/**
 * @author Duc Anh Pham
 * @email ducanh.pham@btaskee.com
 * @create date 2022-11-17 17:34
 * @modify date 2022-11-17 17:34
 * @desc fastlane IOS
 */

 fastlane_version "2.58.0"
 xcode_select "/Applications/Xcode.app"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    sh "cd ../.. && ./fastlane-clean.sh ios"
    # password
    ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']= "dump"
    # Error ITMSTRANSPORTER
    # Get sortName 
    # xcrun altool --list-providers -u 'Email' -p 'SPECIFIC_PASSWORD'
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-asc_provider 85Q6F9K636"
    # Error ITMSTRANSPORTER
    ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'true'
  end

  desc "---------------Submit a new Beta Build to TestFlight---------------"
  lane :beta do
    match(
      type: "appstore",
      git_url: "https://gitlab.com/btaskee/ios-certs.git",
      app_identifier:["com.btaskee.partner"]
      #readonly:true
    ) # more information: https://codesigning.guide
    gym(scheme: "btaskeePartner-prod", workspace: "btaskeePartner.xcworkspace", configuration: "Release") # Build your app - more options available
    pilot(skip_waiting_for_build_processing: true)
  end

  after_all do |lane|
    slack(
      message: "Successfully deployed new bTaskee Partner Version 3 IOS App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
