export default {
  VALIDATE: {
    THIS_FIELD_IS_REQUIRED: "Required Information",
    ERROR_PASSWORD_LENGTH: "Password 6 - 12 characters, no spaces.",
    TYPE_INPUT_INVALID: "Invalid data",
  },
  ERROR: {
    ERROR_TRY_AGAIN: "An error occurred, please try again later! [{{t}}]",
    PHONE_NUMBER_SYNTAX_IS_INCORRECT: "Invalid phone number",
    SEND_OTP_MESSAGE_ACCOUNT_NOT_EXIST: "Phone number does not exist.",
    ACTIVATION_ERROR_CODE: "Invalid Activate Code, please try again",
    USER_NOT_FOUND: "Account does not exist",
    USER_LOCKED: "Your account is temporarily blocked, call us for further information.",
    INVALID_PASSWORD: "Incorrect password. Please re-enter.",
    USER_TYPE_INCORRECT: "The phone number has been registered on bTaskee app (Customer App). Please contact the operator for further assistance!",
    USER_PERMISSION_DENIED: "You are not allowed to access",
    NETWORK_REQUEST_FAILED: "No connection. Please check the network!",
    CANCEL_LIMITED: "Can not cancel this task. You have exceeded the allowed cancellation rate for the last 7 days !",
    ACTIVATION_CODE_INVALID: "Invalid authentication code. Please try again.",
    BUTTON_RELOAD: "Reload",
  },
  PERMISSION: {
    ACCESS_PHOTOS_TITLE: "Request access to photo",
    ACCESS_PHOTOS_CONTENT: "bTaskee requires access to photo for this function",
    WRITE_EXTERNAL_STORAGE_TITLE: "Request storage permission",
    WRITE_EXTERNAL_STORAGE_CONTENT: "bTaskee needs permission to store to your phone ",
  },
  NOTIFICATION: {
    TAB_NOTIFICATION: "Notification",
    NOTIFICATION_MESSAGE: "Do you want to remove notifications?",
    NOTIFICATION_MESSAGE_NOTHING: "There are no notifications as of now.",
    NOTIFICATION_DETAIL: "Notification details",
    TASK_NOTIFICATION: "Task notifications",
    SYSTEM_NOTIFICATION: "System notifications",
    HAPPY_BIRTHDAY_TITLE: "Happy Birthday",
    TITLE_HAVE_NEW_TASK: "New task",
    READ_ALL_NOTIFICATION: "Mark as read",
    TITLE_NOTIFICATION_WARNING: 'The notification was TURNED OFF.',
    CONTENT_NOTIFICATION_WARNING: 'You may miss out on the fascinating tasks. Turn on the notification now.',
    TURN_ON_NOTIFICATION: 'Turn on notification',
  },
  DIALOG: {
    BUTTON_CLOSE: "Close",
    BUTTON_ACCEPT: "Ok",
    TITLE_INFORMATION: "Notification",
    TITLE_ERROR: "Sorry",
    BUTTON_SEE: "See",
    BUTTON_DONE: "Done",
    BUTTON_SEE_AGAIN: "See again",
    BUTTON_CALL_SUPPORT: "Call support",
    UPDATE_SUCCESS: "Update successful",
    BUTTON_CONFIRM: "Confirm",
    BUTTON_UPDATE: "Update",
    BUTTON_NEXT: "Next",
    CANCEL_TASK_SUCCESS: "Please choose other task that is more suitable!",
    ARE_YOU_SURE_TO_GO_BACK: "Are you sure you want to go back?",
    BUTTON_CANCEL: "Cancel",
    BUTTON_SKIP: "Skip",
    BUTTON_SEE_MORE: "See now"
  },
  LOGIN: {
    TITLE_LOGIN: "Login",
    USERNAME: "Phone Number",
    PASSWORD: "Password",
    BUTTON_LOGIN: "Login",
    FORGOT_PASSWORD: "Forgot password?",
    SIGN_UP: "Sign up",
    VERSION: "Version {{t}}",
    BUILD_NUMBER: "Code {{t}}",
    TASKER_APP: "For Tasker",
    MESSAGE_ACCOUNT_ACTIVE: 'Your account was not activated, please activate now.',
    MESSAGE_ACCOUNT_TASKER_LOCK: "bTaskee regrets to restrict your account at this time. Please contact Call Center to continue accepting work.",
    MESSAGE_TOKEN_EXPIRED: "Your account logged in on another device. Change password if unauthorized access. Please log in again to use our service!"
  },
  CHOOSE_LANGUAGE: {
    TITLE: "Choose language",
    VI: "Vietnamese",
    EN: "English",
    TH: "ภาษาไทย",
    ID: "Bahasa Indonesia",
  },
  COUNTRY: {
    INDONESIA: "Indonesia",
    VIETNAM: "Việt Nam",
    THAILAND: "Thái Lan",
  },
  REGISTER: {
    TITLE_REGISTER: "Registration",
    FULL_NAME: "First and last name",
    FULL_NAME_PLACEHOLDER: "Nguyễn Văn A",
    ID_NUMBER: "ID number",
    ID_NUMBER_PLACEHOLDER: "123456789",
    PHONE_NUMBER: "Phone Number",
    PHONE_NUMBER_PLACEHOLDER: "0987654321",
    PASSWORD: "Password",
    PASSWORD_PLACEHOLDER: "As least 6 characters",
    REFERRAL_CODE: "Referral code (if any)",
    REFERRAL_CODE_PLACEHOLDER: "Referral code",
    BUTTON_REGISTER: "Register",
    BUTTON_CHOOSE_WORKING_PLACES: "Choose the working place",
    BUTTON_CONFIRM_OTP: "Activate",
    BUTTON_RESEND_CODE: "Resend",
    BUTTON_RESEND_CODE_1: "Didn't receive OTP?",
    REFERRAL_REWARD: "Enter the referral code from the Tasker to receive many attractive offers from bTaskee.",
    BUTTON_NEXT: "Continue",
    TEXT_OTP:"The OTP will expired in"
  },
  REGISTER_CHOOSE_WORKING_PLACE_CITY: {
    TITLE: "Choose the city",
    CHOOSE_CITY: "What city do you want to work ?",
    NOTE_CHOOSE_SERVICE: "Please note, the services may vary depending on the city and you only choose one city to work",
  },
  REGISTER_CHOOSE_WORKING_PLACE_DISTRICT: {
    TITLE: "Choose your district",
    LIMIT_DISTRICT: "Choose maximum 3 districts",
    CHOOSE_DISTRICT: "Which district do you want to work in?",
  },
  REGISTER_CHOOSE_SERVICES: {
    TITLE: "Choose your services",
    BUTTON_REGISTER: "Register",
    CHOOSE_SERVICES: "What services do you want to work?",
  },
  CONFIRM_CHOOSE_WORKING_PLACE_AND_SERVICES: {
    CONFIRM: "Confirm",
    CONFIRM_NOTE: "Please double-check the information you just registered. Once you have confirmed that the information is correct, you may begin the admission test.",
    SERVICES: "Services",
    DISTRICTS: "Districts",
    SAVE_SUCCESS: "Congratulations, you have successfully updated",
  },
  FORGOT_PASSWORD: {
    TITLE: "Forgot password",
    DESCRIPTION: "Enter your phone number to reset your password",
    RESEND_PASSWORD: "Resend password",
  },
  SET_PASSWORD: {
    TITLE: "Set Password",
    DESCRIPTION: "This password will be used for your next login.",
    NEW_PASSWORD: "New password",
    SAVE: "Save",
    SUCCESS_SET_PASSWORD: "Changed your password successfully.",
    WELCOME: "Welcome back to Btaskee",
  },
  CHANGE_PASSWORD: {
    TITLE: "Reset password",
    DESCRIPTION: "This password will be the password for you to log in next time.",
    INPUT_OLD_PASSWORD: "Enter old password",
    OLD_PASSWORD: "Old password",
    INPUT_NEW_PASSWORD: "Enter new password",
    NEW_PASSWORD: "New password",
    ACCESS: "Confirm",
    SUCCESS_CHANGE_PASSWORD: "Changed your password successfully",
    CHANGE_PASSWORD: "Reset password",
    WELCOME: "Welcome to Btaskee",
  },
  CHOOSE_COUNTRY: {
    TITLE_CHOOSE_COUNTRY: "Choose country",
    BUTTON_NEXT: "Next",
    TITLE: "Where do you live?",
  },
  OTP: {
    TITLE: "Account Activation",
    HELLO: "Hello",
    INSTRUCTION_OTP: "The ACTIVATION CODE has been sent to your phone {{t}}. Please check SMS and enter the CODE to the textfield below.",
    ACTIVATION_CODE: "Activation Code",
    RESEND_CODE_ERROR: "You have pressed send too many times. Please try again later.",
  },
  TASK_DETAIL: {
    TITLE: "Task Details",
    DESCRIPTION_FOR_PROMOTION: "Add to your promotion account",
    PAYMENT_METHOD_LABEL: "Payment method:",
    TYPE_HOUSE_LABEL: "House type: ",
    NOTE_LABEL: "Note: ",
    BUTTON_SEE_FULL_NOTE: "See all",
    BUTTON_SLIDE_TO_CONFIRM: "Slide to get task",
    BUTTON_FAQ: "Q&A",
    STATUS_WAITING_CONFIRM: "Awaiting Asker confirmation",
    WITHDRAW_TASK: "Withdraw from this task",
    BEGIN_WORK: "Start working",
    TASK_IS_WORKING: "Task in progress",
    DURATION_NOTE: "Work for {{duration}} hours",
    COUNT_DOWN_TIME_START_JOB: "Task will begin after {{time}}",
    COUNT_DOWN_TIME_START_JOB_TASK_ITEM: "Begin after:",
    COUNT_DOWN_TIME_FINISH_JOB: "Task will end after {{time}}",
    FINISH: "Done",
    DURATION_HOUSE: "{{duration}} rooms : {{area}}",
    APARTMENT: "Apt/Condo",
    HOME: "House/Town house",
    VILLA: "Villa",
    HOTEL: "Hotel",
    DOG: "Dog",
    CAT: "Cat",
    REQUIREMENTS_COOKING: "Cooking",
    REQUIREMENTS_IRON: "Ironing",
    REQUIREMENTS_2_SHOTS_VACCINE: "Received 2 shots of vaccine",
    REQUIREMENTS_NEGATIVE_TEST_COVID: "Negative test result for COVID-19 within 7 days",
    REQUIREMENTS_BRING_TO_TOOLS: "Include cleaning supplies",
    CALL_WITH_PHONE_NUMBER: "Call by phone number",
    CALL_WITH_BTASKEE_APP: "Call by bTaskee app",
    ACCEPTED_SUCCESS: "You accepted this task successfully",
    ACCEPTED_TASK_WAITING_SUCCESS: "Get the job successfully. Waiting for Customer to confirm",
    PAYMENT_METHOD_CASH: "Cash",
    PAYMENT_METHOD_TRANSFER: "Bank transfer",
    MY_TASK_EMPTY: "You have not received any job as of this date",
    NEW_TASK_EMPTY: "No new tasks yet",
    BUTTON_TRANSLATE_NOTE: "Translate",
    NOTES_TITLE: "Note",
    BUTTON_DONE: "Done",
    NUMBER_OF_TASK: "{{number}} Tasks",
    BUTTON_GO_TO_DATE: "Today",
    NUMBER_ACCEPTED_TASK: "Taskers accepted this task: ",
    TITLE_CANCEL_TASK: "Cancellation",
    BUTTON_CANCEL: "Cancel",
    BUTTON_NO: "Back",
    CONFIRM_CANCEL_TEXT: "Are you sure you want to cancel this task?",
    CANCEL_TASK_REASON_NEARBY_TASK_PLACE: "Have arrived, cannot contact customer (Require turn on your location).",
    CANCEL_TASK_REASON_SO_FAR_AWAY: "Accepted the task too far.",
    CANCEL_TASK_REASON_WRONG_DATE: "Accepted the task wrong date.",
    CANCEL_TASK_OTHER_REASON: "Others.",
    CANCEL_TASK_REASON_TEXT: "Please click one of the reasons below to cancel this job",
    CANCEL_REASON_IS: "The cancel reason is:",
    CANCEL_FREE: "Fee",
    NOTE_CANCEL_TASK: "Fine will be minus into your main account if you cancel the task.",
    PLACEHOLDER_TEXT_INPUT: "Please enter the reason you want to cancel this job...(Required information)",
    TITLE_MODAL_CALL: "Contact with customers",
    PREMIUM_TASK: "Premium service",
    TASK_FROM_SUBSCRIPTION: "Monthly subscription",
    POP_UP_DRAW_TASK_TXT: "Your credibility will be reduced. Are you sure you want to withdraw from this job?",
    CANCELED: "Canceled",
    DONE: "Done",
    CANCELED_BY_TASKER: "Cancelled by yourself",
    CANCELED_BY_ASKER: "Cancelled by customers",
    CANCELED_REASON: "Reason",
    NUMBER_OF_DINER: "Number of eating people: ",
    NUMBER_OF_DISH: "Number of dishes",
    TASTE: "Taste: ",
    EATING_TIME: "Eating time: ",
    BAC: "North",
    TRUNG: "Central",
    NAM: "South",
    FRUIT_DESERT: "Dessert fruits",
    GO_MARKET: "Go market",
    DISH_WAITING: "Waiting",
    CALL_CUSTOMER_TO_UPDATE_DISH: "The list of dishes has not been updated. After getting the task, you must call the customers to update the list of dishes.",
    BUDGET_TO_MARKET: "Shopping budget: ",
    AIR_CONDITIONER_NUMBER: "{{t}} units",
    ANY_CAPACITY: "All AC capacity",
    CAPACITY_LESS_THAN: "Capacity less than {{t}}HP",
    CAPACITY_GREATER_THAN: "Capacity greater than {{t}}HP",
    CAPACITY_FROM_TO: "Capacity from {{t1}}HP to {{t2}}HP",
    CAPACITY_LESS_THAN_BTU: "Capacity less than {{t}}BTU",
    CAPACITY_GREATER_THAN_BTU: "Capacity greater than {{t}}BTU",
    CAPACITY_FROM_TO_BTU: "Capacity from {{t1}}BTU to {{t2}}BTU",
    TYPE_AC: "A/C Type",
    QTY: "QTY",
    TASK_AIR_CONDITIONER: "Task",
    HOSTEL_NAME: "Location name: ",
    TOTAL_AREA: "Total area: {{t}}m²",
    IMAGE_TITLE: "Images",
    NAME_ROOM: "Room name: {{t}}",
    AREA_ROOM: "Area: {{t}}m²",
    NOTE_ROOM: "Notes: {{t}}",
    HOSTEL_DETAIL: "Room information",
    NUMBER_TASKER_ACCEPTED: "Tasker accepted: ",
    LIST_OF_TASK: "List of task",
    BUTTON_SEE_LIST: "Detail",
    TITLE_LIST_CLEANING_TOOL: "Tools list",
    OVERVIEW: "General",
    NUMBER_TOTAL_SOFA: "Furniture amount: ",
    SOFA_TYPE: "Type",
    MATTRESS: "Mattress",
    DRY_CLEANING: "Dry laundry",
    WASHING: "Wet laundry",
    CURTAIN: "Curtain",
    CARPET: "Carpet",
    BED: "Mattress",
    AREA_DISINFECTION: "Area: ",
    DISINFECTION_AREA_FROM_TO: "{{t1}}m² - {{t2}}m²",
    DISINFECTION_AREA_CUSTOM: "{{t}}m²",
    DISINFECTION_PROCEDURE: "Disinfection spray process",
    DISINFECTION_PROCEDURE_CONTENT_TITLE: "Proceed to spray disinfectant",
    DISINFECTION_PROCEDURE_CONTENT_1: "1. Prepare chemicals for spraying disinfectants.",
    DISINFECTION_PROCEDURE_CONTENT_2: "2 Turn off the ventilation system. Turn off the air conditioner and turn off the fan.",
    DISINFECTION_PROCEDURE_CONTENT_3: "3. Living room: ceiling, floor, wall, cabinet, door, table...",
    DISINFECTION_PROCEDURE_CONTENT_4: "4. Bedroom: ceiling, floor, wall, cabinet, under the bed...",
    DISINFECTION_PROCEDURE_CONTENT_5: "5. Kitchen: ceiling, floor, wall, dining table, chair, shelf...",
    DISINFECTION_PROCEDURE_CONTENT_6: "6. Bathroom: ceiling, floor, wall, sink...",
    DISINFECTION_PROCEDURE_CONTENT_7: "7. Check the work again after it is done.",
    SHOPPING_TIME_LABEL: "Shopping Time: ",
    DURATION: "{{t}} hours",
    ESTIMATED_PURCHASE_AMOUNT: "Estimated purchase amount of customer: ",
    SHOPPING_LIST: "Shopping list",
    AMOUNT_CHILD_LABEL: "Number of child",
    AGE_OF_CHILD: "Age",
    NUMBER_OF_CHILD: "Child",
    BUTTON_CONFIRM: "Confirm",
    TET_BOOKING: "Tet Booking tasks",
    YOUR_WORK: "Your task",
    YOU_ARE_LEADER: "You are a leader of this task",
    YOU_ARE_MEMBER: "You are a member of the group",
    WORK_ACCORDING_TO_ASSIGNMENT: "- Working as assigned by the leader.",
    PLEASE_CANCEL_TASK_BEFORE_A_TIME: "- If you want to cancel the task, please contact the operator before task starts {{t}} hour(s) for assistance.",
    RECEIVE_CASH_FROM_LEADER: "When the task is done, please contact the leader to receive money.",
    OTHER_PAYMENT: "- When the task is done, money will be transferred to main account of each members.",
    RECEIVE_CASH: "- When the task is done, receives cash from customer and divide it to other teammates as below information.",
    DIVIDE_WORK: "- Divide task to you and your teammates .",
    NEED_TO_CONTACT_PARTNER: "- The leader need to contact members before the task starts. If there is any member cannot go to work, please contact the operator for assistance.",
    TITLE_TASK_WAITING: "Waiting Task",
    BUTTON_CHAT: "Chat",
    BUTTON_CALL: "Call",
    MONEY_GET_MORE: 'Collect cash from customers',
    TASK_WAS_CONFIRMED: "This task has been accepted.",
    SEE_MORE: "See more",
    CANCEL_TASK_TASKER_SO_FAR_AWAY_TASK_PLACE: 'You can not cancel the task with this reason. The system only accept this cancel reason if you are near the workplace.',
    CANCEL_TASK_LOCATION_NOT_FOUND_TEXT: 'We can not detect your location. Please allow location access and restart the application to cancel this task.',
    NEW_ASKER_NOTE: 'This is customer who use new service, you should contact the customer before arriving to customer home.',
    TITLE_LIST_OF_TOOL_FOR_TASKER: "List of Cleaning supplies have to bring along",
    TITLE_ALERT_FAQ: "Warning",
    MESSAGE_ALERT_FAQ_WAITING: "If you leave this task, you will not be charged.",
    MESSAGE_ALERT_FAQ_CONFIRMED: "If you cancel this job, you will incur cancellation fees according to regulations.",
    ACCIDENT_INSURANCE: 'Task supported by bCare',
    DESCRIPTION_CANCEL_TASK:"Please choose another task that is more suitable!",
    TODAY: "Today",
    TOMORROW: "Tomorrow",
    QR_CODE:"Your QR Identification",
    COST_INCURRED: "To arise more",
    DESCRIPTION_FOR_PROMOTION_LEADER: "Will be divided equally and added to the member's promotion account",
    MONEY_GET_MORE_MEMBER: "Get more from the leader",
    PAYMENT_MOTHOD_BANKER: "Bank transfer",
    PAYMENT_MOTHOD_CASH: "Cash",
    PAYMENT_MOTHOD_PROMOTION: "Promotion",
    MONEY_GET_MORE_LEADER: "Get more from you",
    SOFA_CLEANING_TYPE_MORE: "More than 6 seats",
    CURTAIN_CHOOSE_SERVICE_ON_SITE: "On site service",
    CURTAIN_CHOOSE_SERVICE_OFF_SITE: "Off site service",
    WORKED_FOR_ASKER: "Used to work for this customer",
    ASKER_OFTEN_USE_SERVICE: "Customers use the service regularly",
    TIP: "Tip:",
    CANCEL_FEE: "Cancellation fee is ",
    MORNING: "Morning",
    AFTERNOON: "Afternoon",
    EVENING: "Evening",
    VACUUMING_OFFICE_CARPETS: "Vacuuming office carpets",
    CLEANING_GLASSES: "Cleaning glasses",
    WM_TYPE: "W/M Type",
    WM_SERVICES: "Services",
    NUMBER_OF_WM: "Number of washing-machine",
    CALL_WITH_MEMBER: "Contact with team member",
    CALL_WITH_LEADER: "Contact with team leader",
  },
  HOME: {
    TAB_HOME: "Home",
    TAB_BENEFIT: "Benefit",
    TAB_ACCOUNT: "Account",
    BTASKEE: "bTaskee",
    TAB_MY_TASK: "Received",
    TAB_NEW_TASK: "New Task",
    TAB_NOTIFICATION: "Inbox",
    NET_DISCONNECTED: "No connection. Please check the network again!",
    NET_ONLINE: "Connected!",
  },
  NOTIFICATION_CHAT: {
    TAB_TITLE: "CHAT",
    NOTHING: "There are currently no messages.",
  },
  NOTIFICATION_SYSTEM: {
    TAB_TITLE: "Notification",
    INBOX: "Mailbox",
  },
  TAB_BENEFIT: {
    TRAINING_PROGRAM: "Training program",
    MONTHLY_REWARD: "Monthly reward",
    BREWARD: "bReward",
    COMMUNITY: "Community",
    BCARE: "bCare",
    INSURANCE: "Accident support policy",
    LEVEL_MONTHLY_REWARD: "Need to work {{t}} hours overtime to reach the bonus in the next month",
    MAX_LEVEL: "Congratulations on reaching the highest bonus level this month.",
    HOURS_OF_AWARDS: "{{t}} hours ",
    PROMOTION: "Promotion",
    BREWARD_DETAIL: "bReward Detail",
    LABEL_REWARD_INFO: "Reward Information",
    LABEL_CONDITION: "Conditions",
    BUTTON_REDEEM: "Redeem",
    NUMBER_POINT: "bPoint",
    TITLE_ALERT_CONFIRM_REDEEM: "Confirm Redemption",
    CONTEXT_ALERT_CONFIRM_REDEEM: "Redeem this coupon exchange",
    BUTTON_CONFIRM: "Confirm",
    BUTTON_LATER: "Later",
    FREE: "Free",
    REDEEM_SUCCESS: "Redemption Success",
    NEW_GIFT: "New",
    USED_GIFT: "Used",
    LIST_INCENTIVE_EMPTY: "No Rewards yet.",
    MY_GIFT: "My Gift",
    EXPIRED_ON: "Expired on:",
    EXPIRED: "Expired",
    USED: "Used",
    DETAIL_REWARD_EMPTY: "Promotion not available yet!",
    LABEL_SAVE_SUCCESS: "Success",
    MONEY: "{{currency}}{{cost}}",
    MONTHLY_REWARD_DETAIL: "Reward Details",
    MORE_HOURS:"Need extra work",
    MORE_REWARD:"Next Reward",
    TIME_WORK_IN_MONTH:"Working hours this month:",
    REWARD_WORD_IN_MONTH:"Rewards received this month:",
    HOURS:"Hours",
    DAY_LEFT:"Days left:",
    DAY:"Days",
    NEXT_STEP:"Next step:",
    VIEW_DETAIL:"View detail",
    DETAIL_REWARD:"Detail reward",
    NEXT_REWARD: "Next reward",
    TRAINING: "Training",
    COMMUNITY_CONTENT: "Exchange and share experiences with other bTaskers across the country.",
    BREWARD_CONTENT: "To receive a `multitude of gifts` when earning bPoints to redeem with bRewards.",
    TRAINING_CONTENT: "Let's promote to the higher quality with bTaskee training courses!",
    BCARE_CONTENT: "The Tasker cannot deal with the risk, so let bCare assist the Tasker.",
    PREMIUM_CONTENT: "Let's strive to become a premium Tasker!",
    EMPTY_DATA: "Please come back after activating your account to receive special benefits exclusive to bTaskee partner.",
    SEARCH: "Search",
    SEARCH_VOUCHER: "Search voucher",
    ACCOUNT_LOCK: "Locked"
  },
  TAB_ACCOUNT: {
    PROFILE: "Profile",
    FINANCE: "Finance",
    WEEKLY_REPORT: "Weekly report",
    HISTORY_INCOME: "History Income",
    INCOME: "Income",
    SERVICES: "Services",
    DISTRICTS: "Districts",
    LEVEL: "Level",
    PREMIUM: "Premium",
    TITLE_QA_CODE: "Your QA Identification",
    YOUR_REFERRAL_CODE: "Your referral code",
    COPY: "Copy",
    LABEL_COPY: "Copied",
    SEE_INFORMATION: "See information",
    LOGOUT: "Log out",
    LOGOUT_CONFIRM: "Are you sure you want to sign out?",
    LEVEL_1: "Amateur",
    LEVEL_2: "Professional",
    HOLDING_ACCOUNT: "Temporary job payment: ",
    MAIN_ACCOUNT: "Main account",
    PROMOTION_ACCOUNT: "Promotion account: ",
    INCOME_THIS_WEEK: "Your Income this week",
    COMPLETED_TASK: "Completed tasks",
    INCOME_TOTAL: "Total income",
    INCOME_IN_MONTH: "Your income this month",
    TOPUP: "Top-up",
    WITHDRAW: "Withdraw",
    AMOUNT_WITHDRAW: "Pending withdrawal",
    AMOUNT_WITHDRAW_NOTE: "Your payment is being processed by the system.",
    TRANSACTION_HISTORY: "Transaction History",
    AMOUNT: "Amount",
    BALANCE: "Available balance",
    WITHDRAW_NOTE: "Note: There must be at least {{amount}} {{currency}} in your account in order to continue receiving tasks.",
    NEXT: "Next",
    CONFIRMATION: "Confirmed",
    CONFIRMATION_WITHDRAW: "Are you sure you want to withdraw money from your account?",
    BANK_ACCOUNT: "Account",
    FMAIN_ACCOUNT_NOTE: "is your account balance shows the current amount of money that you can use to accept tasks or withdraw when you meet the requirements.",
    PROMOTION_ACCOUNT_NOTE: "is the account containing the amount of bonus and support that Taskers receive, as well as the tasks that customers use promo codes for. This account is only used for receiving tasks.",
    ON_HOLD_ACCOUNT: "Temporary work fee",
    ON_HOLD_ACCOUNT_NOTE: "The estimated job fee is the amount of money held when you are accepting a task. If you complete the task, this amount will be deducted from your promotion account. When the promotion account is depleted, it will be deducted from your main account.",
    PAYOUT_NAME: "Withdrawal request",
    PAYOUT_WAIT: "Waiting",
    PAYOUT_PAID: "Paid",
    PAYOUT_CANCELED: "Canceled",
    PAYOUT_REJECTED: "Rejected",
    PAYOUT_SUCCESS: "Your request created successfully",
    MONTH: "Month",
    WEEK: "Week",
    STAR: "Star",
    BELOW: "Below average",
    TASK: "Task",
    INCREASE_TASK: "Increase {{task}} tasks compared to last week.",
    DECREASE_TASK: "Reduce {{task}} tasks compared to last week.",
    GOOD_REVIEW: "Good review",
    BAD_REVIEW: "Need to improve",
    TASK_HISTORY: "History Task",
    INFORMATION: "Information",
    EMPTY_TASK_IN_MONTH: "No jobs in this month",
    EMPTY_TRANSACTION_IN_MONTH: "No deals in this month",
    LIST_OF_EMPLOYEE: "List of employee",
    REVIEW: "Review",
    ERROR_ON_HOLD_ACCOUNT_WHEN_WITHDRAW: "You have 1 pending withdrawal request",
    TRANSACTION: "Transaction",
    PAYOUT: "Request",
    LABEL_TRANSACTION_TAB: "Recently",
    EMPTY_TRANSACTION: "You don't have any transactions yet",
    EMPTY_PAYOUT: "You don't have any requests",
    TITLE_CHECK_NOTIFICATION: "Test notification",
    BUTTON_CHECK_NOTIFICATION: "Send notification",
    TITLE_TEST_NOTIFICATION: 'Notifications are working well',
    INFO_TEST_NOTIFICATION: 'The application will automatically shut down to check the notification. Do you want to proceed?',
    TITLE_CARD_SHARE: "Share",
    CONTENT_CARD_SHARE: "Share the app to receive gifts",
    BUTTON_VIEW_MORE: "View more",
    TEXT_QR: "Please show your QR code so customers can identify.",
    LABEL_DELETE_ACCOUNT: "Delete account",
    TEXT_DELETE_ACCOUNT: "Are you sure?",
    TITLE_RESTART_APP: "Restart the application",
    BUTTON_RESTART_APP: "Start now",
    TEXT_RESTAR_APP: "Are you sure you want to restart the application?",
    NUMBER_ACCEPT_TASK: "Currently have {{numberTasks}} tasks",
    NUMBER_OF_POINT_LABEL: "Preferential point",
    NUMBER_OF_POINT: "{{t}} points"
  },
  CHAT: {
    TRANSLATING: "Translating ...",
    TITLE: "Chat",
    PREPARED_MESSAGE_THANK: "Thank you so much.",
    PREPARED_MESSAGE_WAIT_ASKER: "I am on my way home. Please wait for me a little bit. Thank you!",
    GPS_NOT_FOUND: "Location could not be found!",
    TYPE_A_MESSAGE: "Type a message",
    SERVICE_REQUEST_GPS: "Please enable GPS to use this service!",
    PT1_MAP_POPUP_PERMISSION_REQUEST_GPS_CLOSE: "Close",
    OPEN_SETTINGS: "Open setting",
    MODAL_CONFIRM_SHARE_LOCATION_TITLE: "Do you want to share your current location?",
    PREPARED_MESSAGE_CONFIRMATION: "Hi! I accepted your task. I will come on time.",
    PREPARED_MESSAGE_REQUIRE_ADDRESS_EXACTLY: "Please tell me the accurate address. Thank you!",
    PREPARED_MESSAGE_COMING: "I am coming to do your task. Please keep in contact!",
    PREPARED_MESSAGE_WAIT_20_MINUTES: "Hello, I have come to your location but could not contact you. I will wait 20 minutes, and if I still cannot contact you then I need to cancel the task.",
    PREPARED_MESSAGE_WAITED_20_MINUTES: "I waited 20 minutes and still could not contact you. This task shall be cancelled.",
    PREPARED_MESSAGE_AT_RECEPTION: "I am waiting at the receptionist lobby, please kindly come down to pick me up.",
    LABEL_CHAT_WITH_BTASKEE: "Chat with bTaskee"
  },
  TRAINING_INPUT: {
    TITLE: "Test",
    LOADING_TITLE: "Getting information",
    INSTRUCTION_PASS_TEST: "Note: Your test result must be above 80% to pass, please read carefully before answer.",
    ERROR: "Failed to get information. Please try again!",
    START: "Start",
    RELOAD: "Please try again!",
    FINISH: "Submit",
    ACCEPT_TEST_CONFIRMATION: "Do you read the note carefully and want to take the test?",
    FINISH_TEST_CONFIRMATION: "Are you sure?",
    FAILD: "Test failed. Please call the hotline for assistance.",
    RESULT_TEST_FAILD: "You haven't passed the test. You have {{t}} times left to retake the test. Be careful and try your best!",
    RESULT_TEST_FAILD_LIMITED: "You did not pass the test. Please contact the operator for more details!",
    SEE_RESULT: "Results",
    GRADING_TEST: "Checking results .... Please wait!",
    QUIT_TEST: "Exit test",
    TRAINING_TASKER_PASS_TITLE: "Welcome to bTaskee",
    PREPARE_PROFILE: "Please prepare documents, including:",
    UNVERIFIED_TASKER_PROFILE_1: "01 Curriculum Vitae:",
    UNVERIFIED_TASKER_PROFILE_2: "02 copies of Identification:",
    UNVERIFIED_TASKER_PROFILE_3: "01 copy of Household registration (Photo):",
    UNVERIFIED_TASKER_PROFILE_4: "01 Confirmation of Conduct (Notarized):",
    NOTE_FOR_UNVERIFIED_TASKER_PROFILE: "Notarized by local police  and valid for 6 months from the date of issuance.",
    APPLY_YOUR_PROFILE_AT_COMPANY_NOTE: "Submit all the documents in person at one of bTaskee's offices in Ho Chi Minh city where you registered.",
    TIME_TO_APPLY: "Time for Document Submission",
    MORNING_TO_APPLY: "Morning:",
    AFTERNOON_TO_APPLY: "Afternoon:",
    TIME_MORNING: "09:00 AM",
    TIME_AFTERNOON: "14:00 PM",
    ARRIVE_APPLY_LATE_NOTE: "If you are late, you will have to reschedule for another day",
    UNVERIFIED_TASKER_SUBMITION_ADDRRESS: "Address for document submission:",
    CALL_SUPPORT_FOR_MORE_DETAIL: "Call for support if you need further detailed information",
    PHONE: "Phone number: {{t}}",
    CALL_WITH_HR: "Please contact staff prior to your arrival to receive suitable appointment and parking arrangements.",
    DESCRIPTION_PLAY_VIDEO: "Let's remember the lesson better with the summary below",
    NEXT: "Continue",
    DONE: "Complete",
    TRAINING_PROGRAM: "Training Program",
    READING_TIME: "Learning time:",
    BY_MINUTUES: "Minute",
    TRAINING: "Lesson",
    TRAINING_DESCRIPTION: "Please take a quiet place and your free time so that your focus on the lesson is highest.",
    TEST: "Test",
    TEST_DESCRIPTION: "Please read the lesson summary carefully to take the test more effectively",
    PASS: "Pass",
    FAILED: "Failed",
    REMAINING_TIME: "Number of attempts left:",
    LESSON: "Lesson {{t}}",
    TRAINING_DETAIL_TITLE: "Detail lesson",
    SUMMARY: "Summary",
    FINISH_TEST_SUCCESS: "Congratulations on completing the test",
    TEST_FAILD_LIMITED: "You did not pass the test",
    TEST_AGAIN: "Redo the test",
    COME_BACK_LATER: "Come back later",
    NUMBER_OF_CORRECT_ANSWER: "Number of correct answers: ",
    TAKE_THE_TEST: "Take the quiz now!",
    INFO_TEST: "Result: {{t1}}/{{t2}}",
    DES_SEE_TEST: "The quiz will be opened after watching the video",
    CORRECT: "Correct",
    WRONG: "Wrong",
  },
  TRAINING_PREMIUM: {
    TITLE: "Training Premium",
    SHARE: 'Share',
    TASKER_PREMIUM_TITLE: 'Certificate',
    TASKER_PREMIUM_SUB_TITLE: 'Senior collaborator',
    CONTENT: "Regulations on granting senior collaborators' degrees",
    PASS_TITLE: "Congratulations on passing the test",
    REGULATIONS_TASKER_PREMIUM: 'Operation regulations for senior collaborators',
    WITHDRAW_TASKER_PREMIUM_TITLE: 'Operation regulations for senior collaborators',
    REGULATIONS_TASKER_PREMIUM_1: 'Apply the provisions and agreements according to the signed Cooperation Agreement Memorandum when registering to become a bTaskee contributor.',
    REGULATIONS_TASKER_PREMIUM_2: 'Senior collaborators will be **DISCLOSED** for violating the regulations on:',
    REGULATIONS_TASKER_PREMIUM_2_1: "Negotiate privately with bTaskee's customers outside the system",
    REGULATIONS_TASKER_PREMIUM_2_2: 'Violation of issues of uniforms and manners.',
    REGULATIONS_TASKER_PREMIUM_2_3: 'Service quality is not guaranteed',
    REGULATIONS_TASKER_PREMIUM_2_4: 'Violation of behavioral issues.',
    REGULATIONS_TASKER_PREMIUM_3: "When being stripped of the associate's license, the collaborator will:",
    REGULATIONS_TASKER_PREMIUM_3_1: 'Can not accept Premium task',
    REGULATIONS_TASKER_PREMIUM_3_2: 'Not allowed to participate in the monthly honor program.',
    REGULATIONS_TASKER_PREMIUM_4: 'Every day will check and:',
    REGULATIONS_TASKER_PREMIUM_4_1: 'Withdrawal if Tasker violates.',
    REGULATIONS_TASKER_PREMIUM_4_2: 'Re-issue the license if Tasker meets the conditions.',
    CONDITION_TASKER_PREMIUM_TITLE: 'Conditions to upgrade to become a premium CTV of bTaskee',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_1: 'Have a stellar grade point average of 4.80 or higher.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_2: 'There are over 10 Preferred Customers.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_3: 'There is a full set of tools according to bTaskee standards.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_4: 'Already have a vacuum cleaner',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_5: 'Already have a bTaskee backpack',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_6: 'Have completed at least 200 jobs on the bTaskee system.',
    TITLE_TASKER_PREMIUM: "Training now",
    LABEL_START_NOW: "Becoming Premium",
  },
  INTRO_APP: {
    BUTTON_START: "Start",
    TITLE: "Benefit with bTaskee",
    LEARN_MORE: "Learn more",
    START_WORKING: "Let turn your free time to income",
    ALREADY_ACCOUNT: "Do you already have an account?",
    FLEXIBLE_TIME: "Flexible Time",
    HIGH_INCOME: "High Income",
    COMMUNITY_REWARD: "Community & Rewards",
    FLEXIBLE_TIME_1: "Working hours are flexible and depend on your choice",
    FLEXIBLE_TIME_2: "Convert your free time into income",
    HIGH_INCOME_1: "Earn up to 20 million/month if you actively and diligently follow up to receive the job.",
    COMMUNITY_REWARD_1: "The large community connects, shares and honors the noble values of people and The Domestic help",
    COMMUNITY_REWARD_2: "Collaborators are entitled to a support policy of up to VND 100 million.",
    FLEXIBLE_TIME_ID:"You can get the wage of the full time job with the random free time.",
    HIGH_INCOME_ID:"Working hours are flexible and depend on your choice. Convert your free time into income.",
    COMMUNITY_REWARD_ID:"Take part in a modern, dynamic and practical community.",
    HIGH_INCOME_TITLE_TH:"Earn big, work easy!",
    HIGH_INCOME_CONTENT_TH:" With bTaskee, you can make over 30,000 baht a month, plus tips and bonuses!",
    FLEXIBLE_TIME_TITLE_TH:"Be the boss of your life!",
    FLEXIBLE_TIME_CONTENT_TH:"With bTaskee, you choose when and how much you work. No more working 8 hours a day!",
    COMMUNITY_REWARD_TITLE_TH:"Family first!",
    COMMUNITY_REWARD_CONTENT_TH:"  With bTaskee, you get to spend more quality time with your loved ones. Work-life balance? Achieved!",
  },
  SETTINGS: {
    SETTINGS: "Settings",
    LANGUAGE: "Language",
    NOTIFICATION: "Notify",
    NOTIFICATION_TASK: "Notification Task",
    NOTIFICATION_ON: "On",
    NOTIFICATION_OFF: "Off",
    FEE_SCHEDULE: "Free Schedule",
    YOUR_WORKTIME: "Free time",
    BUSY_TIME: "Busy time",
    REMIND: "Remind",
    MINUTE: "Minute",
    HOURS: "Hours",
    MORNING: "Morning",
    AFTERNOON: "Afternoon",
    EVENING: "Evening",
    UPDATE: "Update",
    NOTE_TASKER_UPDATE_SCHEDULE: "You can only update once (if you want to change, please contact bTaskee).",
    TEXT_VIBRATION:"It vibrates when receiving a new job notification."
  },
  TOPUP: {
    MIN_COST_TOPUP: "Minimum deposit amount is:",
    INSTRUCTTION_NOTE: "Note: Your account will be updated within 24 hours after you transfer money.",
    BANK_TRANFER: "Ngân hàng:",
    BANK_INFO_ACCOUNT_HOLDER: "Account Holder:",
    BANK_INFO_ACCOUNT_NUMBER: "Account Number:",
    BANK_INFO_TRANFER_CONTENT: "Note:",
    BANK_INFO_CONTENT_SYNTAX: "Enter full name and phone number",
    LBL_EX_DEPOSITE: "E.G. Nguyễn Thị A 0123456789",
    NOTE_DEPOSIT_MONEY: "NOTE: Money deposited into the account can only be used to receive work, not to pay other expenses such as buying backpacks, uniforms, etc.",
    SAVE_IMAGE: "Save image",
    SAVE_IMAGE_SUCCESS: "Save image success",
    BTASKEE_THAILAND: "bTaskee (Thailand)",
    METHOD: "Top-up method",
    OPEN_BANK_APP: "Open bank applications",
    SCAN: "Scan",
    SELECT_PHOTO: "Select photos",
    BUTTON_DONE: "Done",
    MIN_MONEY: "Minimum amount that can be deposited",
    MAX_MONEY: "Maximum amount that can be deposited",
    IMAGE_DOWNLOAD_PERMISSTION: "Image Download Permission",
    IMAGE_DOWNLOAD_PERMISSTION_MESS: "Your permission is required to save images to your device",
    COMING_SOON: "Coming soon",
    NOTE:"Note:",
    QR_CODE: "Scan QR code",
    NOTE_LABEL: "Note: ",
    QR_NOTE: "How to top up money online via QR code?",
    STEP_1: "Click Save to download the QR code image to your device.",
    STEP_2: "Open your banking app",
    STEP_3: "Go to Scan or Scan QR, then select the QR code image you just took from your photo library.",
    STEP_4: "Please enter the amount you want to deposit into your account, note that the minimum deposit is {{money}}.",
    TOPUP_TO_BANK: "Top up your account",
  },
  WITHDRAW: {
    NOTE: "Note: You must have at least {{currency}}{{amount}} in your account in order to continue receiving tasks.",
    VALID_AMOUNT: "The amount of money per withdrawal is from {{currency}}{{minCost}} to {{currency}}{{maxCost}}",
    ERROR_SCOPE_OF_MONEY: "The amount of money you entered is not within the allowed withdrawal range. Please try again!",
    MONEY: " {{currency}}{{cost}}",
    RECEIPT_OF_MONEY_INFO: 'Your withdrawal request will be processed on Tuesdays and Fridays every week. The bank will transfer the money to you within 1-3 business days.',
    TECHCOMBANK: "VietNam Technological and Commercial Joint Stock Bank",
    TRANSFER_FEE: "Transfer fee",
    ERROR_TCBANK_NUMBER: "You have not provided your bank account number. Please update your bank information before withdrawing money.",
    UNABLE_TO_WITHDRAW_1: 'You need at least ',
    UNABLE_TO_WITHDRAW_2: ' in order to withdraw money, you must have an available account!.',
    LABEL_NOTE: "Note: ",
    MIN_MONEY_NOTE: "To continue receiving tasks, your available account must have at least: ",
    MIN_MONEY: "Minimum withdrawal amount: ",
    SCOPE_OF_MONEY:"You can withdraw an amount from {{t1}} to {{t2}}.",
    KASIKORN_BANK: "Kasikornbank",
    RECEIPT_OF_MONEY_INFO_TH: 'You will receive money into your account every Tuesday or Friday from 18.00 onwards, which must be requested at least 1 day in advance. If the request is made on Tuesday or Friday, it will be counted as the next withdrawal cycle. It is recommended that you press withdrawals on Mondays or Thursdays to accumulate more withdrawal amounts.',
  },
  ABOUT_BTASKEE: {
    TITLE: "About bTaskee",
    DESCRIPTION: "Our community activities",
  },
  NEW_VERSION_APP: {
    CONTENT_UPDATE_APP: "There is a new version. Please update to experience the new features.",
    TITLE_BUTTON_UPDATE_VERSION: "Notify",
    MAINTENANCE_APP_TITLE: "System is updating. Please comeback later.",
    NEW_VERSION_BUTTON: "Update now",
  },
  CAR_ADVERTISING: {
    YOUR_REFERRAL_CODE: "Your referral code",
    BUTTON_SHARE_REFERRAL_CODE: "Share referral code",
    NUMBER_PEOPLE_REGISTER_WITH_REFERRAL: "Number of customers who have created accounts",
    NUMBER_PEOPLE_DONE_TASK: "Number of customers who booked the first task",
    TITLE_HISTORY_TRANSACTION: "Transaction history",
    COST_AND_CURRENCY: "{{cost}} {{currency}}",
    INVITE_ASKER_TEXT_HEAD: "Register a new account with referral",
    INVITE_ADVERTISING_SHARE_TEXT: "Register to become Tasker with referral code {{referralCode}} to get {{referralValue}} in promotion account after you completes the first task.\nOr receive 01 {{voucherValue}} voucher after you successfully register a customer account with a referral code {{referralCode}}",
    INVITE_ASKER_TEXT_TAIL: "to get voucher worth when the first task is finished.",
  },
  MONTHLY_REWARD: {
    TITLE: "Reward Detail",
    CONGRATULATIONS: "Congratulation on you!",
    BUTTON_REWARD: "Reward now",
  },
  LAUNDRY: {
    TITLE_WAITING_COLLECT: "Waiting to receive",
    TITLE_WAITING_RETURN: "Waiting to pay",
    RETURN_DATE: "Return time: ",
    CHECK_AND_CONFIRM: "Check and confirm",
    PICK_UP_CLOTHES: "Pick up items",
    COLLECTION_DATE: "Delivery date: ",
  },
  SUPPORT:{
    TITLE: "Support",
    DESCRIPTION: "Support staff and working time.",
    TITLE_DAILY_WORK: "Daily work support",
    TITLE_PERSONNEL_WORK:"HR Support",
    TITLE_PERSONNEL_WORK2:"(Opening, blocking accounts, taking a break, etc.)",
    TIME_DAILY_WORK: "Monday - Saturday:",
    TIME_PERSONNEL_WORK:"Monday - Friday:",
    SUNDAY:"Sunday",
    SATURDAY:"Saturday",
    TIME_IN_WORK:"Time in works",
    OUT_OF_TIME:"Out of hours",
    SWITCH_BOARD:"Call the operator",
    TEXT_OUT_OF_TIME:"Call center does not support outside business hours."
  },
  RATING: {
    BUTTON_RATING: "Rating",
    TASKER_RATE_ASKER_TITLE: "Rating customer",
    TASKER_RATE_ASKER_THANK: "Thank you for completing this task. How do you rate your customers?",
    TASKER_RATE_ASKER_TASK_NOT_FOUND: "Cannot rate this task now, Please skip this step",
    ASKER_ONE_STAR_LABEL: "Awful",
    ASKER_TWO_STAR_LABEL: "Bad",
    ASKER_THREE_STAR_LABEL: "Not Good",
    ASKER_FOUR_STAR_LABEL: "Good",
    ASKER_FIVE_STAR_LABEL: "Perfect",
    ASKER_WHAT_WENT_WRONG: "What do you want to comment?",
    ASKER_WHAT_COULD_BE_BETTER: "What would you expect better?",
    ASKER_WHAT_GOOD: "What is great about customer?",
    ASKER_RATING_REVIEW: "Your review",
    ASKER_THANK_YOU_NOTE: "Thank customer message",
    ASKER_RATING_BAD_1: "Privately negotiation.",
    ASKER_RATING_BAD_2: "Bad working environment",
    ASKER_RATING_BAD_3: "Over load",
    ASKER_RATING_BAD_4: "Cannot contact",
    ASKER_RATING_BAD_5: "Unfriendly",
    ASKER_RATING_OTHER: "Others",
    ASKER_RATING_GOOD_1: "Should not private negotiate with the cleaner",
    ASKER_RATING_GOOD_2: "Ensure occupational safety",
    ASKER_RATING_GOOD_3: "Please balance the volume and working time when booking a task on application.",
    ASKER_RATING_GOOD_4: "Keep in contact when close to the task start time",
    ASKER_RATING_GOOD_5: "Need more friendly",
    FRIENDLY: "Friendly",
    POLITE: "Polite",
    CHEERFUL: "Cheerful attitude",
    SUPPORT: "Willing support",
    TASK_SUCCESS: "Your task is finished.",
    NOT_RATING: "Not yet assessed",
    YOUR_REVIEW: "Your review",
    LENGTH_OF_TEXT: "{{t}}/140 words",
  },
  FILTER_NEW_TASK: {
    TITLE: "Filter by time",
    BY_CREATED_AT: "Just posted",
    BY_DATE: "Work to be done",
    BY_AREA: "Only show jobs in the registered area"
  },
  SHARE_SCREEN: {
    YOUR_REFERRAL_CODE:"Your referral code",
    TEXT_SHARE_SUCCESS:"How to share success",
    SHARE_WITH_YOUR_FRIEND:"Share with friends",
    FRIEND_DOW_APP:"Your friends become new collaborators:",
    BE_REWARDED:"Your friends become customers",
    FAQ: "FAQ",
    GIFTS_FOR_YOU_FOR_ME: "Gifts for you and for me",
    DESCRIPTION_BE_REWARDED: "At this point, just need to guide carefully and carefully read the FAQ section below for the correct instructions!",
    DESCRIPTION_FRIEND_DOW_APP: "Friends just click on the referral link, download the app and enter your referral code.",
    DESCRIPTION_SHARE_WITH_YOUR_FRIEND: "Tap the SHARE icon at the bottom to share your own referral code.",
    HOW_GET_REWARD: "How do my friends get rewards ?",
    DONE_GET_REWARD:"When you sign up for an account, remember to enter your referral code EXACTLY.",
    REFERRAL_REWARD: "Referral Bonus",
    TOTAL_BONUS: "Total bonus received",
    SEE_MORE: "See all",
    JOIN_DAY: "Join the day",
    ADD_TO_PROMOTION: "(Money will be added to your promotion account.)",
    SHARE_REFERRAL_CODE: "Share",
    TITLE_SHARE_REFERRAL_CODE: "Share",
    SUB_TITLE_SHARE_REFERRAL_CODE:"Share for",
    TEXT_Q1: "Q1",
    LABEL_COPY:"Copied",
    SHARE_WITH_ASKER: "Share for customer",
    SHARE_WITH_TASKER: "Share for Collaborator",
    DEEPLINK_TITLE: 'bTaskee Partner - Application for bTasker',
  },
  KIT_CHEMICALS:{
    TITLE: "Kits and chemicals",
    GET_KITS: "Kits",
    GET_CHEMICALS: "Chemicals",
    GET_KITS_AND_CHEMICALS_DETAIL: "Details of tools and chemicals",
    PRESS_BUY_KITS_AND_CHEMICALS: "See where to buy",
    KITS_AND_CHEMICALS_AMOUNT: "Amount",
    KITS_AND_CHEMICALS_PRICE: "Reference price",
    KITS_AND_CHEMICALS_MONEY: "Into money",
  },
  DELETE_ACCOUNT:{
    TITLE:"Delete account",
    TURN_BACK:"Come back",
    TEXT_AGREE_DELETE_ACCOUNT:"I agree to the terms and confirm the account deletion",
    DELETE_ACCOUNT_TITLE_REASON:"Reason",
    DELETE_ACCOUNT_SUB_REASON:"Why did you delete your account?",
    PLACEHOLDER_TEXT_INPUT:"Please enter the reason you want to delete the account.",
    TEXT_TITLE_DELETE:"You don't want to be bTasker anymore?",
    TEXT_INFO_ACCOUNT:"• Account information",
    TEXT_CONFIRM:"Please confirm that deleting your account will lose the following information:",
    TEXT_1:"• Deleted account you will not be able to recover.",
    TEXT_2:"• Also, you won't be able to use this account's email and phone number to create a new account.",
    TEXT_TRANS_INFO:"• Also, you won't be able to use this account's email and phone number to create a new account.",
    TEXT_TRANS_INFO_1:"Any information related to the transaction, saved address, payment method",
    TEXT_PRIVILEGES_BENEFIT:"• Offers and benefits",
    TEXT_PRIVILEGES_BENEFIT_1:"You will lose all affiliate offers, vouchers and benefits",
    TEXT_INFO_ACCOUNT_1:"Personal information related to your Tasker account",
    TEXT_INFO_ACCOUNT_2:"bTaskee will not be responsible for any loss of information, data or money after the account has been deleted.",
    DELETE_ACCOUNT_SUCCESS: "Your account has been permanently deleted from the bTaskee system. We are sorry for any inconvenience this may have caused you. We hope you will return soon.",
    ARE_YOU_SURE: "Are you sure you want to delete your account?",
  },
  BCARE: {
    TITLE: "Accident Support Policy",
    HEADER_TEXT: "All tasks on the bTaskee system are covered by accident insurance.",
    ROLE_LABEL: "Role",
    ROLE_TEXT: "As a Tasker on the bTaskee platform.",
    CONDITION_LABEL: "Conditions",
    CONDITION_TEXT: "Protection in case of accidents during transportation to the customer's house and while performing tasks on the bTaskee system:",
    CONDITION_TEXT_1: "• Deceased",
    CONDITION_TEXT_2: "• Total or partial permanent disability due to a work accident.",
    FEE_LABEL: "Protection fee",
    FEE_TEXT: "Tasker ",
    FEE_TEXT_1: "not required.",
    FEE_TEXT_2: " no insurance fees required.",
    BENEFIT_LABEL: "Benefits",
    BENEFIT_TEXT: "1. Collaborators will get:",
    BENEFIT_TEXT_1: "• Support costs if the accident leads to death",
    BENEFIT_TEXT_2: "• Support costs if the accident results in total or partial permanent disability",
    BENEFIT_TEXT_3: "• Financial support during hospitalization for treatment due to accidents.",
    BENEFIT_TEXT_4: "• Support for medical treatment costs due to accidents.",
    BENEFIT_TEXT_5: "2. bTaskee will proactively support the protection of your rights and benefits.",
    AMOUNT_LABEL: "Protection level",
    AMOUNT_TEXT: "Flexible maximum support amount ",
    AMOUNT_TEXT_1: "100,000,000 VND.",
    PROCEDURE_LABEL: "Support process",
    PROCEDURE_TEXT_1: "In case of an accident, please notify bTaskee via hotline 0901.300.501 - press 8.",
    PROCEDURE_TEXT_2: "Keep all medical examination and treatment-related documents and invoices and send them to the company no later than 30 days after discharge for insurance support within 30 days of reporting.",
    PROCEDURE_TEXT_3: "Get a VAT invoice when buying medicine outside the hospital worth over 200,000 VND.",
    REQUIRE_LABEL: "Request",
    REQUIRE_TEXT_1: "Invoice",
    REQUIRE_TEXT_2: "Medicine cost",
    REQUIRE_TEXT_3: "Medical examination certificate",
    NOTE: "Note:",
    NOTE_TEXT_1: "• Must be clear, reasonable with signatures and stamps from the hospital, pharmacy, and patient information.",
    NOTE_TEXT_2: "• Tasker need to provide all required documents to the company for consideration of support level.",
  },
  REFERRAL: {
    TITLE:"Enter the referral code to receive the gift.",
    YES:"Yes",
    NO:"No"
  },
  MODAL_ALERT: {
    TITLE_MODAL_TIP: "Congratulations",
    LABEL_MODAL_TIP: "You have just received a tip from the customer.",
    TEXT_MODAL_TIP: "Your skills, job quality, and service attitude deserve this reward from the customer. Keep striving and winning the hearts of more customers!",
    TITLE_MODAL_LEVEL_UP: "Level Up",
  },
  PROCEDURE_ACTIVE_ACCOUNT: {
    BUTTON_TEST_NOW: "Test now",
    TITLE_STEP_1: "Admission Test",
    TITLE_STEP_2: "Basic training",
    TITLE_STEP_3: "Active account",
    CONTENT_STEP_1: "Let's see how many skills and mindsets you have that are suitable for Maid!",
    CONTENT_STEP_2: "Please join the basic skills training program before you join the system!",
    CONTENT_STEP_3: "Congratulations on being a potential candidate of bTaskee and I'm sure in the next journey we will achieve many successes together.",
    NUMBER_OF_TIME_TEST: "Number of times taking the test",
    TEXT_SUCCESS: "Complete",
    TEST_FALSE: "You have exceeded the number of times specified. Please call the hotline for assistance.",
    MAKE_APPOINTMENT: "Make an appointment",
    ACTIVE_SUCCESS_TITLE: "Congratulations",
    ACTIVE_SUCCESS_CONTENT: "Notification after a successful appointment booking: Congratulations, you have completed the application submission process. Please note that we will have a direct appointment at the office. When you come, please bring the notarized photocopies and original documents, including: ID card - Household registration book/Residential information confirmation - Curriculum vitae - Good conduct certificate.",
    TITLE_MAKE_AN_APPOINTMENT: "Make an appointment",
    BUTTON_CHAT: "Chat",
    BUTTON_CALL: "Call now",
    MORNING_APPOINTMENT: "Morning - 09:00",
    AFTERNOON_APPOINTMENT: "Afternoon - 14:00",
    TITLE_SELECT_TIME: "Select time",
    LABEL_DATE: "Date",
    LABEL_TIME: "Time",
    NOTE_SELECT_TIME: "Note: Please arrive on time for your appointment as delays may affect HR support.",
    TITLE_SELECT_PLACE: "Select place",
    APPROVED_TITLE: "Approved",
    APPROVED_CONTENT: "Congratulations on completing the initial profile update. Please schedule an appointment to the nearest office for assistance with account activation.",
    PROCESSING_TITLE: "Processing",
    PROCESSING_CONTENT: "Your profile is being moderated. The system will notify you of the results as soon as possible.",
    BUTTON_UPDATE_PROFILE:"Update profile",
    REJECTED_TITLE: "Rejected",
  },
  SUPPLEMENT_INFO:{
    TITLE_ADD_SUPPLEMENT:"Upload Profile",
    NOTE_SUPPLEMENT_1:"• All documents must be notarized within the past 6 months.",
    NOTE_SUPPLEMENT_2:"• Please use the same type of document to take photos of the front and back.",
    NOTE_SUPPLEMENT_3:"• Please take a clear photo without cutting off any corners and avoiding any glare on important information on the documents.",
    TEXT_IDENTITY:"Identification card",
    TEXT_RESIDENCY:"Household booklet",
    TEXT_CURRICULUM:"Curriculum Vitae (CV)",
    TEXT_CERTIFICATE:"Certificate of conduct",
    TEXT_REQUIRE:"* require",
    TEXT_OPTIONAL:"* optional (you can upload later)",
    TEXT_SUPPLEMENT_NOTE:"Please take photos of additional documents for your profile",
    OPEN_PHOTO_GALLERY:"Open photo from gallery",
    OPEN_IMAGE_CAMERA:"Take image from camera",
    TEXT_NOTE_IDENTITY_1:"• Make sure the photo shooting environment has sufficient brightness.",
    TEXT_NOTE_IDENTITY_2:"• The main object is positioned at the center and fits within the framing area.",
    TAKE_A_PHOTO:"Take a photo",
    IMAGE_FRONT_SIDE:"Front side",
    IMAGE_BACK_SIDE:"Behind side",
    UPLOAD:"Upload",
    REUPLOAD:"Re-Upload",
    OPEN_CAMERA:"Open Camera",
    CHOOSE_PHOTO:"Choose a photo from",
    UPLOAD_IMAGE:"Upload image"
  },
  JOURNEY:{
    TITLE:"Journey",
    LEADER_BOARD_SCREEN:"Leaderboard",
    TITLE_MAIN_PRIZE: "Main prize:",
    TITLE_BONUS: "Bonus:",
    BUTTON_GET_REWARD: "Get reward now",
    TRAINING: "Training now",
    TASK: "Back to home",
    TITLE_ALERT: "Detail",
    TITLE_NUMBER_OF_TASK: "{{t}} task",
    TITLE_CURRENT_LEVEL: "My level",
    AVG_RATING_CONDITION: "The average service quality must be {{t}} or higher",
    MESSAGE_GET_REWARD_SUCCESS: "Get reward success!",
    TITLE_RECEIVED_REWARD: "Received:",
    BONUS_PRIZE: "Bonus:",
    LABEL_TIME_PASSED: "Time has passed",
    TITLE_PRIZE_BONUS_DETAIL: "Bonus detail",
    TITLE_PRIZE_BONUS: "Bonus",
    HOURS: "{{t}} hours",
    DAYS: "{{t}} days ",
    TRAINING_PASSED: "Complete",
    TRAINING_INCOMPLETE: "Incomplete",
    BONUS_NOT_RECEIVE: "Unclaimed Gift:",
    RECEIVE_AT_OFFICE: " (received at the office)",
    LABEL_PROCESSING: "Processing",
    LABEL_PASSED: "Passed",
    LABEL_LOCKED: "Lock",
    LABEL_MISSION: "Mission:",
    LEADER_BOARD_EMPTY: "List leader board is being updated!",
    TEXT_MODAL_ALERT_LEVEL_UP: "Congratulations on reaching",
    DESCRIPTION_MODAL_ALERT_LEVEL_UP: "Get rewarded for your efforts and try harder in the future!",
    TITLE_BUTTON_SEE_REWARD: "See rewards",
    TITLE_BUTTON_NEXT_REWARD: "Next rewards",
    LABEL_MODAL_ALERT_LEVEL_UP_REWARD: "Congratulations",
    TEXT_BONUS_PRIZE: "Bonus prize",
    TITLE_BUTTON_RANK_SCORE: "How to calculate the ranking score?",
    TITLE_CALCULATE_SCORE: "How to calculate points?",
    TITLE_HOW_TO_CALCULATE_SCORE: "How to calculate rating points",
    TEXT_CALCULATE_SCORE_1: "After completing 1 task, your score will be calculated based on the formula:",
    TEXT_CALCULATE_SCORE_2: "Extra Ranked Points = ",
    TEXT_CALCULATE_SCORE_3: " “Rate the quality of service” ",
    TEXT_CALCULATE_SCORE_4: " “Time to complete the task” ",
    TEXT_CALCULATE_SCORE_5: "For example, when completing **1 task** that requires execution from **12:00 to 16:00 (4 hours)** and is rated by a customer **5 stars**, you will have:",
    TEXT_CALCULATE_SCORE_6: "1 + 4 + 5 = 10 (point)",
    TITLE_RATING_SERVICE_QUALITY: "Service quality rating",
    TEXT_RATING_SERVICE_QUALITY_1: "From 1 to 5",
    TEXT_RATING_SERVICE_QUALITY_2: "When the Task is done, be sure to remind the customer to rate the service for additional rating points. Try to do well to get a 5 star rating, you will get 5 points.",
    TITLE_DURATION: "Time to complete the task",
    TEXT_DURATION_1: "Based on the required time of the task",
    TEXT_DURATION_2: "Note that the task completion time is fixed when the customer places the service, you cannot deliberately delay the completion of the work longer to earn more points.",
    TITLE_DETAIL_JOURNEY: "Journey detail",
    LEARN_MORE: "Learn more",
    DESCRIPTION_LEARN_MORE: "You can view all the information about the Bee Journey here.",
    COMING_SOON: "Coming soon",
    CURRENT_LEVEL: "Current level",
    TEXT_TRAINING_TO_RECEIVE_BONUS: "Complete training to get rewards",
  },
  MEMBER_INFO: {
    TITLE: "Member Infor",
    BPOINT_HISTORY: "bPoint History",
    VIEW: "View",
    SEE_NOW: "See now",
    LABEL_AVAILABLE_POINT: "Available bPoint",
    BROWSE_BREWARD: "Browse bRewards",
    RECOMMEND_FOR_YOU: "Recommend for you"
  },
  BREWARD: {
    RECOMMEND_FOR_YOU: "Recommend for you",
    FLASH_SALES: "Flash Sales",
    TOP_DEALS: "Top Deals",
    EXCLUSIVE_DEALS: "Exclusive Deals",
    VIEW_MORE: "View more",
    REDEM_NOW: "Redeem now",
    ALL: "All",
    TITLE_BPOINT_HISTORY_RECEIVED: "Received",
    TITLE_BPOINT_HISTORY_USED: "Used",
    EMPTY_TRANSACTION: "List transaction is empty!",
    TITLE_BUTTON_VIEW_MORE: "View more",
    EXPIRED_DATE:"Expired date",
    MY_REWARD: "My reward",
    RECENT_SEARCHES:"Recent searches",
    VOUCHERS_SEARCHES:"Vouchers searches",
    SEARCH:"Search for vouchers by voucher name: Discount ...",
    BUTTON_AGREE:"Agree",
    BUTTON_LATER:"Later",
    TITLE_CONTACT:"Contact",
    STORE:"Store List",
    BRANCH_STORE:"Currently {{t}} active",
    BRANCH_STORE_EMPTY:"The list of stores is being updated",
    DOW_IOS:"IOS",
    DOW_ANDROID:"Android",
    DOW:"Download the application",
    OUT_OF_STOCK: "Out of stock",
  },
  WEATHER:{
    TITLE: "Weather",
    BY_DATE: "By date",
    BY_HOUR: "By hour",
    PARTLY_CLOUDY: "Partly cloudy",
    MODERATE_RAIN: "Moderate rain",
    PATCHY_RAIN_POSSIBLE: "Patchy rain possible",
    SUNNY: "Sunny",
    CLEAR: "Clear",
    OVERCAST: "Overcast",
    CLOUDY: "Cloudy",
    LIGHT_RAIN: "Light rain",
    MODERATE_RAIN_AT_TIME: "Moderate rain at times",
    HEAVY_RAIN: "Heavy rain",
    HEAVY_RAIN_AT_TIME: "Heavy rain at times",
    MODERATE_OR_HEAVY_FREEZING_RAIN: "Moderate or heavy freezing rain",
    MODERATE_OR_HEAVY_RAIN_SHOWER: "Moderate or heavy rain shower",
    MODERATE_OR_HEAVY_RAIN_WITH_THUNDER: "Moderate or heavy rain with thunder",
    MIST: "Mist",
    FOG: "Fog",
    PATCHY_RAIN_NEARBY: "Patchy rain nearby",
    PATCHY_SNOW_NEARBY: "Patchy snow nearby",
    PATCHY_SLEET_NEARBY: "Patchy sleet nearby",
    PATCHY_FREEZING_DRIZZLE_NEARBY: "Patchy freezing drizzle nearby",
    THUNDERY_OUTBREAKS_IN_NEARBY: "Thundery outbreaks in nearby",
    FREEZING_FOG: "Freezing fog",
    PATCHY_LIGHT_DRIZZLE: "Patchy light drizzle",
    LIGHT_DRIZZLE: "Light drizzle",
    FREEZING_DRIZZLE: "Freezing drizzle",
  }
};
