export default {
  VALIDATE: {
    THIS_FIELD_IS_REQUIRED: "Informasi diperlukan",
    ERROR_PASSWORD_LENGTH: "Kata sandi 6-12 karakter",
    TYPE_INPUT_INVALID: "Data tidak berlaku",
  },
  ERROR: {
    ERROR_TRY_AGAIN: "Kegagalan tedeteksi, silahkan coba lagi! [{{t}}]",
    PHONE_NUMBER_SYNTAX_IS_INCORRECT: "No. Telepon salah",
    SEND_OTP_MESSAGE_ACCOUNT_NOT_EXIST: "No. Telepon tidak terdaftar.",
    ACTIVATION_ERROR_CODE: "Kode aktivasi salah, silahkan coba lagi",
    USER_NOT_FOUND: "Akun tidak terdaftar.",
    USER_LOCKED: "Akun anda sementara diblokir, hubungi kami untuk informasi selanjutnya.",
    INVALID_PASSWORD: "Kata sandi salah. Silahkan masuk lagi.",
    USER_TYPE_INCORRECT: "No. Telepon telah terdaftar di aplikasi bTaskee (aplikasi pelanggan). Silahkan kontak operator untuk bantuan selanjutnya.",
    USER_PERMISSION_DENIED: "Anda tidak dapat izin untuk mengakses",
    NETWORK_REQUEST_FAILED: "Tidak ada jaringan. Silahkan cek jaringan anda!",
    CANCEL_LIMITED: "Tidak bisa membatalkan pekerjaan ini. Anda telah melebihi batasan batalan dalam 7 hari!",
    ACTIVATION_CODE_INVALID: "Kode otentikasi salah. Silahkan coba lagi.",
    BUTTON_RELOAD: "Muat ulang",
  },
  PERMISSION: {
    ACCESS_PHOTOS_TITLE: "Permintaan izin akses foto",
    ACCESS_PHOTOS_CONTENT: "bTaskee meminta izin untuk akses foto Anda utnuk keperluan ini",
    WRITE_EXTERNAL_STORAGE_TITLE: "Permintaan izin penyimpanan",
    WRITE_EXTERNAL_STORAGE_CONTENT: "bTaskee butuh izin untuk setor handphone anda",
  },
  NOTIFICATION: {
    TAB_NOTIFICATION: "Notifikasi",
    NOTIFICATION_MESSAGE: "Apakah anda ingin menghilangkan notifikasi?",
    NOTIFICATION_MESSAGE_NOTHING: "Saat ini tidak ada notifikasi.",
    NOTIFICATION_DETAIL: "Notifikasi detail",
    TASK_NOTIFICATION: "Notifikasi",
    SYSTEM_NOTIFICATION: "System notifications",
    HAPPY_BIRTHDAY_TITLE: "Selamat Ulang Tahun",
    TITLE_HAVE_NEW_TASK: "Pekerjaan baru",
    READ_ALL_NOTIFICATION: "Ditandai sudah terbaca",
    TITLE_NOTIFICATION_WARNING:"Notifikasi mati",
    CONTENT_NOTIFICATION_WARNING:"Anda kemungkinan kelewatan pekerjaan yang menarik. Nyalakan notifikasi sekarang.",
    TURN_ON_NOTIFICATION: "Nyalakan notifikasi"
  },
  DIALOG: {
    BUTTON_CLOSE: "Tutup",
    BUTTON_ACCEPT: "Ok",
    TITLE_INFORMATION: "Notifikasi",
    TITLE_ERROR: "Maaf",
    BUTTON_SEE: "Lihat",
    BUTTON_DONE: "Selesai",
    BUTTON_SEE_AGAIN: "Lihat kembali",
    BUTTON_CALL_SUPPORT: "Hubungi bantuan",
    UPDATE_SUCCESS: "Pembaruan sukses",
    BUTTON_CONFIRM: "Konfirmasi",
    BUTTON_UPDATE: "Perbarui",
    BUTTON_NEXT: "Lanjut",
    CANCEL_TASK_SUCCESS: "Silahkan pilih pekerjaan lainnya!",
    ARE_YOU_SURE_TO_GO_BACK: "Are you sure you want to go back?",
    BUTTON_CANCEL: "Cancel",
    BUTTON_SKIP: "Skip",
    BUTTON_SEE_MORE: "See now"
  },
  LOGIN: {
    TITLE_LOGIN: "Masuk",
    USERNAME: "Nomor telpon",
    PASSWORD: "Kata Sandi",
    BUTTON_LOGIN: "Masuk",
    FORGOT_PASSWORD: "Lupa kata sandi?",
    SIGN_UP: "Daftar",
    VERSION: "Versi {{t}}",
    BUILD_NUMBER: "Kode {{t}}",
    TASKER_APP: "Untuk Tasker",
    MESSAGE_ACCOUNT_ACTIVE: 'Akun anda belum di aktivasi, silahkan aktivasi sekarang.',
    MESSAGE_ACCOUNT_TASKER_LOCK: "bTaskee regrets to restrict your account at this time. Please contact Call Center to continue accepting work.",
    MESSAGE_TOKEN_EXPIRED: "Akun Anda masuk ke perangkat lain. Ubah kata sandi jika masuk tidak diotorisasi. Silakan masuk kembali untuk menggunakan layanan kami!"
  },
  CHOOSE_LANGUAGE: {
    TITLE: "Pilih Bahasa",
    VI: "Vietnam",
    EN: "Bahasa Inggris",
    TH: "Thailand",
    ID: "Bahasa Indonesia",
  },
  COUNTRY: {
    INDONESIA: "Indonesian",
    VIETNAM: "Việt Nam",
    THAILAND: "Thailand",
  },
  REGISTER: {
    TITLE_REGISTER: "Registrasi",
    FULL_NAME: "Nama pertama dan nama akhir",
    FULL_NAME_PLACEHOLDER: "Nguyễn Văn A",
    ID_NUMBER: "No. KTP",
    ID_NUMBER_PLACEHOLDER: "123456789",
    PHONE_NUMBER: "No. Telepon",
    PHONE_NUMBER_PLACEHOLDER: "0987654321",
    PASSWORD: "Kata Sandi",
    PASSWORD_PLACEHOLDER: "Setidaknya 6 karakter",
    REFERRAL_CODE: "Kode Referral (Jika ada)",
    REFERRAL_CODE_PLACEHOLDER: "Kode Referral",
    BUTTON_REGISTER: "Tombol_Masuk",
    BUTTON_CHOOSE_WORKING_PLACES: "Pilih tempat bekerja",
    BUTTON_CONFIRM_OTP: "Aktivasi",
    BUTTON_RESEND_CODE: "Kirim ulang",
    REFERRAL_REWARD: "Masukkan kode referral dari Tasker untuk dapatkan berbagai tawaran menarik dari bTaskee.",
    BUTTON_NEXT: "Lanjutkan",
    BUTTON_RESEND_CODE_1: "Tidak menerima OTP?",
    TEXT_OTP:"OTP akan kadaluarsa dalam"
  },
  REGISTER_CHOOSE_WORKING_PLACE_CITY: {
    TITLE: "Pilih Kota",
    CHOOSE_CITY: "Di kota mana anda bekerja ?",
    NOTE_CHOOSE_SERVICE: "Mohon perhatikan, layanan bervariasi tergantung dengan kota dan anda hanya bisa memilih satu kota untuk bekerja",
  },
  REGISTER_CHOOSE_WORKING_PLACE_DISTRICT: {
    TITLE: "Pilih Wilayah",
    LIMIT_DISTRICT: "Pilih Maksimum 3 Wilayah",
    CHOOSE_DISTRICT: "Anda ingin kerja di area mana ?",
  },
  REGISTER_CHOOSE_SERVICES: {
    TITLE: "Pilih layanan",
    BUTTON_REGISTER: "Tombol_Masuk",
    CHOOSE_SERVICES: "Layanan apa yang ingin anda kerjakan?",
  },
  CONFIRM_CHOOSE_WORKING_PLACE_AND_SERVICES: {
    CONFIRM: "Konfirmasi",
    CONFIRM_NOTE: "Silahkan cek kembali informasi yang anda daftarkan. Saat anda sudah konfirmasi bahwa informasinya benar, anda bisa memulai tes masuk.",
    SERVICES: "Layanan",
    DISTRICTS: "Wilayah",
    SAVE_SUCCESS: "Selamat, anda telah sukses memperbarui",
  },
  FORGOT_PASSWORD: {
    TITLE: "Lupa kata sandi",
    DESCRIPTION: "Masukkan nomor telepon anda untuk mengatur ulang kata sandi",
    RESEND_PASSWORD: "Kirim ulang kata sandi",
  },
  SET_PASSWORD: {
    TITLE: "Atur ulang kata sandi",
    DESCRIPTION: "Kata sandi ini akan digunakan untuk masuk ke aplikasi berikutnya.",
    NEW_PASSWORD: "Kata sandi baru",
    SAVE: "Simpan",
    SUCCESS_SET_PASSWORD: "Ganti kata sandi sukses.",
    WELCOME: "Selamat datang di bTaskee",
  },
  CHANGE_PASSWORD: {
    TITLE: "Mengatur ulang kata sandi",
    DESCRIPTION: "Kata sandi ini akan menjadi kata sandi untuk anda masuk ke aplikasi selanjutnya.",
    INPUT_OLD_PASSWORD: "Masukkan kata sandi yang lama",
    OLD_PASSWORD: "Kata sandi lama",
    INPUT_NEW_PASSWORD: "Masukkan kata sandi baru ",
    NEW_PASSWORD: "Kata sandi baru",
    ACCESS: "Akses",
    SUCCESS_CHANGE_PASSWORD: "Ganti kata sandi sukses",
    CHANGE_PASSWORD: "Mengatur ulang kata sandi",
    WELCOME: "Selamat datang di bTaskee",
  },
  CHOOSE_COUNTRY: {
    TITLE_CHOOSE_COUNTRY: "Pilih Negara",
    BUTTON_NEXT: "Lanjutkan",
    TITLE: "Dimana anda tinggal?",
  },
  OTP: {
    TITLE: "Aktivasi akun",
    HELLO: "Halo",
    INSTRUCTION_OTP: "KODE AKTIVASI telah dikirim ke HP {{t}}. Silahkan cek SMS dan masukkan KODE di kolom berikut.",
    ACTIVATION_CODE: "Aktivasi kode",
    RESEND_CODE_ERROR: "Anda telah menekan kirim terlalu banyak. Silahkan coba lagi.",
  },
  TASK_DETAIL: {
    TITLE: "Detail pekerjaan",
    DESCRIPTION_FOR_PROMOTION: "Tambah ke akun promosi",
    PAYMENT_METHOD_LABEL: "Metode Pembayaran:",
    TYPE_HOUSE_LABEL: "Tipe rumah: ",
    NOTE_LABEL: "Catatan: ",
    BUTTON_SEE_FULL_NOTE: "Lihat Semua",
    BUTTON_SLIDE_TO_CONFIRM: "Geser untuk mendapat tugas",
    BUTTON_FAQ: "Pertanyaan",
    STATUS_WAITING_CONFIRM: "Menunggu pertanyaan konfirmasi",
    WITHDRAW_TASK: "Mundur dari pekerjaan ini",
    BEGIN_WORK: "Mulai bekerja",
    TASK_IS_WORKING: "Pekerjaan dalam proses",
    DURATION_NOTE: "Bekerja untuk {{duration}} jam",
    COUNT_DOWN_TIME_START_JOB: "Pekerjaan akan mulai pada {{time}}",
    COUNT_DOWN_TIME_START_JOB_TASK_ITEM: "Mulai setelah:",
    COUNT_DOWN_TIME_FINISH_JOB: "Pekerjaan akan selesai pada {{time}}",
    FINISH: "Selesai",
    DURATION_HOUSE: "{{duration}} kamar : {{area}}",
    APARTMENT: "Apartemen/Kondominium",
    HOME: "Rumah",
    VILLA: "Vila",
    HOTEL: "Hotel",
    DOG: "Anjing",
    CAT: "Kucing",
    REQUIREMENTS_COOKING: "Masak",
    REQUIREMENTS_IRON: "Setrika",
    REQUIREMENTS_2_SHOTS_VACCINE: "Memperoleh 2 dosis vaksin",
    REQUIREMENTS_NEGATIVE_TEST_COVID: "Hasil COVID-19 test negative dalam 7 hari",
    REQUIREMENTS_BRING_TO_TOOLS: "Termasuk perlatan berih-bersih",
    CALL_WITH_PHONE_NUMBER: "Hubungi menggunakan nomor telepon",
    CALL_WITH_BTASKEE_APP: "Hubungi menggunakan aplikasi bTaskee",
    ACCEPTED_SUCCESS: "Anda berhasil terima tugas ini ",
    ACCEPTED_TASK_WAITING_SUCCESS: "Berhasil mendapatkan tugas. Menunggu pelanggan untuk konfirmasi",
    PAYMENT_METHOD_CASH: "Uang tunai",
    PAYMENT_METHOD_TRANSFER: "Bank transfer",
    MY_TASK_EMPTY: "Anda belum mendapatkan tugas hingga tanggal yang tertera.",
    NEW_TASK_EMPTY: "Tidak ada tugas baru",
    BUTTON_TRANSLATE_NOTE: "Terjemahan",
    NOTES_TITLE: "Catatan",
    BUTTON_DONE: "Selesai",
    NUMBER_OF_TASK: "{{number}} Pekerjaan",
    BUTTON_GO_TO_DATE: "Hari ini",
    NUMBER_ACCEPTED_TASK: "Taskers accepted this task: ",
    TITLE_CANCEL_TASK: "Batal",
    BUTTON_CANCEL: "Batalkan",
    BUTTON_NO: "Kembali",
    CONFIRM_CANCEL_TEXT: "Apakah anda yakin untuk mundur dari tugas ini?",
    CANCEL_TASK_REASON_NEARBY_TASK_PLACE: "Sudah sampai, tidak bisa hubungi pelanggan (Harus nyalakan lokasi anda)",
    CANCEL_TASK_REASON_SO_FAR_AWAY: "Terima pekerjaan terlalu jauh.",
    CANCEL_TASK_REASON_WRONG_DATE: "Terima kerjaan di tanggal yang salah.",
    CANCEL_TASK_OTHER_REASON: "Lainnya.",
    CANCEL_TASK_REASON_TEXT: "Silahkan pilih salah satu alasan kenapa anda menolak tugas ini",
    CANCEL_REASON_IS: "Alasan pembatalan adalah:",
    CANCEL_FREE: "Bayaran",
    NOTE_CANCEL_TASK: "Denda akan di ambil dari akun anda jika anda batalkan pekerjaan ini.",
    PLACEHOLDER_TEXT_INPUT: "Silahkan masukkan alasan kenapa anda menolak tugas ini (Informasi yang diperlukan)",
    TITLE_MODAL_CALL: "Hubungi pelanggan",
    PREMIUM_TASK: "Layanan Premium",
    TASK_FROM_SUBSCRIPTION: "Langganan Perbulan",
    POP_UP_DRAW_TASK_TXT: "Kredibilitas anda akan dikurangi. Apakah anda yakin untuk mundur dari tugas ini?",
    CANCELED: "Batalkan",
    DONE: "Done",
    CANCELED_BY_TASKER: "Saya batalkan",
    CANCELED_BY_ASKER: "Dibatalkan oleh pelanggan",
    CANCELED_REASON: "Alasan",
    NUMBER_OF_DINER: "Jumlah orang yang akan makan: ",
    NUMBER_OF_DISH: "Jumlah masakan",
    TASTE: "Rasa: ",
    EATING_TIME: "Jam makan: ",
    BAC: "Utara",
    TRUNG: "Pusat",
    NAM: "Barat",
    FRUIT_DESERT: "Buah",
    GO_MARKET: "Asisten rumah tangga",
    DISH_WAITING: "Ditunggu",
    CALL_CUSTOMER_TO_UPDATE_DISH: "Daftar masakan telah diperbarui. Setelah dapat tugas, silahkan hubungi pelanggan untuk mendapat informasi terbaru mengenai daftar makanan.",
    BUDGET_TO_MARKET: "Anggaran belanja: ",
    AIR_CONDITIONER_NUMBER: "{{t}} unit",
    ANY_CAPACITY: "Semua ruangan AC",
    CAPACITY_LESS_THAN: "Kapasitas lebih sedikit dari {{t}}HP",
    CAPACITY_GREATER_THAN: "Kapasitas lebih banyak dari {{t}} HP",
    CAPACITY_FROM_TO: "Kapasitas mulai dari {{t1}} HP hingga {t2} HP",
    CAPACITY_LESS_THAN_BTU: "Kapasitas lebih sedikit dari {{t}}BTU",
    CAPACITY_GREATER_THAN_BTU: "Kapasitas lebih dari {{t}} BTU",
    CAPACITY_FROM_TO_BTU: "Kapasitas dari {{t1}} BTU hingga {{t2}} BTU",
    TYPE_AC: "Tipe AC",
    QTY: "Jumlah",
    TASK_AIR_CONDITIONER: "Tugas",
    HOSTEL_NAME: "Nama lokasi: ",
    TOTAL_AREA: "Luas bangunan: {{t}}m²",
    IMAGE_TITLE: "Gambar",
    NAME_ROOM: "Nama ruangan: {{t}}",
    AREA_ROOM: "Areal: {{t}}m²",
    NOTE_ROOM: "Catatan: {{t}}",
    HOSTEL_DETAIL: "Informasi ruangan",
    NUMBER_TASKER_ACCEPTED: "Tasker yang di terima: ",
    LIST_OF_TASK: "Daftar pekerjaan",
    BUTTON_SEE_LIST: "Detail",
    TITLE_LIST_CLEANING_TOOL: "Daftar peralatan",
    OVERVIEW: "Umum",
    NUMBER_TOTAL_SOFA: "Jumlah furnitur: ",
    SOFA_TYPE: "Tipe: ",
    MATTRESS: "Kasur",
    DRY_CLEANING: "Cucian kering",
    WASHING: "Cucian basah",
    CURTAIN: "Tirai",
    CARPET: "Karpet",
    BED: "Kasur",
    AREA_DISINFECTION: "Areal: ",
    DISINFECTION_AREA_FROM_TO: "{{t1}}m² - {{t2}}m²",
    DISINFECTION_AREA_CUSTOM: "{{t}}m²",
    DISINFECTION_PROCEDURE: "Proses semport disinfektan",
    DISINFECTION_PROCEDURE_CONTENT_TITLE: "Lanjutkan untuk semprot disinfektan",
    DISINFECTION_PROCEDURE_CONTENT_1: "1. Siapkan cairan untuk semprot disinfektan.",
    DISINFECTION_PROCEDURE_CONTENT_2: "2. Matikan sistem ventilasi. Matikan AC dan matikan kipas angin..",
    DISINFECTION_PROCEDURE_CONTENT_3: "3. Ruang keluarga: atap, lantai, dinding, kabinet, pintu, meja...",
    DISINFECTION_PROCEDURE_CONTENT_4: "4. Kamar tidur: atap, lantai, dinding, kabinet, di bawah kasur",
    DISINFECTION_PROCEDURE_CONTENT_5: "5. Dapur: atap, lantai, dinding, meja makan, kursi, rak",
    DISINFECTION_PROCEDURE_CONTENT_6: "6. Kamar mandi: atap, lantai, dinding, wastafel",
    DISINFECTION_PROCEDURE_CONTENT_7: "7. Periksa kerjaan lagi setelah sudah selesai.",
    SHOPPING_TIME_LABEL: "Waktu belanja: ",
    DURATION: "{{t}} jam",
    ESTIMATED_PURCHASE_AMOUNT: "Perkkiraan jumlah pembelian pelanggan: ",
    SHOPPING_LIST: "Daftar belanja",
    AMOUNT_CHILD_LABEL: "Jumlah anak",
    AGE_OF_CHILD: "Usia",
    NUMBER_OF_CHILD: "Anak",
    BUTTON_CONFIRM: "Konfirmasi",
    TET_BOOKING: "Pemesanan pekerjaan saat Tet",
    YOUR_WORK: "Tugas anda",
    YOU_ARE_LEADER: "Anda adalah pemimpin tugas ini",
    YOU_ARE_MEMBER: "Anda adalah anggota tugas ini",
    WORK_ACCORDING_TO_ASSIGNMENT: "- Kerja sesuai yang ditugaskan atasan.",
    PLEASE_CANCEL_TASK_BEFORE_A_TIME: "- Jika anda ingin membatalkan pekerjaan ini, silahkan hubungi operator sebelum pekerjaan dimulai {{t}} jam untuk bantuan",
    RECEIVE_CASH_FROM_LEADER: "Saat pekerjaan selesai, silahkan hubungi ketua untuk dapatkan upah.",
    OTHER_PAYMENT: "- Saat pekerjaan selesai, uang akan di transfer ke akun utama setiap anggota.",
    RECEIVE_CASH: "- Saat pekerjaan selesai, dapatkan uang dari palanggan dan bagi uang ke seluruh anggota sesuai informasi dibawah.",
    DIVIDE_WORK: "- Bagi pekerjaan untuk anda dan rekan anda.",
    NEED_TO_CONTACT_PARTNER: "- Ketua akan hubungi anggota sebelum pekerjaan dimulai. Jika ada anggota yang tidak bisa datang, silahkan kontak operator untuk bantuan.",
    TITLE_TASK_WAITING: "Tugas yang ditunggu",
    BUTTON_CHAT: "Percakapan",
    BUTTON_CALL: "Telepon",
    MONEY_GET_MORE: 'Tambahan pemasukan:',
    TASK_WAS_CONFIRMED: "Pekerjaan ini telah diterima.",
    SEE_MORE: "Lihat lainnya",
    CANCEL_TASK_TASKER_SO_FAR_AWAY_TASK_PLACE: 'Anda tidak bisa membatalkan layanan dengan alasan ini. Sistem hanya menerima alasan pembatalan jika anda dekat dari tempat kerja.',
    CANCEL_TASK_LOCATION_NOT_FOUND_TEXT: 'Kami tidak dapat mendeteksi lokasi anda. Silahkan beri akses dan coba ulang aplikasi untuk batalkan layanan.',
    NEW_ASKER_NOTE: 'Pelanggan ini menggunakan layanan baru, anda harus hubungi pelanggan sebelum tiba di rumah pelanggan.',
    TITLE_LIST_OF_TOOL_FOR_TASKER: "Daftar peralatan bersih-bersih yang harus dibawa",
    TITLE_ALERT_FAQ: "Peringatan",
    MESSAGE_ALERT_FAQ_WAITING: "Jika anda membatalkan pekerjaan ini, anda tidak akan dikenakan biaya.",
    MESSAGE_ALERT_FAQ_CONFIRMED: "Jika anda membatalkan pekerjaan ini, biaya pembatalan akan dikenakan sesuai ketentuan.",
    ACCIDENT_INSURANCE: 'Pekerjaan di support bCare',
    DESCRIPTION_CANCEL_TASK:"Maaf, pelanggan telah memilih Tasker lainnya. Silahkan pilih pekerjaan lainnya.",
    TODAY: "Hari ini",
    TOMORROW: "Besok",
    QR_CODE:"Identifikasi QR anda",
    COST_INCURRED: "Untuk meningkatkan",
    DESCRIPTION_FOR_PROMOTION_LEADER: "Akan dibagi rata dan dimasukkan ke akun promosi pengguna.",
    MONEY_GET_MORE_MEMBER: "Dapatkan lebih dari atasan",
    PAYMENT_MOTHOD_BANKER: "Transfer bank",
    PAYMENT_MOTHOD_CASH: "Uang tunai",
    PAYMENT_MOTHOD_PROMOTION: "Promosi",
    MONEY_GET_MORE_LEADER: "Dapatkan lebih dari anda (Akan dibagi rata ke anggota) ",
    SOFA_CLEANING_TYPE_MORE: "Lebih dari 6 kursi",
    CURTAIN_CHOOSE_SERVICE_ON_SITE: "Layanan di tempat",
    CURTAIN_CHOOSE_SERVICE_OFF_SITE: "Layanan di luar lokasi",
    WORKED_FOR_ASKER: "Used to work for this customer",
    ASKER_OFTEN_USE_SERVICE: "Customers use the service regularly",
    TIP: "Tip:",
    CANCEL_FEE: "Cancellation fee is ",
    MORNING: "Morning",
    AFTERNOON: "Afternoon",
    EVENING: "Evening",
    VACUUMING_OFFICE_CARPETS: "Vacuuming office carpets",
    CLEANING_GLASSES: "Cleaning glasses",
    WM_TYPE: "W/M Type",
    WM_SERVICES: "Services",
    NUMBER_OF_WM: "Number of washing-machine",
    CALL_WITH_MEMBER: "Contact with team member",
    CALL_WITH_LEADER: "Contact with team leader",
  },
  HOME: {
    TAB_HOME: "Menu utama",
    TAB_BENEFIT: "Kelebihan",
    TAB_ACCOUNT: "Akun",
    BTASKEE: "bTaskee",
    TAB_MY_TASK: "Diperoleh",
    TAB_NEW_TASK: "Tugas Baru",
    TAB_NOTIFICATION: "Pesan masuk",
    NET_DISCONNECTED: "No connection. Please check the network again!",
    NET_ONLINE: "Connected!",
  },
  NOTIFICATION_CHAT: {
    TAB_TITLE: "Percakapan",
    NOTHING: "Tidak ada pesan baru.",
  },
  NOTIFICATION_SYSTEM: {
    TAB_TITLE: "Notifikasi",
    INBOX: "Pesan masuk",
  },
  TAB_BENEFIT: {
    TRAINING_PROGRAM: "Program Pelatihan",
    MONTHLY_REWARD: "Ganjaran Bulanan",
    BREWARD: "bReward",
    COMMUNITY: "Komunitas",
    BCARE: "bCare",
    INSURANCE: "Accident support policy",
    LEVEL_MONTHLY_REWARD: "Perlu bekerja {{t}}jam untuk mendapatkan bonus bulan depan",
    MAX_LEVEL: "Congratulations on reaching the highest bonus level this month.",
    HOURS_OF_AWARDS: "{{t}} jam ",
    PROMOTION: "Promosi",
    BREWARD_DETAIL: "Detail bReward",
    LABEL_REWARD_INFO: "Informasi ganjaran",
    LABEL_CONDITION: "Kondisi",
    BUTTON_REDEEM: "Tukar",
    NUMBER_POINT: "bPoint",
    TITLE_ALERT_CONFIRM_REDEEM: "Konfirmasi penukaran",
    CONTEXT_ALERT_CONFIRM_REDEEM: "Tukar kupon ini",
    BUTTON_CONFIRM: "Konfirmasi",
    BUTTON_LATER: "Nanti",
    FREE: "Gratis",
    REDEEM_SUCCESS: "Penukaran sukses",
    NEW_GIFT: "Baru",
    USED_GIFT: "Dipakai",
    LIST_INCENTIVE_EMPTY: "Belum ada ganjaran.",
    MY_GIFT: "Hadiah saya",
    EXPIRED_ON: "Kadaluarsa pada:",
    EXPIRED: "Kadaluarsa",
    USED: "Telah dipakai",
    DETAIL_REWARD_EMPTY: "Promosi tidak sedia",
    LABEL_SAVE_SUCCESS: "Sukses",
    MONTHLY_REWARD_DETAIL: "Detail hadiah",
    MORE_HOURS:"Butuh kerja lebih",
    MORE_REWARD:"Hadiah selanjutnya",
    TIME_WORK_IN_MONTH:"Jam kerja bulan ini:",
    REWARD_WORD_IN_MONTH:"Hadiah yang didapatkan bulan ini:",
    HOURS:"Jam",
    DAY_LEFT:"Tanggal tersisa:",
    DAY:"Hari tersisa",
    NEXT_STEP:"Langkah selanjutnya:",
    VIEW_DETAIL:"Lihat detail",
    DETAIL_REWARD:"Detail hadiah",
    MONEY: "{{currency}}{{cost}}",
    NEXT_REWARD: "Hadiah selanjutnya",
    TRAINING: "Pelatihan",
    COMMUNITY_CONTENT: "Tukarkan dan bagikan pengalaman dengan bTasker di negara ini.",
    BREWARD_CONTENT: "Untuk mendapatkan 'Banyak hadiah' saat mendapatkan bPoints untuk menukar bRewards.",
    TRAINING_CONTENT: "Mari promosikan kualitas tinggi bTaskee melalui program pelatihan!",
    BCARE_CONTENT: "Tasker tidak bisa berurusan dengan risiko ini, mari bantu tasker bersama bCare.",
    PREMIUM_CONTENT: "Mari bersemangat untuk menjadi Tasker premium!",
    EMPTY_DATA: "Silahkan kembali setelah mengaktivasi akun anda untuk mendapat hadiah spesial untuk bTasker.",
    SEARCH: "Search",
    SEARCH_VOUCHER: "Search voucher",
    ACCOUNT_LOCK: "Locked"
  },
  TAB_ACCOUNT: {
    PROFILE: "Profil",
    FINANCE: "Keuangan",
    WEEKLY_REPORT: "Laporan mingguan",
    HISTORY_INCOME: "Sejarah Pemasukan",
    INCOME: "Penghasilan",
    SERVICES: "Layanan",
    DISTRICTS: "Wilayah",
    LEVEL: "Tingkatan",
    PREMIUM: "Premium",
    TITLE_QA_CODE: "Identifikasi QA anda",
    YOUR_REFERRAL_CODE: "Kode referral",
    COPY: "Salin",
    LABEL_COPY: "Tersalin",
    SEE_INFORMATION: "Lihat informasi",
    LOGOUT: "Keluar",
    LOGOUT_CONFIRM: "Apakah anda yakin ingin keluar?",
    LEVEL_1: "Amatiran",
    LEVEL_2: "Profesional",
    HOLDING_ACCOUNT: "Temporary job payment: ",
    MAIN_ACCOUNT: "Akun utama",
    PROMOTION_ACCOUNT: "Akun promosit: ",
    INCOME_THIS_WEEK: "Masukan anda minggu ini",
    COMPLETED_TASK: "Tugas yang diselesaikan",
    INCOME_TOTAL: "Jumlah pemasukan",
    INCOME_IN_MONTH: "Masukan anda bulan ini",
    TOPUP: "Isi ulang",
    WITHDRAW: "Mundur",
    AMOUNT_WITHDRAW: "Pending withdrawal",
    AMOUNT_WITHDRAW_NOTE: "Your payment is being processed by the system.",
    TRANSACTION_HISTORY: "Riwayat transaksi",
    AMOUNT: "Jumlah",
    BALANCE: "Saldo yang tersedia",
    WITHDRAW_NOTE: "Catatan: Anda harus memiliki setidaknya {{amount}} {{currency}} yang tersisa di akun anda untuk melanjutkan pekerjaan.",
    NEXT: "Lanjut",
    CONFIRMATION: "Konfirmasi",
    CONFIRMATION_WITHDRAW: "Apakah anda yakin untuk ambil uang dari akun anda?",
    BANK_ACCOUNT: "Akun",
    FMAIN_ACCOUNT_NOTE: "Saldo akun anda menunjukkan nominal uang yang bisa anda gunakan untuk menerima pekerjaan atau ambil uang jika memenuhi ketentuan.",
    PROMOTION_ACCOUNT_NOTE: "Akun ini mengandung jumlah bonus dan bantuan yang diperoleh Tasker, demikian juga pekerjaan yang menggunakan kode promo dari pelanggan. Akun ini hanya digunakan untuk menerima pekerjaan.",
    ON_HOLD_ACCOUNT: "Upah pekerjaan sementara",
    ON_HOLD_ACCOUNT_NOTE: "The estimated job fee is the amount of money held when you are accepting a task. If you complete the task, this amount will be deducted from your promotion account. When the promotion account is depleted, it will be deducted from your main account.",
    PAYOUT_NAME: "Permintaan mundur",
    PAYOUT_WAIT: "Diproses",
    PAYOUT_PAID: "Dibayar",
    PAYOUT_CANCELED: "Batalkan",
    PAYOUT_REJECTED:  "Ditolak",
    PAYOUT_SUCCESS: "Permintaan sukses",
    MONTH: "Bulan",
    WEEK: "Minggu",
    STAR: "Bintang",
    BELOW: "Dibawah rata-rata",
    TASK: "Pekerjaan",
    INCREASE_TASK: "Tingkatkan {{task}} pekerjaan dibandingkan minggu lalu",
    DECREASE_TASK: "Pengurangan {{task}} pekerjaan dibandingkan minggu lalu",
    GOOD_REVIEW: "Ulasan bagus",
    BAD_REVIEW: "Perlu ditingkatkan",
    TASK_HISTORY: "Riwayat Pekerjaan",
    INFORMATION: "Informasi",
    EMPTY_TASK_IN_MONTH: "Tidak ada pekerjaan bulan ini",
    EMPTY_TRANSACTION_IN_MONTH: "Tidak ada penawaran bulan ini",
    LIST_OF_EMPLOYEE: "Daftar pekerja",
    REVIEW: "Evaluasi",
    ERROR_ON_HOLD_ACCOUNT_WHEN_WITHDRAW: "Anda memiliki 1 permintaan penarikan yang tertunda",
    TRANSACTION: "Transaksi",
    PAYOUT: "Permintaan",
    LABEL_TRANSACTION_TAB: "Baru-baru ini",
    EMPTY_TRANSACTION: "Anda belum memiliki transaksi",
    EMPTY_PAYOUT: "Anda tidak memiliki permintaan",
    TITLE_CHECK_NOTIFICATION: "Tes notifikasi",
    BUTTON_CHECK_NOTIFICATION: "Kirim notifikasi",
    TITLE_TEST_NOTIFICATION: 'Notifikasi bekerja dengan baik',
    INFO_TEST_NOTIFICATION: 'Aplikasi akan mati dengan otomatis untuk melihat notifikasi. Apakah anda ingin melanjutkan?',
    TITLE_CARD_SHARE: "Bagikan",
    CONTENT_CARD_SHARE: "Bagikan aplikasi untuk mendapat hadiah",
    BUTTON_VIEW_MORE: "Lihat lainnya",
    TEXT_QR: "Silahkan tunjukkan kode QR anda agar pelanggan bisa mengidentifikasi.",
    LABEL_DELETE_ACCOUNT: "Hapus akun",
    TEXT_DELETE_ACCOUNT: "Apakah anda yakin?",
    TITLE_RESTART_APP: "Mulai ulang aplikasi",
    BUTTON_RESTART_APP: "Mulai sekarang",
    TEXT_RESTAR_APP: "Apakah anda yakin ingin mulai ulang aplikasi?",
    NUMBER_ACCEPT_TASK: "Saat ini memiliki {{numberTasks}} pekerjaan",
    NUMBER_OF_POINT_LABEL: "Preferential point",
    NUMBER_OF_POINT: "{{t}} points"
  },
  CHAT: {
    TRANSLATING: "Terjemahi...",
    TITLE: "Percakapan",
    PREPARED_MESSAGE_THANK: "Terima kasih.",
    PREPARED_MESSAGE_WAIT_ASKER: "Saya di jalan. Mohon ditunggu sebentar. Terima kasih!",
    GPS_NOT_FOUND: "Lokasi tidak bisa ditemukan!",
    TYPE_A_MESSAGE: "Tulis pesan",
    SERVICE_REQUEST_GPS: "Harapkan aktifkan GPS untuk menggunakan layanan ini!",
    PT1_MAP_POPUP_PERMISSION_REQUEST_GPS_CLOSE: "Tutup",
    OPEN_SETTINGS: "Buka pengaturan",
    MODAL_CONFIRM_SHARE_LOCATION_TITLE: "Apakah anda ingin membagi lokasi anda sekarang?",
    PREPARED_MESSAGE_CONFIRMATION: "Halo! Saya terima pekerjaan anda. Saya akan datang tepat waktu.",
    PREPARED_MESSAGE_REQUIRE_ADDRESS_EXACTLY: "Mohon kirim alamat yang akurat. Terima kasih!",
    PREPARED_MESSAGE_COMING: "Saya akan datang untuk melakukan pekerjaan anda. Mohon hubungi saya!",
    PREPARED_MESSAGE_WAIT_20_MINUTES: "Halo, saya sudah datang ke lokasi anda tetapi tidak bisa hubungi anda. Saya akan tunggu 20 menit, dan jika saya tetap tidak bisa hubungi anda saya akan batali pekerjaan ini.",
    PREPARED_MESSAGE_WAITED_20_MINUTES: "Saya telah menunggu 20 menit dan tidak bisa hubungi anda. Pekerjaan ini akan dibatalkan.",
    PREPARED_MESSAGE_AT_RECEPTION: "Saya menunggu di lobi resepsionis. Mohon datang dan jemput saya.",
    LABEL_CHAT_WITH_BTASKEE: "Percakapan dengan bTaskee"
  },
  TRAINING_INPUT: {
    TITLE: "Tes",
    LOADING_TITLE: "Mendapatkan Informasi",
    INSTRUCTION_PASS_TEST: "Catatan: Hasil tes anda harus 80% untuk lulus, mohon baca dengan seksama sebelum menjawab.",
    ERROR: "Gagal mendapatkan informasi. Silahkan coba lagi!",
    START: "Mulai",
    RELOAD: "Silahkan coba lagi!",
    FINISH: "Kirim",
    ACCEPT_TEST_CONFIRMATION: "Apakah anda membaca dengan seksama dan ingin mengambil tes?",
    FINISH_TEST_CONFIRMATION: "Apakah anda yakin?",
    FAILD: "Tes gagal. Silahkan hubungi hotline untuk bantuan.",
    RESULT_TEST_FAILD: "Anda belum lolos tes. Anda memiliki {{t}} kali lagi untuk mengambil test. Hati-hati dan kerjakan yang terbaik!",
    RESULT_TEST_FAILD_LIMITED: "Anda tidak lolos tes. Silahkan hubungi operator until detail lebih lanjut!",
    SEE_RESULT: "Hasil",
    GRADING_TEST: "Mengecek hasil...Mohon ditunggu!",
    QUIT_TEST: "Keluar tes",
    TRAINING_TASKER_PASS_TITLE: "Selamat datang di bTaskee",
    PREPARE_PROFILE: "Silahkan siapkan dokumen berikut:",
    UNVERIFIED_TASKER_PROFILE_1: "01 Riwayat Pekerjaan:",
    UNVERIFIED_TASKER_PROFILE_2: "02 Fotokopi KTP:",
    UNVERIFIED_TASKER_PROFILE_3: "01 Fotokopi Akta Keluarga (Foto):",
    UNVERIFIED_TASKER_PROFILE_4: "01 Konfirmasi perilaku (Disahkan):",
    NOTE_FOR_UNVERIFIED_TASKER_PROFILE: "Disahkan, tidak lebih dari 6 bulan",
    APPLY_YOUR_PROFILE_AT_COMPANY_NOTE: "Kirim semua dokumen secara langsung di salah satu kantor bTaskee di Ho Chi Minh dimana anda daftar.",
    TIME_TO_APPLY: "Waktu untuk kirim dokumen",
    MORNING_TO_APPLY: "Pagi:",
    AFTERNOON_TO_APPLY: "Siang:",
    TIME_MORNING: "09:00 AM",
    TIME_AFTERNOON: "14:00 PM",
    ARRIVE_APPLY_LATE_NOTE: "Jika anda telat, anda harus mengatur jadwal bertemu di lain hari.",
    UNVERIFIED_TASKER_SUBMITION_ADDRRESS: "Alamat untuk kirim dokumen:",
    CALL_SUPPORT_FOR_MORE_DETAIL: "Untuk informasi lebih lanjut silahkan hubungi",
    PHONE: "No. Telepon: {{t}}",
    CALL_WITH_HR: "Silahkan kontak staff sebelum kedatangan anda untuk dapatkan jadwal bertemu yang tepat dan validasi parkir.",
    DESCRIPTION_PLAY_VIDEO: "Mari ingat pelajaran lebih baik dengan ringkasan berikut",
    NEXT: "Lanjutkan",
    DONE: "Selesai",
    TRAINING_PROGRAM: "Program pelatihan",
    READING_TIME: "Waktu belajar:",
    BY_MINUTUES: "Menit",
    TRAINING: "Pelajaran",
    TRAINING_DESCRIPTION: "Silahkan bertempat di tempat yang sunyi di waktu luang anda dan fokus kepada pelajaran.",
    TEST: "Ujian",
    TEST_DESCRIPTION: "Mohon baca ringkasan pelajaran dengan seksama untuk ujian yang efektif",
    PASS: "Lulus",
    FAILED: "Gagal",
    REMAINING_TIME: "Jumlah percobaan yang tersisa:",
    LESSON: "Pelajaran {{t}}",
    TRAINING_DETAIL_TITLE: "Detail pelajaran",
    SUMMARY: "Ringkasan",
    FINISH_TEST_SUCCESS: "Selamat atas menyelesaikan ujian",
    TEST_FAILD_LIMITED: "Anda tidak lulus ujian",
    TEST_AGAIN: "Ulangi ujian",
    COME_BACK_LATER: "Kembali nanti",
    NUMBER_OF_CORRECT_ANSWER: "Jumlah jawaban yang benar: ",
    TAKE_THE_TEST: "Take the quiz now!",
    INFO_TEST: "Result: {{t1}}/{{t2}}",
    DES_SEE_TEST: "The quiz will be opened after watching the video",
    CORRECT: "Correct",
    WRONG: "Wrong",
  },
  TRAINING_PREMIUM: {
    TITLE: "Pelatihan Premium",
    SHARE: 'Sebarkan',
    TASKER_PREMIUM_TITLE: 'Sertifikat',
    TASKER_PREMIUM_SUB_TITLE: 'Kolaborator berpengalaman',
    CONTENT: "Peraturan untuk mendapat gelar kolabolator berpengalaman",
    PASS_TITLE: "Selamat atas lolos tes",
    REGULATIONS_TASKER_PREMIUM: 'Peraturan pekerjaan untuk kolabolator berpengalaman',
    WITHDRAW_TASKER_PREMIUM_TITLE: 'Peraturan pekerjaan untuk kolabolator berpengalaman',
    REGULATIONS_TASKER_PREMIUM_1: 'Terapkan ketentuan dan kesepakatan sesuai dengan catatan kesepakatan kerja sama saat daftar untuk menjadi kolaborator bTaskee.',
    REGULATIONS_TASKER_PREMIUM_2: 'Kolaborator senior akan **DIKELUARKAN** jika melanggar peraturan:',
    REGULATIONS_TASKER_PREMIUM_2_1: 'Negosiasi bersama pelanggan bTaskee diluar sistem.',
    REGULATIONS_TASKER_PREMIUM_2_2: 'Pelanggaran seragam dan perilaku.',
    REGULATIONS_TASKER_PREMIUM_2_3: 'Kualitas pelayanan tidak terjamin.',
    REGULATIONS_TASKER_PREMIUM_2_4: 'Pelanggaran mengenai perilaku.',
    REGULATIONS_TASKER_PREMIUM_3: 'Saat lisensi kolaborator dicabut, dia akan:',
    REGULATIONS_TASKER_PREMIUM_3_1: 'Tidak bisa menerima pekerjaan premium.',
    REGULATIONS_TASKER_PREMIUM_3_2: 'Tidak dapat berpartisipasi dalam penghargaan bulanan.',
    REGULATIONS_TASKER_PREMIUM_4: 'Akan ada pengecekan setiap hari untuk:',
    REGULATIONS_TASKER_PREMIUM_4_1: 'Penarikan lisensi jika Tasker melanggar.',
    REGULATIONS_TASKER_PREMIUM_4_2: 'Terbitkan lisensi lagi saat Tasker memenuhi persyaratan.',
    CONDITION_TASKER_PREMIUM_TITLE: 'Aturan untuk menjadi CTV premium bTaskee',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_1: 'Memiliki rata-rata bintang 4.80 atau lebih.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_2: 'Ada lebih dari 10 pelanggan yang dipilih.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_3: 'Memiliki peralatan lengkap sesuai standar bTaskee.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_4: 'Memiliki Vacuum Cleaner.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_5: 'Memiliki tas ransel.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_6: 'Telah menyelesaikan setidaknya 200 pekerjaan bTaskee dalam sistem.',
    TITLE_TASKER_PREMIUM: "Training now",
    LABEL_START_NOW: "Becoming Premium",
  },
  INTRO_APP: {
    BUTTON_START: "Mulai",
    TITLE: "Kelebihan bersama bTaskee",
    LEARN_MORE: "Pelajari lebih lanjut",
    START_WORKING: "Let turn your free time to income",
    ALREADY_ACCOUNT: "Apakah anda sudah memiliki akun?",
    FLEXIBLE_TIME: "Waktu fleksibel",
    HIGH_INCOME: "Pendapatan tinggi",
    COMMUNITY_REWARD: "Komunitas & Hadiah",
    FLEXIBLE_TIME_1: "Jam kerja fleksibel berdasarkan pendapatan anda",
    FLEXIBLE_TIME_2: "Ubah waktu luang anda menjadi pendapatan",
    HIGH_INCOME_1: "Dapatkan hingga 20 juta/bulan jika anda mengikuti pekerjaannya dengan tekun dan rajin.",
    COMMUNITY_REWARD_1: "Komunitas besar berhubungan, membagi, menghadiahkan dan membantu orang-orang domestik.",
    COMMUNITY_REWARD_2: "Kolaborator berhak atas kebijakan dukungan hingga 100 Juta VND.",
    HIGH_INCOME_TITLE_TH:"Dapatkan banyak, kerja dengan mudah!",
    HIGH_INCOME_CONTENT_TH:"Bersama bTaskee, anda bisa mendapat 30,000 Baht per bulan, ditambah tip dan bonus!",
    FLEXIBLE_TIME_TITLE_TH:"Menjadi bos dalam hidup anda!",
    FLEXIBLE_TIME_CONTENT_TH:"Bersama bTaskee, anda bisa memilih kapan dan seberapa banyak kerjaan anda. Tidak lebih dari 8 jam per hari!",
    COMMUNITY_REWARD_TITLE_TH:"Keluarga didahulukan!",
    COMMUNITY_REWARD_CONTENT_TH:"Bersama bTaskee, anda bisa menghabiskan waktu dengan orang-orang yang anda cintai. Keseimbangan antara pekerjaan dan kehidupan sehari-hari? Bisa tercapai!",
    FLEXIBLE_TIME_ID:"Jam kerja fleksibel dan tergantung pilihan anda. Ubah waktu luang anda menjadi pemasukan.",
    HIGH_INCOME_ID:"Anda bisa dapat pendapatan tinggi dan kerjaan stabil dengan jam kerja yang fleksibel.",
    COMMUNITY_REWARD_ID:"Bergabung dalam komunitas moderen, dinamis, dan praktis.",
  },
  SETTINGS: {
    SETTINGS: "Pengaturan",
    LANGUAGE: "Bahasa",
    NOTIFICATION: "Notifikasi",
    NOTIFICATION_TASK: "Dapatkan pemberitahuan pekerjaan",
    NOTIFICATION_ON: "Nyala",
    NOTIFICATION_OFF: "Mati",
    FEE_SCHEDULE: "Jadwal gratis",
    YOUR_WORKTIME: "Waktu senggang",
    BUSY_TIME: "Waktu sibuk",
    REMIND: "Pra-Pengingat",
    MINUTE: "Menit",
    HOURS: "Jam",
    MORNING: "Pagi",
    AFTERNOON: "Siang",
    EVENING: "Sore",
    UPDATE: "Perbarui",
    NOTE_TASKER_UPDATE_SCHEDULE: "Anda hanya dapat memperbarui satu kali (jika ingin mengubah, silakan hubungi bTaskee).",
    TEXT_VIBRATION:"HP getar saat mendapatkan notifikasi pekerjaan baru"
  },
  TOPUP: {
    MIN_COST_TOPUP: "Jumlah minimum:",
    INSTRUCTTION_NOTE: "Akun anda akan diperbarui dalam 24 jam setelah uang di transfer.",
    BANK_TRANFER: "Bank:",
    BANK_INFO_ACCOUNT_HOLDER: "Pemilik akun",
    BANK_INFO_ACCOUNT_NUMBER: "Nomor rekening:",
    BANK_INFO_TRANFER_CONTENT: "Catatan:",
    BANK_INFO_CONTENT_SYNTAX: "Masukkan nama lengkap dan nomor telepon anda",
    LBL_EX_DEPOSITE: "VD: Nguyen Thi A 0123456789",
    NOTE_DEPOSIT_MONEY: "Catatan: Uang deposit di akun dapat digunakan untuk menerima pekerjaan, tidak untuk membayar pengeluaran lain seperti tas ransel, seragam, dsb.",
    SAVE_IMAGE: "Menyimpan gambar",
    SAVE_IMAGE_SUCCESS: "Sukses menyimpan gambar",
    BTASKEE_THAILAND: "bTaskee (Thailand)",
    METHOD: "Metode top-up",
    OPEN_BANK_APP: "Buka aplikasi bank",
    SCAN: "Pindai",
    SELECT_PHOTO: "Pilih foto",
    BUTTON_DONE: "Selesai",
    MIN_MONEY: "Jumlah minimum yang dapat disimpan",
    MAX_MONEY: "Jumlah maksimum yang dapat disimpan",
    IMAGE_DOWNLOAD_PERMISSTION: "Izin unduh foto",
    IMAGE_DOWNLOAD_PERMISSTION_MESS: "Izin anda dibutuhkan untuk menyimpan foto dari perangkat anda",
    COMING_SOON: "Coming soon",
    NOTE:"Catatan:",
    QR_CODE: "Scan QR code",
    NOTE_LABEL: "Note: ",
    QR_NOTE: "How to top up money online via QR code?",
    STEP_1: "Click Save to download the QR code image to your device.",
    STEP_2: "Open your banking app",
    STEP_3: "Go to Scan or Scan QR, then select the QR code image you just took from your photo library.",
    STEP_4: "Please enter the amount you want to deposit into your account, note that the minimum deposit is {{money}}.",
    TOPUP_TO_BANK: "Top up your account",
  },
  WITHDRAW: {
    NOTE: "Catatan: Anda harus memiliki setidaknya {{currency}}{{amount}} yang tersisa di akun anda untuk terus bekerja. ",
    VALID_AMOUNT: "Jumlah uang untuk diambil mulai dari {{currency}}{{minCost}} hinga {{currency}}{{maxCost}}",
    ERROR_SCOPE_OF_MONEY: "Jumlah uang yang anda masuki tidak sesuai dengan jangkauan jumlah pengambilan uang!",
    MONEY: " {{currency}}{{cost}}",
    RECEIPT_OF_MONEY_INFO: 'Permintaan penarikan anda akan diproses hari Selasa dan Jumat minggu depan. Bank akan transfer uang anda dalam 1-3 hari kerja.',
    TECHCOMBANK: "VietNam Technological and Commercial Joint Stock Bank",
    TRANSFER_FEE: "Biaya transfer",
    ERROR_TCBANK_NUMBER: "Anda belum masukkan nomor rekening anda. Mohon perbarui nomor rekening anda sebelum mengambil uang.",
    UNABLE_TO_WITHDRAW_1: 'Anda butuh setidaknya',
    UNABLE_TO_WITHDRAW_2: ' untuk menarik uang, anda harus memiliki akun aktif!',
    LABEL_NOTE: "Catatan: ",
    MIN_MONEY_NOTE: "Untuk tetap mendapat pekerjaan, akun aktif anda harus memiliki setidaknya: ",
    MIN_MONEY: "Nominal minimal penarikan: ",
    SCOPE_OF_MONEY: "Anda bisa menarik nominal dari {{t1}} hingga {{t2}}.",
    KASIKORN_BANK: "Kasikornbank",
    RECEIPT_OF_MONEY_INFO_TH: 'Anda akan mendapatkan uang ke akun anda setiap Selasa dan Jumat dari 18.00, harus diminta setidaknya 1 hari sebelumnya. Jika permintaan dibuat Selasa dan Jumat, itu akan dihitung sebagai siklus penarikan selanjutnya. Direkomendasikan untuk menarik di hari Senin atau Kamis untuk mendapat jumlah penarikan yang lebih banyak.',
  },
  ABOUT_BTASKEE: {
    TITLE: "Tentang bTaskee",
    DESCRIPTION: "Kegiatan komunitas kami",
  },
  NEW_VERSION_APP: {
    CONTENT_UPDATE_APP: "Telah sedia versi terbaru. Silahkan perbarui pengalaman difitur baru.",
    TITLE_BUTTON_UPDATE_VERSION: "Hubungi",
    MAINTENANCE_APP_TITLE: "Sistem sedang diperbarui. Silahkan kembali lagi.",
    NEW_VERSION_BUTTON: "Perbarui Sekarang",
  },
  CAR_ADVERTISING: {
    YOUR_REFERRAL_CODE: "Kode referral",
    BUTTON_SHARE_REFERRAL_CODE: "Bagikan kode referral",
    NUMBER_PEOPLE_REGISTER_WITH_REFERRAL: "Number of customers who have created accounts",
    NUMBER_PEOPLE_DONE_TASK: "Number of customers who booked the first task",
    TITLE_HISTORY_TRANSACTION: "Riwayat transaksi",
    COST_AND_CURRENCY: "{{cost}} {{currency}}",
    INVITE_ASKER_TEXT_HEAD: "Daftarkan akun baru menggunakan referal",
    INVITE_ADVERTISING_SHARE_TEXT: "Daftar untuk menjadi Tasker dengan kode referal {{kode referal}} untuk mendapatkan {{nominal referal}} di promosi setelah anda menyelesaikan pekerjaan. Atau dapatkan 01 {{jumlah voucher}} voucher setelah anda sukses mendaftarkan akun pelanggan menggunakan kode referal {{kode referal}",
    INVITE_ASKER_TEXT_TAIL: "to get voucher worth when the first task is finished.",
  },
  MONTHLY_REWARD: {
    TITLE: "Detail Hadiah",
    CONGRATULATIONS: "Selamat untuk anda!",
    BUTTON_REWARD: "Hadiah sekarang ",
  },
  LAUNDRY: {
    TITLE_WAITING_COLLECT: "Diterima",
    TITLE_WAITING_RETURN: "Dibayar",
    RETURN_DATE: "Waktu kembali: ",
    CHECK_AND_CONFIRM: "Periksa dan konfirmasi",
    PICK_UP_CLOTHES: "Ambil peralatan anda",
    COLLECTION_DATE: "Tanggal pengiriman: ",
  },
  SUPPORT: {
    TITLE: "Bantuan",
    DESCRIPTION: "Karyawan bantuan dan jam kerja.",
    TITLE_DAILY_WORK: "Bantuan kerjaan setiap hari",
    TITLE_PERSONNEL_WORK: "Bantuan HR",
    TITLE_PERSONNEL_WORK2: "(Membuka, blokir akun, beristirahat, dll.)",
    TIME_DAILY_WORK: "Senin - Sabtu:",
    TIME_PERSONNEL_WORK: "Senin - Jumat:",
    SUNDAY: "Minggu",
    SATURDAY: "Sabtu",
    TIME_IN_WORK: "Jam kerja",
    OUT_OF_TIME: "Diluar jam",
    SWITCH_BOARD: "Hubungi operator",
    TEXT_OUT_OF_TIME: "Pusat panggilan tidak melayani diluar jam kerja."
  },
  RATING: {
    BUTTON_RATING: "Penilaian",
    TASKER_RATE_ASKER_TITLE: "Penilaian pelanggan",
    TASKER_RATE_ASKER_THANK: "Terima kasih telah menyelesaikan pekerjaan ini. Bagaimana anda menilai pelanggan anda?",
    TASKER_RATE_ASKER_TASK_NOT_FOUND: "Tidak bisa menilai pekerjaan sekarang, silahkan lewati langkah ini",
    ASKER_ONE_STAR_LABEL: "Buruk",
    ASKER_TWO_STAR_LABEL: "Tidak baik sekali",
    ASKER_THREE_STAR_LABEL: "Tidak Baik",
    ASKER_FOUR_STAR_LABEL: "Baik",
    ASKER_FIVE_STAR_LABEL: "Sempurna!",
    ASKER_WHAT_WENT_WRONG: "Apakah komentar anda?",
    ASKER_WHAT_COULD_BE_BETTER: "Apakah yang anda harap lebih baik?",
    ASKER_WHAT_GOOD: "Apakah hal yang baik mengenai pelanggan ini?",
    ASKER_RATING_REVIEW: "Ulasan anda",
    ASKER_THANK_YOU_NOTE: "Pesan terima kasih untuk pelanggan",
    ASKER_RATING_BAD_1: "Negosiasi pribadi",
    ASKER_RATING_BAD_2: "Lingkungan kerja yang tidak baik",
    ASKER_RATING_BAD_3: "Pekerjaan terlalu banyak",
    ASKER_RATING_BAD_4: "Tidak bisa dihubungi",
    ASKER_RATING_BAD_5: "Tidak ramah",
    ASKER_RATING_OTHER: "Lainnya",
    ASKER_RATING_GOOD_1: "Tidak boleh negosiasi pribadi bersama pelayan",
    ASKER_RATING_GOOD_2: "Memastikan keselamatan kerja",
    ASKER_RATING_GOOD_3: "Silahkan imbangi bobot dan jam kerja saat memesan layanan dalam aplikasi.",
    ASKER_RATING_GOOD_4: "Tetap berhubungan saat mendekati jam kerja",
    ASKER_RATING_GOOD_5: "Butuh lebih ramah",
    FRIENDLY: "Ramah",
    POLITE: "Sopan",
    CHEERFUL: "Sikap yang ceria",
    SUPPORT: "Ingin membantu",
    TASK_SUCCESS: "Pekerjaan anda selesai.",
    NOT_RATING: "Belum dinilai",
    YOUR_REVIEW: "Ulasan anda",
    LENGTH_OF_TEXT: "{{t}}/140 kata",
  },
  FILTER_NEW_TASK: {
    TITLE: "Saring sesuai waktu",
    BY_CREATED_AT: "Baru di unggah",
    BY_DATE: "Pekerjaan yang harus diselesaikan",
    BY_AREA: "Tampilkan pekerjaan hanya di area yang terdaftar"
  },
  SHARE_SCREEN: {
    YOUR_REFERRAL_CODE: "Your referral code",
    TEXT_SHARE_SUCCESS: "Bagaimana cara menyebar sukses",
    SHARE_WITH_YOUR_FRIEND: "Kode referral anda",
    FRIEND_DOW_APP: "Teman anda menjadi Tasker baru:",
    BE_REWARDED: "Teman anda menjadi Pelanggan baru",
    FAQ: "FAQ",
    GIFTS_FOR_YOU_FOR_ME: "Hadiah untuk anda dan kami",
    DESCRIPTION_BE_REWARDED: "Pada titik ini, hanya butuh arahan panduan khusus dan baca secara seksama bagian FAQ untuk mendapat panduan yang tepat!",
    DESCRIPTION_FRIEND_DOW_APP: "Teman/pelanggan hanya klik link referral, unduh aplikasi, dan masukkan kode referral anda.",
    DESCRIPTION_SHARE_WITH_YOUR_FRIEND: "Klik pada simbol BAGIKAN dibawah untuk membagikan kode referral.",
    HOW_GET_REWARD: "Bagaimana teman saya dapat hadiah?",
    DONE_GET_REWARD:"Saat mendaftarkan akun, mohon masukkan kode referral yang TEPAT.",
    REFERRAL_REWARD: "Hadiah referral",
    TOTAL_BONUS: "Bonus total",
    SEE_MORE: "Lihat semua",
    JOIN_DAY: "Hari bergabung                                                                                                                                                                                    ",
    ADD_TO_PROMOTION: "(Money will be added to your promotion account.)",
    SHARE_REFERRAL_CODE: "Bagikan",
    TITLE_SHARE_REFERRAL_CODE: "Bagikan ke(ke Tasker atau Pelanggan)",
    SUB_TITLE_SHARE_REFERRAL_CODE:"Bagikan ke(ke Tasker atau Pelanggan)",
    TEXT_Q1: "Q1",
    LABEL_COPY:"Tersalin",
    SHARE_WITH_ASKER: "Bagikan ke pelanggan",
    SHARE_WITH_TASKER: "Bagikan ke Tasker",
    DEEPLINK_TITLE: 'Mitra bTaskee - Aplikasi untuk tasker bTaskee',
  },
  KIT_CHEMICALS:{
    TITLE: "Peralatan dan bahan kimia",
    GET_KITS: "Kits",
    GET_CHEMICALS: "Chemicals",
    GET_KITS_AND_CHEMICALS_DETAIL: "Detail peralatan dan bahan kimia",
    PRESS_BUY_KITS_AND_CHEMICALS: "Lihat dimana bisa dibeli",
    KITS_AND_CHEMICALS_AMOUNT: "AJumlah mount",
    KITS_AND_CHEMICALS_PRICE: "Refrensi harga",
    KITS_AND_CHEMICALS_MONEY: "Ke uang",
  },
  DELETE_ACCOUNT:{
    TITLE:"Hapus akun",
    TURN_BACK:"Kembali",
    TEXT_AGREE_DELETE_ACCOUNT:"Saya setuju atas syarat dan ketentuan penghapusan akun",
    DELETE_ACCOUNT_TITLE_REASON:"Alasan",
    DELETE_ACCOUNT_SUB_REASON:"Kenapa anda menghapus akun ini?",
    PLACEHOLDER_TEXT_INPUT:"Silahkan masukkan alasan kenapa anda ingin menghapus akun ini",
    TEXT_TITLE_DELETE:"Apakah anda tidak mau jadi bTasker lagi?",
    TEXT_INFO_ACCOUNT:"• Informasi akun ",
    TEXT_CONFIRM:"Mohon konfirmasi jika menghapus akun anda akan menghilangkan informasi berikut:",
    TEXT_1:"• Akun yang terhapus tidak bisa kembali.",
    TEXT_2:"• Anda tidak bisa menggunakan email dan nomor telepon yang sama untuk membuat akun baru",
    TEXT_TRANS_INFO:"• Also, you won't be able to use this account's email and phone number to create a new account.",
    TEXT_TRANS_INFO_1:"Informasi yang berhubungan dengan transaksi, alamat tersimpan, metode pembayaran",
    TEXT_PRIVILEGES_BENEFIT:"• Tawaran dan manfaat",
    TEXT_PRIVILEGES_BENEFIT_1:"Anda akan kehilangan semua tawaran afiliasi, voucher, dan manfaat",
    TEXT_INFO_ACCOUNT_1:"Informasi personal yang berkaitan dengan akun Tasker",
    TEXT_INFO_ACCOUNT_2:"bTaskee tidak bertanggung jawab untuk kehilangan informasi, data, atau uang setelah akun dihapus.",
    DELETE_ACCOUNT_SUCCESS: "Akun anda telah dihapus secara permanen dari sistem bTaskee. Maaf atas ketidaknyamanan yang menyebabkan ini terjadi. Kami berharap anda segera kembali.",
    ARE_YOU_SURE: "Apakah anda yakin akan menghapus akun anda?",
  },
  BCARE: {
    TITLE:"Kebijakan Bantuan Kecelakaan",
    HEADER_TEXT:"Seluruh pekerjaan bTaskee dtanggung oleh asuransi",
    ROLE_LABEL: "Peran",
    ROLE_TEXT: "Sebagai Tasker di platform bTaskee.",
    CONDITION_LABEL: "Ketentuan",
    CONDITION_TEXT: "Perlindungan jika terjadi kecelakaan dalam jalan menuju rumah pelanggan dan saat mengerjakan pekerjaan dari sistem bTaskee:",
    CONDITION_TEXT_1: "• Meninggal",
    CONDITION_TEXT_2: "• Cacat sebagian atau total karena kecelakaan saat bekerja.",
    FEE_LABEL: "Biaya perlindungan",
    FEE_TEXT: "Tasker",
    FEE_TEXT_1: "tidak perlu",
    FEE_TEXT_2: "biaya asuransi tidak diperlukan",
    BENEFIT_LABEL: "Keuntungan",
    BENEFIT_TEXT: "1. Kolaborator akan dapat:",
    BENEFIT_TEXT_1: "• Biaya dukungan jika kecelakaan menyebabkan ke kematian",
    BENEFIT_TEXT_2: " • Biaya dukungan jika kecelakaan menyebabkan catat sebagian atau total",
    BENEFIT_TEXT_3: "• Biaya dukungan saat dirawat di rumah sakit untuk perawatan dikarenakan kecalakaan",
    BENEFIT_TEXT_4: "• Bantuan biaya obat-obatan yang dikarenakan kecelakaan.",
    BENEFIT_TEXT_5: "2. bTaskee akan membantu anda secara proaktif untuk hak dan manfaat anda.",
    AMOUNT_LABEL: "Tingkatan perlindungan",
    AMOUNT_TEXT: "Biaya bantuan perlindungan maksimal",
    AMOUNT_TEXT_1: "100,000,000 VND",
    PROCEDURE_LABEL: "Proses bantuan",
    PROCEDURE_TEXT_1: "Jika ada kecelakaan, mohon beri tahu bTaskee melalui hotline 0901.300.501 - tekan 8.",
    PROCEDURE_TEXT_2: "Simpan semua dokumen dan faktur pemeriksaan medis dan kirim ke perusahaan tidak lebih dari 30 hari setelah dibantu asuransi dalam waktu 30 hari setelah pelaporan.",
    PROCEDURE_TEXT_3: "Dapatkan faktur VAT saat membeli obat-obatan diluar rumah sakit yang berharga lebih dari 200,000 VND",
    REQUIRE_LABEL: "Permintaan",
    REQUIRE_TEXT_1: "Faktur",
    REQUIRE_TEXT_2: "Harga obat",
    REQUIRE_TEXT_3: "Sertifikat pemeriksaan kesehatan",
    NOTE: "Catatan:",
    NOTE_TEXT_1: "• Harus jelas, terlampir tanda tangan dan stempel dari rumah sakit, apotek, dan informasi pasien.",
    NOTE_TEXT_2: "• Tasker harus memberi perusahaan semua dokumen yang dibutuhkan untuk dipertimbangkan tingkat dukungan."
  },
  REFERRAL: {
    TITLE:"Masukkan kode referral untuk mendapatkan ahdiah.",
    YES:"Ya",
    NO:"Tidak"
  },
  MODAL_ALERT: {
    TITLE_MODAL_TIP:"Selamat",
    LABEL_MODAL_TIP:"Anda mendapat tip dari pelanggan.",
    TEXT_MODAL_TIP: "Kemampuan, kualitas, dan perilaku anda layak mendapat hadiah ini dari pelanggan. Terus berjuang dan memenangkan hati pelanggan lainnya!",
    TITLE_MODAL_LEVEL_UP: "Level Up",
  },
  PROCEDURE_ACTIVE_ACCOUNT: {
    BUTTON_TEST_NOW: "Ujian sekarang",
    TITLE_STEP_1: "Ujian Masukt",
    TITLE_STEP_2: "Pelatihan dasar",
    TITLE_STEP_3: "Perbarui profil",
    CONTENT_STEP_1: "Mari lihat berapa banyak kemampuan dan pola pikir yang anda miliki untuk menjadi penolong!",
    CONTENT_STEP_2:  "Silahkan ikuti pelatihan kemampuan dasar seblum anda bergabung ke sistem!",
    CONTENT_STEP_3:  "Selamat atas menjadi kandidat potensial bTaskee dan kami yakin kami akan mencapai banyak kesuksesan di waktu yang akan datang",
    NUMBER_OF_TIME_TEST:  "Berapa kali mengerjakan ujian",
    TEXT_SUCCESS:  "Selesai",
    TEST_FALSE:  "Anda telah melebihi jumlah yang ditentukan. Mohon telepon untuk bantuan.",
    MAKE_APPOINTMENT:  "Buat pertemuan",
    ACTIVE_SUCCESS_TITLE:  "Selamat",
    ACTIVE_SUCCESS_CONTENT: "Notification after a successful appointment booking: Congratulations, you have completed the application submission process. Please note that we will have a direct appointment at the office. When you come, please bring the notarized photocopies and original documents, including: ID card - Household registration book/Residential information confirmation - Curriculum vitae - Good conduct certificate.",
    TITLE_MAKE_AN_APPOINTMENT: "Buat pertemuan",
    BUTTON_CHAT:  "Pesan",
    BUTTON_CALL:  "Telepon sekarang",
    MORNING_APPOINTMENT:  "Pagi - 09:00",
    AFTERNOON_APPOINTMENT:  "Siang - 14.00",
    TITLE_SELECT_TIME: "Pilih Waktu",
    LABEL_DATE:  "Tanggal",
    LABEL_TIME:  "Jam",
    NOTE_SELECT_TIME: "Catatan: Mohon datang tepat waktu untuk pertemuan anda, jika telat akan mempengaruh bantuan SDM",
    TITLE_SELECT_PLACE: "Pilih tempat",
    APPROVED_TITLE:  "Disetujui",
    APPROVED_CONTENT: "Selamat atas melengkapi perbaruan profil inisial. Silahkan jadwalkan pertemuan di kantor terdekat untuk bantuan aktivasi akun.",
    PROCESSING_TITLE:  "Diproses",
    PROCESSING_CONTENT:"Profil anda sedang dimoderasi. Sistem akan memberitahu hasil secepatnya.",
    BUTTON_UPDATE_PROFILE: "Perbarui profil",
    REJECTED_TITLE:  "Ditolak"
  },
  SUPPLEMENT_INFO:{
    TITLE_ADD_SUPPLEMENT:"Unggah Profil",
    NOTE_SUPPLEMENT_1:"• Seluruh dokumen harus diaktakan dalam 6 bulan kebelakang.",
    NOTE_SUPPLEMENT_2:"• Mohon gunakan dokumen yang sama untuk mengambil foto depan dan belakang.",
    NOTE_SUPPLEMENT_3:"• Mohon ambil foto yang jelas tanpa memotong pojokan dan hindari silau apapun yang menutuplan dokumen.",
    TEXT_IDENTITY:"KTP",
    TEXT_RESIDENCY:"Kartu Keluarga",
    TEXT_CURRICULUM:"Daftar Riwayat Pekerjaan",
    TEXT_CERTIFICATE:"Sertifikat Perilaku",
    TEXT_REQUIRE:"* diperlukan",
    TEXT_OPTIONAL:"* opsional (anda bisa unggah nanti)",
    TEXT_SUPPLEMENT_NOTE:"Mohon ambil foto dokumen tambahan untuk profile anda",
    OPEN_PHOTO_GALLERY:"Ambil foto dari galeri",
    OPEN_IMAGE_CAMERA:"Ambil foto dari kamera",
    TEXT_NOTE_IDENTITY_1:"• Pastikan lingkungan ambil foto terang.",
    TEXT_NOTE_IDENTITY_2:"• Objek utama terletak di tengah dan dimuat di bingkai.",
    TAKE_A_PHOTO:"Ambil foto",
    IMAGE_FRONT_SIDE:"Sisi depan",
    IMAGE_BACK_SIDE:"Sisi belakang",
    UPLOAD:"Unggah",
    REUPLOAD:"Unggah ulang",
    OPEN_CAMERA:"Buka kamera",
    CHOOSE_PHOTO:"Pilih foto dari",
    UPLOAD_IMAGE:"Unggah foto",
  },
  JOURNEY:{
    TITLE:"Journey",
    LEADER_BOARD_SCREEN:"Leaderboard",
    TITLE_MAIN_PRIZE: "Main prize:",
    TITLE_BONUS: "Bonus:",
    BUTTON_GET_REWARD: "Get reward now",
    TRAINING: "Training now",
    TASK: "Back to home",
    TITLE_ALERT: "Detail",
    TITLE_NUMBER_OF_TASK: "{{t}} task",
    TITLE_CURRENT_LEVEL: "My level",
    AVG_RATING_CONDITION: "The average service quality must be {{t}} or higher",
    MESSAGE_GET_REWARD_SUCCESS: "Get reward success!",
    TITLE_RECEIVED_REWARD: "Received:",
    BONUS_PRIZE: "Bonus:",
    LABEL_TIME_PASSED: "Time has passed",
    TITLE_PRIZE_BONUS_DETAIL: "Bonus detail",
    TITLE_PRIZE_BONUS: "Bonus",
    HOURS: "{{t}} hours",
    DAYS: "{{t}} days ",
    TRAINING_PASSED: "Complete",
    TRAINING_INCOMPLETE: "Incomplete",
    BONUS_NOT_RECEIVE: "Unclaimed Gift:",
    RECEIVE_AT_OFFICE: " (received at the office)",
    LABEL_PROCESSING: "Processing",
    LABEL_PASSED: "Passed",
    LABEL_LOCKED: "Lock",
    LABEL_MISSION: "Mission:",
    LEADER_BOARD_EMPTY: "List leader board is being updated!",
    TEXT_MODAL_ALERT_LEVEL_UP: "Congratulations on reaching",
    DESCRIPTION_MODAL_ALERT_LEVEL_UP: "Get rewarded for your efforts and try harder in the future!",
    TITLE_BUTTON_SEE_REWARD: "See rewards",
    TITLE_BUTTON_NEXT_REWARD: "Next rewards",
    LABEL_MODAL_ALERT_LEVEL_UP_REWARD: "Congratulations",
    TEXT_BONUS_PRIZE: "Bonus prize",
    TITLE_BUTTON_RANK_SCORE: "How to calculate the ranking score?",
    TITLE_CALCULATE_SCORE: "How to calculate points?",
    TITLE_HOW_TO_CALCULATE_SCORE: "How to calculate rating points",
    TEXT_CALCULATE_SCORE_1: "After completing 1 task, your score will be calculated based on the formula:",
    TEXT_CALCULATE_SCORE_2: "Extra Ranked Points = ",
    TEXT_CALCULATE_SCORE_3: " “Rate the quality of service” ",
    TEXT_CALCULATE_SCORE_4: " “Time to complete the task” ",
    TEXT_CALCULATE_SCORE_5: "For example, when completing **1 task** that requires execution from **12:00 to 16:00 (4 hours)** and is rated by a customer **5 stars**, you will have:",
    TEXT_CALCULATE_SCORE_6: "1 + 4 + 5 = 10 (point)",
    TITLE_RATING_SERVICE_QUALITY: "Service quality rating",
    TEXT_RATING_SERVICE_QUALITY_1: "From 1 to 5",
    TEXT_RATING_SERVICE_QUALITY_2: "When the Task is done, be sure to remind the customer to rate the service for additional rating points. Try to do well to get a 5 star rating, you will get 5 points.",
    TITLE_DURATION: "Time to complete the task",
    TEXT_DURATION_1: "Based on the required time of the task",
    TEXT_DURATION_2: "Note that the task completion time is fixed when the customer places the service, you cannot deliberately delay the completion of the work longer to earn more points.",
    TITLE_DETAIL_JOURNEY: "Journey detail",
    LEARN_MORE: "Learn more",
    DESCRIPTION_LEARN_MORE: "You can view all the information about the Bee Journey here.",
    COMING_SOON: "Coming soon",
    CURRENT_LEVEL: "Current level",
    TEXT_TRAINING_TO_RECEIVE_BONUS: "Complete training to get rewards",
  },
  MEMBER_INFO: {
    TITLE: "Member Infor",
    BPOINT_HISTORY: "bPoint History",
    VIEW: "View",
    SEE_NOW: "See now",
    LABEL_AVAILABLE_POINT: "Available bPoint",
    BROWSE_BREWARD: "Browse bRewards",
    RECOMMEND_FOR_YOU: "Recommend for you"
  },
  BREWARD: {
    RECOMMEND_FOR_YOU: "Recommend for you",
    FLASH_SALES: "Flash Sales",
    TOP_DEALS: "Top Deals",
    EXCLUSIVE_DEALS: "Exclusive Deals",
    VIEW_MORE: "View more",
    REDEM_NOW: "Redeem now",
    ALL: "All",
    TITLE_BPOINT_HISTORY_RECEIVED: "Received",
    TITLE_BPOINT_HISTORY_USED: "Used",
    EMPTY_TRANSACTION: "List transaction is empty!",
    TITLE_BUTTON_VIEW_MORE: "View more",
    EXPIRED_DATE:"Expired date",
    MY_REWARD: "My reward",
    RECENT_SEARCHES:"Recent searches",
    VOUCHERS_SEARCHES:"Vouchers searches",
    SEARCH:"Search for vouchers by voucher name: Discount ...",
    BUTTON_AGREE:"Agree",
    BUTTON_LATER:"Later",
    TITLE_CONTACT:"Contact",
    STORE:"Store List",
    BRANCH_STORE:"Currently {{t}} active",
    BRANCH_STORE_EMPTY:"The list of stores is being updated",
    DOW_IOS:"IOS",
    DOW_ANDROID:"Android",
    DOW:"Download the application",
    OUT_OF_STOCK: "Out of stock",
  },
  WEATHER:{
    TITLE: "Weather",
    BY_DATE: "By date",
    BY_HOUR: "By hour",
    PARTLY_CLOUDY: "Partly cloudy",
    MODERATE_RAIN: "Moderate rain",
    PATCHY_RAIN_POSSIBLE: "Patchy rain possible",
    SUNNY: "Sunny",
    CLEAR: "Clear",
    OVERCAST: "Overcast",
    CLOUDY: "Cloudy",
    LIGHT_RAIN: "Light rain",
    MODERATE_RAIN_AT_TIME: "Moderate rain at times",
    HEAVY_RAIN: "Heavy rain",
    HEAVY_RAIN_AT_TIME: "Heavy rain at times",
    MODERATE_OR_HEAVY_FREEZING_RAIN: "Moderate or heavy freezing rain",
    MODERATE_OR_HEAVY_RAIN_SHOWER: "Moderate or heavy rain shower",
    MODERATE_OR_HEAVY_RAIN_WITH_THUNDER: "Moderate or heavy rain with thunder",
    MIST: "Mist",
    FOG: "Fog",
    PATCHY_RAIN_NEARBY: "Patchy rain nearby",
    PATCHY_SNOW_NEARBY: "Patchy snow nearby",
    PATCHY_SLEET_NEARBY: "Patchy sleet nearby",
    PATCHY_FREEZING_DRIZZLE_NEARBY: "Patchy freezing drizzle nearby",
    THUNDERY_OUTBREAKS_IN_NEARBY: "Thundery outbreaks in nearby",
    FREEZING_FOG: "Freezing fog",
    PATCHY_LIGHT_DRIZZLE: "Patchy light drizzle",
    LIGHT_DRIZZLE: "Light drizzle",
    FREEZING_DRIZZLE: "Freezing drizzle",
  }
};
