export default {
  VALIDATE: {
    THIS_FIELD_IS_REQUIRED: "ข้อมูลที่ต้องการ",
    ERROR_PASSWORD_LENGTH: "รหัสผ่าน 6-12 ตัวอักษรไม่เว้นวรรค",
    TYPE_INPUT_INVALID: "ข้อมูลไม่ถูกต้อง",
  },
  ERROR: {
    ERROR_TRY_AGAIN: "เกิดข้อผิดพลาด โปรดลองอีกครั้งในภายหลัง! [{{t}}]",
    PHONE_NUMBER_SYNTAX_IS_INCORRECT: "หมายเลขโทรศัพท์ไม่ถูกต้อง",
    SEND_OTP_MESSAGE_ACCOUNT_NOT_EXIST: "หมายเลขโทรศัพท์นี้ไม่มี",
    ACTIVATION_ERROR_CODE: "รหัสเปิดใช้งานไม่ถูกต้องโปรดลองอีกครั้ง",
    USER_NOT_FOUND: "บัญชีไม่มีอยู่",
    USER_LOCKED: "บัญชีของคุณถูกล็อคชั่วคราวโปรดติดต่อเราเพื่อขอรายละเอียดเพิ่มเติม",
    INVALID_PASSWORD: "รหัสผ่านไม่ถูกต้อง กรุณาพิมพ์อีกครั้ง",
    USER_TYPE_INCORRECT: "หมายเลขโทรศัพท์นี้ได้ลงทะเบียนในแอพลิเคชันของลูกค้าแล้ว โปรดติดต่อเจ้าหน้าที่เพื่อช่วยเหลือท่าน",
    USER_PERMISSION_DENIED: "คุณไม่ได้รับการอนุญาตให้เข้าถึง",
    NETWORK_REQUEST_FAILED: "ไม่มีสัญญาณ กรุณาตรวจสอบอินเตอร์เน็ตของท่าน",
    CANCEL_LIMITED: "งานนี้ไม่สามารถยกเลิกได้ คุณยกเลิกงานเกินกำหนดใน 7 วันที่ผ่านมา",
    ACTIVATION_CODE_INVALID: "รหัสรับรองความถูกต้องผิดพลาด กรุณาลองอีกครั้ง",
    BUTTON_RELOAD: "โหลดใหม่",
  },
  PERMISSION: {
    ACCESS_PHOTOS_TITLE: "ขออนุญาตเข้าถึงคลังรูปภาพ",
    ACCESS_PHOTOS_CONTENT: "สำหรับการใช้งานฟังก์ชันนี้ bTaskee ต้องการเข้าถึงคลังรูปภาพของคุณ",
    WRITE_EXTERNAL_STORAGE_TITLE: "อนุญาตเข้าถึงพื้นที่จัดเก็บข้อมูล",
    WRITE_EXTERNAL_STORAGE_CONTENT: "bTaskee ขออนุญาตเข้าถึงพื้นที่จัดเก็บข้อมูลในโทรศัพท์ของคุณ",
  },
  NOTIFICATION: {
    TAB_NOTIFICATION: "แจ้งเตือน",
    NOTIFICATION_MESSAGE: "คุณต้องการลบการแจ้งเตือนหรือไม่?",
    NOTIFICATION_MESSAGE_NOTHING: "ยังไม่มีข้อความในตอนนี้",
    NOTIFICATION_DETAIL: "รายละเอียดการแจ้งเตือน",
    TASK_NOTIFICATION: "การแจ้งเตือนงานใหม่",
    SYSTEM_NOTIFICATION: "การแจ้งเตือนของระบบ",
    HAPPY_BIRTHDAY_TITLE: "สุขสันต์วันเกิด",
    TITLE_HAVE_NEW_TASK: "งานใหม่",
    READ_ALL_NOTIFICATION: "อ่านทั้งหมด",
    TITLE_NOTIFICATION_WARNING: 'การแจ้งเตือนของคุณถูกปิด',
    CONTENT_NOTIFICATION_WARNING: 'คุณอาจพลาดงานราคาสูง เมื่อคุณปิดการแจ้งเตือน  เปิดฟังชั่นการแจ้ง',
    TURN_ON_NOTIFICATION: 'เตือนทันที',
  },
  DIALOG: {
    BUTTON_CLOSE: "ปิด",
    BUTTON_ACCEPT: "ตกลง",
    TITLE_INFORMATION: "ประกาศ",
    TITLE_ERROR: "ขออภัย",
    BUTTON_SEE: "ดูข้อมูลเพิ่มเติม",
    BUTTON_DONE: "เสร็จสิ้น",
    BUTTON_SEE_AGAIN: "ดูข้อมูลเพิ่มเติมอีกครั้ง",
    BUTTON_CALL_SUPPORT: "ติดต่อเจ้าหน้าที่",
    UPDATE_SUCCESS: "อัพเดตเสร็จเรียบร้อย",
    BUTTON_CONFIRM: "ใช่",
    BUTTON_UPDATE: "อัพเดต",
    BUTTON_NEXT: "ต่อไป",
    CANCEL_TASK_SUCCESS: "กรุณาเลือกรับงานอื่นๆ ที่คุณสามารถทำได้แทน",
    ARE_YOU_SURE_TO_GO_BACK: "คุณแน่ใจหรือว่าต้องการย้อนกลับ?",
    BUTTON_CANCEL: "ยกเลิก",
    BUTTON_SKIP: "ข้าม",
    BUTTON_SEE_MORE: "ดูตอนนี้"
  },
  LOGIN: {
    TITLE_LOGIN: "ลงชื่อเข้าใช้",
    USERNAME: "หมายเลขโทรศัพท์",
    PASSWORD: "รหัสผ่าน",
    BUTTON_LOGIN: "ลงชื่อเข้าใช้",
    FORGOT_PASSWORD: "ลืมรหัสผ่าน",
    SIGN_UP: "ลงชื่อสมัครใช้",
    VERSION: "เวอร์ชัน {{t}}",
    BUILD_NUMBER: "โค้ด {{t}}",
    TASKER_APP: "สำหรับ bTasker",
    MESSAGE_ACCOUNT_ACTIVE: "บัญชีของคุณยังไม่ได้เปิดใช้งาน, กรุณาเปิดใช้งานทันที",
    MESSAGE_ACCOUNT_TASKER_LOCK: "bTaskee regrets to restrict your account at this time. Please contact Call Center to continue accepting work.",
    MESSAGE_TOKEN_EXPIRED: "บัญชีของคุณเข้าสู่ระบบอุปกรณ์อื่น ๆ แล้ว กรุณาเปลี่ยนรหัสผ่านถ้าไม่ได้รับอนุญาต โปรดเข้าสู่ระบบอีกครั้งเพื่อใช้บริการของเรา"
  },
  CHOOSE_LANGUAGE: {
    TITLE: "เลือกภาษา",
    VI: "Tiếng Việt",
    EN: "English",
    TH: "ภาษาไทย",
    ID: "Bahasa Indonesia",
  },
  COUNTRY: {
    INDONESIA: "อินโดนีเซีย",
    VIETNAM: "เวียดนาม",
    THAILAND: "ไทย",
  },
  REGISTER: {
    TITLE_REGISTER: "ลงชื่อสมัครใช้",
    FULL_NAME: "ชื่อ-นามสกุล",
    FULL_NAME_PLACEHOLDER: "Nguyễn Văn A",
    ID_NUMBER: "บัตรประชาชน",
    ID_NUMBER_PLACEHOLDER: "123456789",
    PHONE_NUMBER: "หมายเลขโทรศัพท์",
    PHONE_NUMBER_PLACEHOLDER: "0623456789",
    PASSWORD: "รหัสผ่าน",
    PASSWORD_PLACEHOLDER: "อย่างน้อย 6 ตัวอักษร",
    REFERRAL_CODE: "รหัสแนะนำ (ถ้ามี)",
    REFERRAL_CODE_PLACEHOLDER: "รหัสแนะนำ",
    BUTTON_REGISTER: "สมัครร่วมงาน",
    BUTTON_CHOOSE_WORKING_PLACES: "เลือกพื้นที่ทำงาน",
    BUTTON_CONFIRM_OTP: "เปิดใช้งาน",
    BUTTON_RESEND_CODE: "ส่งรหัสอีกครั้ง",
    REFERRAL_REWARD: "ใส่รหัสแนะนำการสมัครงาน จากเพื่อนของคุณ เพื่อรับสิทธิพิเศษมากมายจากบีทัสกี",
    BUTTON_NEXT: "ดำเนินการต่อ",
    BUTTON_RESEND_CODE_1: "คุณยังไม่ได้รหัส OTP? ",
    TEXT_OTP:"รหัส OTP จะหมดอายุใน "
  },
  REGISTER_CHOOSE_WORKING_PLACE_CITY: {
    TITLE: "เลือกเมืองทำงาน",
    CHOOSE_CITY: "เขตที่คุณสะดวกรับงาน",
    NOTE_CHOOSE_SERVICE: "โปรดทราบว่าบริการอาจแตกต่างกันไปตามจังหวัดและคุณจะต้องเลือกเพียงจังหวัดเดียวเพื่อทำงาน",
  },
  REGISTER_CHOOSE_WORKING_PLACE_DISTRICT: {
    TITLE: "เลือกพื้นที่",
    LIMIT_DISTRICT: "เลือกได้สูงสุด 3 เขต",
    CHOOSE_DISTRICT: "เขตที่คุณสะดวกทำงาน",
  },
  REGISTER_CHOOSE_SERVICES: {
    TITLE: "เลือกบริการ",
    BUTTON_REGISTER: "สมัครสมาชิก",
    CHOOSE_SERVICES: "คุณสนใจสมัครงานบริการใด?",
  },
  CONFIRM_CHOOSE_WORKING_PLACE_AND_SERVICES: {
    CONFIRM: "ตกลง",
    CONFIRM_NOTE: "โปรดตรวจสอบข้อมูลที่คุณได้ลงทะเบียนอีกครั้ง หลังจากที่คุณยืนยันว่าข้อมูลถูกต้องแล้ว ขั้นตอนถัดไปคือการทำแบบทดสอบประเมิณทักษะและความสามารถ",
    SERVICES: "บริการ",
    DISTRICTS: "พื้นที่",
    SAVE_SUCCESS: "ยินดีด้วยคุณได้อัพเดตเรียบร้อยแล้ว",
  },
  FORGOT_PASSWORD: {
    TITLE: "ลืมรหัสผ่าน",
    DESCRIPTION: "ป้อนหมายเลขโทรศัพท์ที่ลงทะเบียนเพื่อรับรหัสผ่านของคุณ",
    RESEND_PASSWORD: "ส่งรหัสผ่านใหม่",
  },
  SET_PASSWORD: {
    TITLE: "เปลี่ยนรหัสผ่าน",
    DESCRIPTION: "รหัสผ่านใหม่จะใช้ในการเข้าสู่ระบบครั้งถัดไป",
    NEW_PASSWORD: "รหัสผ่านใหม่",
    SAVE: "บันทึก",
    SUCCESS_SET_PASSWORD: "เปลี่ยนรหัสเสร็จสมบูรณ์",
    WELCOME: "ยินดีต้องรับสู่ bTaskee",
  },
  CHANGE_PASSWORD: {
    TITLE: "เปลี่ยนรหัส",
    DESCRIPTION: "รหัสนี้จะเป็นรหัสที่คุณจะต้องใช้ในการเข้าระบบครั้งถัดไป",
    INPUT_OLD_PASSWORD: "ใส่รหัสเก่า",
    OLD_PASSWORD: "รหัสเก่า",
    INPUT_NEW_PASSWORD: "ใส่รหัสใหม่",
    NEW_PASSWORD: "รหัสใหม่",
    ACCESS: "การเข้าถึง",
    SUCCESS_CHANGE_PASSWORD: "การเปลี่ยนรหัสของคุณเสร็จเรียบร้อย",
    CHANGE_PASSWORD: "เปลี่ยนรหัส",
    WELCOME: "ยินดีต้องรับสู่ bTaskee",
  },
  CHOOSE_COUNTRY: {
    TITLE_CHOOSE_COUNTRY: "เลือกประเทศ",
    BUTTON_NEXT: "ต่อไป",
    TITLE: "คุณพักอาศัยที่ไหน?",
  },
  OTP: {
    TITLE: "เปิดใช้งานบัญชี",
    HELLO: "สวัสดี",
    INSTRUCTION_OTP: "รหัสเปิดใช้งานได้ถูกส่งไปยังโทรศัพท์ของคุณ {{t}} กรุณาตรวจสอบข้อความ SMS และป้อนรหัสเพื่อเปิดใช้งานในช่องข้อความด้านล่าง",
    ACTIVATION_CODE: "รหัสเปิดใช้งาน",
    RESEND_CODE_ERROR: "คุณกดส่งหลายครั้งเกินไป กรุณาลองใหม่อีกครั้งในภายหลัง",
  },
  TASK_DETAIL: {
    TITLE: "รายละเอียดงาน",
    DESCRIPTION_FOR_PROMOTION: "เพิ่มไปยังบัญชีโปรโมชัน",
    PAYMENT_METHOD_LABEL: "วิธีชำระเงิน:",
    TYPE_HOUSE_LABEL: "ประเภทบ้าน: ",
    NOTE_LABEL: "หมายเหตุ: ",
    BUTTON_SEE_FULL_NOTE: "ดูทั้งหมด",
    BUTTON_SLIDE_TO_CONFIRM: "เลื่อน เพื่อรับงานนี้",
    BUTTON_FAQ: "คำถามที่พบบ่อย",
    STATUS_WAITING_CONFIRM: "รอการยืนยันจากคุณ",
    WITHDRAW_TASK: "ขอถอนตัวจากงานนี้",
    BEGIN_WORK: "เริ่มทำงาน",
    TASK_IS_WORKING: "งานที่กำลังทำ",
    DURATION_NOTE: "ระยะเวลาการทำงาน {{duration}} ชั่วโมง",
    COUNT_DOWN_TIME_START_JOB: "งานนี้จะเริ่มในอีก {{time}}",
    COUNT_DOWN_TIME_START_JOB_TASK_ITEM: "เริ่มหลังจาก:",
    COUNT_DOWN_TIME_FINISH_JOB: "งานจะจบหลังจาก {{time}}",
    FINISH: "สมบูรณ์",
    DURATION_HOUSE: "{{duration}} ห้อง : {{area}}",
    APARTMENT: "อพาร์ตเมนต์ / คอนโด",
    HOME: "บ้าน / ทาวน์เฮาส์",
    VILLA: "คฤหาสน์",
    HOTEL: "โรงแรม",
    DOG: "สุนัข",
    CAT: "แมว",
    REQUIREMENTS_COOKING: "ทำอาหาร",
    REQUIREMENTS_IRON: "รีดผ้า",
    REQUIREMENTS_2_SHOTS_VACCINE: "ได้รับวัคซีนครบ 2 เข็ม",
    REQUIREMENTS_NEGATIVE_TEST_COVID: "ผลตรวจหาเชื้อโควิด-19 เป็นลบ ภายใน 7 วัน",
    REQUIREMENTS_BRING_TO_TOOLS: "รวมอุปกรณ์ทำความสะอาด",
    CALL_WITH_PHONE_NUMBER: "โทรตามหมายเลขโทรศัพท์",
    CALL_WITH_BTASKEE_APP: "โทรออกโดยใช้แอป bTaskee",
    ACCEPTED_SUCCESS: "รับงานสำเร็จ",
    ACCEPTED_TASK_WAITING_SUCCESS: "คุณได้กดรอรับงานนี้แล้ว กรุณารอลูกค้ายืนยันอีกครั้ง",
    PAYMENT_METHOD_CASH: "เงินสด",
    PAYMENT_METHOD_TRANSFER: "ชำระเงินเรียบร้อย",
    MY_TASK_EMPTY: "ยังไม่มีงานในวันนี้",
    NEW_TASK_EMPTY: "ยังไม่มีงานใหม่ในตอนนี้",
    BUTTON_TRANSLATE_NOTE: "แปล",
    NOTES_TITLE: "หมายเหตุ",
    BUTTON_DONE: "สมบูรณ์",
    NUMBER_OF_TASK: "{{number}} งาน",
    BUTTON_GO_TO_DATE: "วันนี้",
    NUMBER_ACCEPTED_TASK: "จำนวนคนที่กำลังรอรับงานนี้: ",
    TITLE_CANCEL_TASK: "ยกเลิกงาน",
    BUTTON_CANCEL: "ยกเลิก",
    BUTTON_NO: "ย้อนกลับ",
    CONFIRM_CANCEL_TEXT: "คุณแน่ใจหรือไม่ว่าต้องการยกเลิกงานนี้?",
    CANCEL_TASK_REASON_NEARBY_TASK_PLACE: "มาถึงที่ทำงานแล้ว แต่พยายามติดต่อลูกค้าไม่ได้",
    CANCEL_TASK_REASON_SO_FAR_AWAY: "พลาดรับงานไกลเกินไป",
    CANCEL_TASK_REASON_WRONG_DATE: "ดูวันที่ผิด ไปทำไม่ได้",
    CANCEL_TASK_OTHER_REASON: "เหตุผลอื่น",
    CANCEL_TASK_REASON_TEXT: "กรุณาเลือกเหตุผลที่คุณต้องการยกเลิกงานนี้",
    CANCEL_REASON_IS: "เหตุผลการยกเลิกงาน:",
    CANCEL_FREE: "ค่าธรรมเนียม",
    NOTE_CANCEL_TASK: "ถ้าคุณยกเลิกงานนี้ ค่าปรับจะถูกหักในบัญชีหลักของคุณโดยอัตโนมัติ",
    PLACEHOLDER_TEXT_INPUT: "กรุณาระบุเหตุผลที่ต้องการลบบัญชี",
    TITLE_MODAL_CALL: "โทร",
    PREMIUM_TASK: "บริการพรีเมียม",
    TASK_FROM_SUBSCRIPTION: "งานแพคเกจรายเดือน",
    POP_UP_DRAW_TASK_TXT: "ความน่าเชื่อถือของคุณจะลดลง คุณแน่ใจใช่หรือไม่ที่จะถอนตัวจากงานนี้?",
    CANCELED: "ยกเลิก",
    DONE: "Done",
    CANCELED_BY_TASKER: "คุณได้ยกเลิกงานนี้",
    CANCELED_BY_ASKER: "ลูกค้ายกเลิกงานนี้",
    CANCELED_REASON: "เหตุผล",
    NUMBER_OF_DINER: "จำนวนคนรับประทาน: ",
    NUMBER_OF_DISH: "จำนวนจาน",
    TASTE: "รสชาติ: ",
    EATING_TIME: "เวลาทานอาหาร: ",
    BAC: "ฝั่งเหนือ",
    TRUNG: "ฝั่งกลาง",
    NAM: "ฝั่งใต้",
    FRUIT_DESERT: "ผลไม้",
    GO_MARKET: "ไปตลาด",
    DISH_WAITING: "กำลังรอ",
    CALL_CUSTOMER_TO_UPDATE_DISH: "รายการอาหารยังไม่ได้รับการอัปเดต หลังจากรับงานแล้วกรุณาโทรหาลูกค้า เพื่ออัพเดทรายการอาหาร",
    BUDGET_TO_MARKET: "เงินไปจ่ายตลาด: ",
    AIR_CONDITIONER_NUMBER: "{{t}} เครื่อง",
    ANY_CAPACITY: "ไม่จำกัดความจุ",
    CAPACITY_LESS_THAN: "ความจุน้อยกว่า {{t}} HP",
    CAPACITY_GREATER_THAN: "ความจุสูงกว่า {{t}} HP",
    CAPACITY_FROM_TO: "ความจุ {{t1}} HP ถึง {{t2}} HP",
    CAPACITY_LESS_THAN_BTU: "ความจุน้อยกว่า {{t}} BTU",
    CAPACITY_GREATER_THAN_BTU: "ความจุสูงกว่า {{t}} BTU",
    CAPACITY_FROM_TO_BTU: "ความจุ {{t1}} BTU ถึง {{t2}} BTU",
    TYPE_AC: "ประเภทเครื่องแอร์",
    QTY: "จำนวน",
    TASK_AIR_CONDITIONER: "รายละเอียด",
    HOSTEL_NAME: "ชื่อที่อยู่: ",
    TOTAL_AREA: "พื้นที่ทั้งหมด: {{t}}m²",
    IMAGE_TITLE: "รูปภาพ",
    NAME_ROOM: "ชื่อห้อง: {{t}}",
    AREA_ROOM: "พื้นที่: {{t}}m²",
    NOTE_ROOM: "หมายเหตุ: {{t}}",
    HOSTEL_DETAIL: "รายละเอียดห้อง",
    NUMBER_TASKER_ACCEPTED: "Tasker accepted: ",
    LIST_OF_TASK: "รายการ งาน",
    BUTTON_SEE_LIST: "รายละเอียดงาน",
    TITLE_LIST_CLEANING_TOOL: "รายการอุปกรณ์",
    OVERVIEW: "ทั่วไป",
    NUMBER_TOTAL_SOFA: "รวมจำนวนทั้งหมด: ",
    SOFA_TYPE: "ชนิด",
    MATTRESS: "ที่นอน",
    DRY_CLEANING: "ซักแห้ง",
    WASHING: "ซักน้ำ",
    CURTAIN: "ผ้าม่าน",
    CARPET: "พรม",
    BED: "ที่นอน",
    AREA_DISINFECTION: "พื้นที่: ",
    DISINFECTION_AREA_FROM_TO: "{{t1}}m² - {{t2}}m²",
    DISINFECTION_AREA_CUSTOM: "{{t}}m²",
    DISINFECTION_PROCEDURE: "ขั้นตอนกระบวนการพ่นฆ่าเชื้อโรค",
    DISINFECTION_PROCEDURE_CONTENT_TITLE: "ดำเนินการฉีดพ่นฆ่าเชื้อตามขั้นตอน",
    DISINFECTION_PROCEDURE_CONTENT_1: "1. เตรียมสารเคมีสำหรับฉีดพ่นฆ่าเชื้อ",
    DISINFECTION_PROCEDURE_CONTENT_2: "2. ปิดระบบระบายอากาศ ปิดเครื่องปรับอากาศ และปิดพัดลม",
    DISINFECTION_PROCEDURE_CONTENT_3: "3. ห้องนั่งเล่น : เพดาน พื้น ผนัง ตู้ ประตู โต๊ะ...",
    DISINFECTION_PROCEDURE_CONTENT_4: "4. ห้องนอน : เพดาน พื้น ผนัง ตู้ ใต้เตียง...",
    DISINFECTION_PROCEDURE_CONTENT_5: "5. ห้องครัว : เพดาน พื้น ผนัง โต๊ะทานอาหาร เก้าอี้ ชั้นวางของ...",
    DISINFECTION_PROCEDURE_CONTENT_6: "6. ห้องน้ำ : เพดาน พื้น ผนัง อ่างล้างจาน...",
    DISINFECTION_PROCEDURE_CONTENT_7: "7. ตรวจสอบงานอีกครั้งหลังทำเสร็จ",
    SHOPPING_TIME_LABEL: "เวลาซื้อของ: ",
    DURATION: "{{t}} ชั่วโมง",
    ESTIMATED_PURCHASE_AMOUNT: "จำนวนเงินที่คาดว่าลูกค้าจะซื้อสินค้า: ",
    SHOPPING_LIST: "รายละเอียดการซื้อ",
    AMOUNT_CHILD_LABEL: "จำนวนเด็ก",
    AGE_OF_CHILD: "อายุ",
    NUMBER_OF_CHILD: "คน",
    BUTTON_CONFIRM: "ตกลง",
    TET_BOOKING: "Songkran Booking tasks",
    YOUR_WORK: "งานของคุณ",
    YOU_ARE_LEADER: "คุณเป็นหัวหน้ากลุ่มสำหรับงานนี้",
    YOU_ARE_MEMBER: "คุณเป็นสมาชิกของกลุ่ม",
    WORK_ACCORDING_TO_ASSIGNMENT: "- ทำงานตามการมอบหมายของหัวหน้าทีม",
    PLEASE_CANCEL_TASK_BEFORE_A_TIME: "- หากคุณต้องการยกเลิกงานของคุณ โปรดติดต่อศูนย์บริการก่อนเริ่มทำงาน {{t}} ชั่วโมงเพื่อขอความช่วยเหลือ",
    RECEIVE_CASH_FROM_LEADER: "หลังจากทำงานเสร็จแล้ว ให้ติดต่อหัวหน้าเพื่อรับเงิน",
    OTHER_PAYMENT: "- หลังจากงานเสร็จสิ้น เงินจะถูกโอนไปยังบัญชีหลักของสมาชิกแต่ละคน",
    RECEIVE_CASH: "- หลังจากงานเสร็จ รับเงินสดจากลูกค้า และ แบ่งปันให้กับสมาชิกตามรายละเอียดด้านล่าง",
    DIVIDE_WORK: "- มอบหมายงานให้คุณ และ สมาชิก",
    NEED_TO_CONTACT_PARTNER: "- หัวหน้าทีมต้องติดต่อสมาชิกทีมก่อนที่จะเริ่มงาน หากสมาชิกคนใดไม่สามารถทำงานได้โปรดติดต่อศูนย์บริการเพื่อขอความช่วยเหลือ",
    TITLE_TASK_WAITING: "งานรอการยืนยัน",
    BUTTON_CHAT: "แชท",
    BUTTON_CALL: "โทร",
    MONEY_GET_MORE: 'ลูกค้าต้องชำระเงินสดเพิ่ม',
    TASK_WAS_CONFIRMED: "งานนี้มีคนรับแล้ว",
    SEE_MORE: "อ่านเพิ่ม",
    CANCEL_TASK_TASKER_SO_FAR_AWAY_TASK_PLACE: 'คุณไม่สามารถยกเลิกงานด้วยเหตุผลนี้  ระบบจะอนุญาตให้คุณยกเลิกงานได้หากคุณอยู่ใกล้กับสถานที่ทำงาน',
    CANCEL_TASK_LOCATION_NOT_FOUND_TEXT: 'ไม่ทราบตำแหน่งปัจจุบันของคุณ โปรดเปิดตำแหน่ง (GPS) จากนั้นรีสตาร์ทแอปพลิเคชั่นเพื่อยกเลิกงานต่อ',
    NEW_ASKER_NOTE: 'นี่คือลูกค้าใหม่ที่ใช้บริการคุณควรติดต่อลูกค้าก่อนที่จะไปทำงาน',
    TITLE_LIST_OF_TOOL_FOR_TASKER: "เครื่องมือทำความสะอาดต้องนำไป เวลาถึงบ้านลูกค้า",
    TITLE_ALERT_FAQ: "คำเตือน",
    MESSAGE_ALERT_FAQ_WAITING: "คุณจะไม่เสียค่าปรับถ้าต้องการถอนตัวจากงานนี้",
    MESSAGE_ALERT_FAQ_CONFIRMED: "หากคุณยกเลิกงานนี้ คุณจะต้องเสียค่าธรรมเนียมการยกเลิกตามข้อกำหนดขอบริษัท",
    ACCIDENT_INSURANCE: 'งานที่ได้รับการสนับสนุนโดย bCare',
    DESCRIPTION_CANCEL_TASK: "กรุณาเลือกรับงานอื่นๆ ที่คุณสามารถทำได้แทน",
    TODAY: "วันนี้",
    TOMORROW: "วันพรุ่งนี้",
    QR_CODE:"คิวอาร์โค้ดยืนยันตัวตน",
    COST_INCURRED: "เงินสนับสนุนจากบริษัท",
    DESCRIPTION_FOR_PROMOTION_LEADER: "เงินส่วนนี้จะถูกแบ่งอย่างเท่ากัน ไปยังบัญชีโปรโมชันของสมาชิกในทีม",
    MONEY_GET_MORE_MEMBER: "เงินส่วนนี้จะได้รับจากหัวหน้าทีม",
    PAYMENT_MOTHOD_BANKER: "บัญชีธนาคาร",
    PAYMENT_MOTHOD_CASH: "เงินสด",
    PAYMENT_MOTHOD_PROMOTION: "โปรโมชัน",
    MONEY_GET_MORE_LEADER: "คุณจะต้องแบ่งเงินส่วนนี้ให้สมาชิกในทีมอย่างเท่าๆกัน",
    SOFA_CLEANING_TYPE_MORE: "มากกว่า 6 ที่นั่ง",
    CURTAIN_CHOOSE_SERVICE_ON_SITE: "แบบไม่ถอดผ้าม่าน",
    CURTAIN_CHOOSE_SERVICE_OFF_SITE: "แบบถอดผ้าม่าน",
    WORKED_FOR_ASKER: "คุณเคยทำงานให้ลูกค้าท่านนี้",
    ASKER_OFTEN_USE_SERVICE: "ลูกค้าที่ใช้บริการเป็นประจำ",
    TIP: "Tip:",
    CANCEL_FEE: "ค่าธรรมเนียมการยกเลิกงาน ",
    MORNING: "เช้า",
    AFTERNOON: "กลางวัน",
    EVENING: "เย็น",
    VACUUMING_OFFICE_CARPETS: "การดูดฝุ่นพรมในสำนักงาน",
    CLEANING_GLASSES: "ทำความสะอาดกระจก",
    WM_TYPE: "ซักผ้าด้วยเครื่อง",
    WM_SERVICES: "บริการ",
    NUMBER_OF_WM: "จำนวนที่ต้องการซัก",
    CALL_WITH_MEMBER: "ติดต่อ",
    CALL_WITH_LEADER: "ติดต่อหัวหน้าทีม",
  },
  HOME: {
    TAB_HOME: "หน้าหลัก",
    TAB_BENEFIT: "สิทธิประโยชน์",
    TAB_ACCOUNT: "บัญชี",
    BTASKEE: "bTaskee",
    TAB_MY_TASK: "งานของฉัน",
    TAB_NEW_TASK: "งานใหม่",
    TAB_NOTIFICATION: "กล่องข้อความ",
    NET_DISCONNECTED: "ไม่สามารถเชื่อมต่อได้ โปรดตรวจสอบอินเตอร์เน็ตของท่าน",
    NET_ONLINE: "เชื่อมต่อสำเร็จ",
  },
  NOTIFICATION_CHAT: {
    TAB_TITLE: "แชท",
    NOTHING: "ยังไม่มีข้อความใหม่",
  },
  NOTIFICATION_SYSTEM: {
    TAB_TITLE: "แจ้งเตือน",
    INBOX: "กล่องข้อความ",
  },
  TAB_BENEFIT: {
    TRAINING_PROGRAM: "โปรแกรมฝึกอบรม",
    MONTHLY_REWARD: "เงินโบนัส",
    BREWARD: "bReward",
    COMMUNITY: "ชุมชน",
    BCARE: "bCare",
    INSURANCE: "ประกัน",
    LEVEL_MONTHLY_REWARD: "คุณต้องทำงานจำนวน {{t}} ชั่วโมงเพื่อที่จะได้รับโบนัสในเดือนถัดไป",
    MAX_LEVEL: "ขอแสดงความยินดีด้วย คุณรับงานถึงระดับสูงสุดของโบนัสในเดือนนี้ ",
    HOURS_OF_AWARDS: "{{t}} ชั่วโมง ",
    PROMOTION: "โปรโมชัน",
    BREWARD_DETAIL: "รางวัลของฉัน",
    LABEL_REWARD_INFO: "รายละเอียดรางวัล",
    LABEL_CONDITION: "เงื่อนไข",
    BUTTON_REDEEM: "แลกคูปอง",
    NUMBER_POINT: "bPoint",
    TITLE_ALERT_CONFIRM_REDEEM: "ยืนยันการแลกคูปอง",
    CONTEXT_ALERT_CONFIRM_REDEEM: "แลกคูปอง",
    BUTTON_CONFIRM: "ตกลง",
    BUTTON_LATER: "ไว้ก่อน",
    FREE: "ฟรี",
    REDEEM_SUCCESS: "แลกคูปองสำเร็จ",
    NEW_GIFT: "รางวัลใหม่",
    USED_GIFT: "ใช้แล้ว",
    LIST_INCENTIVE_EMPTY: "ยังไม่มีรางวัล",
    MY_GIFT: "รางวัลของฉัน",
    EXPIRED_ON: "หมดอายุเมื่อ:",
    EXPIRED: "หมดอายุ",
    USED: "ใช้แล้ว",
    DETAIL_REWARD_EMPTY: "ยังไม่มีโปรโมชันในตอนนี้ ",
    LABEL_SAVE_SUCCESS: "ความสำเร็จ",
    MONEY: "{{currency}}{{cost}}",
    MONTHLY_REWARD_DETAIL: "รายละเอียดรางวัล",
    MORE_HOURS:"คุณต้องรับงานให้มากขึ้น",
    MORE_REWARD:"รางวัลถัดไป",
    TIME_WORK_IN_MONTH:"จำนวนชั่วโมงที่คุณทำงานในเดือนนี้:",
    REWARD_WORD_IN_MONTH:"รางวัลที่คุณได้รับในเดือนนี้:",
    HOURS:"ชั่วโมง",
    DAY_LEFT:"เหลือเวลาอีก:",
    DAY:"วัน",
    NEXT_STEP:"ขั้นต่อไป:",
    VIEW_DETAIL:"รายละเอียดรางวัล",
    DETAIL_REWARD:"รายละเอียดรางวัล",
    NEXT_REWARD: "ระดับถัดไป",
    TRAINING: "บทที่ number",
    COMMUNITY_CONTENT: "แลกเปลี่ยนและแบ่งปันประสบการณ์กับพี่บีคนอื่นๆทั่วประเทศ",
    BREWARD_CONTENT: "รับ `ของขวัญมากมาย` เมื่อคุณได้รับ bPoint เพื่อนำไปแลก bRewards",
    TRAINING_CONTENT: "มาพัฒนาคุณภาพของเราในการอบรมกับ bTaskee กันเถอะ!",
    BCARE_CONTENT: "เมื่อคุณไม่สามารถจัดการกับความเสี่ยงได้ ให้ bCare ได้ช่วยเหลือคุณ",
    PREMIUM_CONTENT: "มาพยายามกันให้เป็น Tasker ระดับพรีเมียมกันเถอะ!",
    EMPTY_DATA: "กรุณากลับมาอีกครั้งหลังจากเปิดระบบเรียบร้อยแล้ว เพื่อรับประโยชน์และสิทธิพิเศษเฉพาะคุณ",
    SEARCH: "ค้นหา",
    SEARCH_VOUCHER: "ค้นหาของรางวัล",
    ACCOUNT_LOCK: "ถูกล็อค"
  },
  TAB_ACCOUNT: {
    PROFILE: "โปรไฟล์",
    FINANCE: "การเงิน",
    WEEKLY_REPORT: "รายงานประจำสัปดาห์",
    HISTORY_INCOME: "ประวัติรายได้",
    INCOME: "รายได้ของคุณ",
    SERVICES: "บริการ",
    DISTRICTS: "พื้นที่",
    LEVEL: "ระดับ",
    PREMIUM: "Premium",
    TITLE_QA_CODE: "คุณต้องรับงานให้มากขึ้น",
    YOUR_REFERRAL_CODE: "รหัสแนะนำเพื่อนของคุณ",
    COPY: "คัดลอกy",
    LABEL_COPY: "คัดลอกสำเร็จ",
    SEE_INFORMATION: "ข้อมูลเพิ่มเติม",
    LOGOUT: "ออกจากระบบ",
    LOGOUT_CONFIRM: "คุณแน่ใจว่าต้องการออกจากระบบใช่ไหม?",
    LEVEL_1: "มือใหม่",
    LEVEL_2: "มืออาชีพ",
    HOLDING_ACCOUNT: "เงินสำรองการรับงาน ",
    MAIN_ACCOUNT: "บัญชีหลัก",
    PROMOTION_ACCOUNT: "บัญชีโปรโมชัน: ",
    INCOME_THIS_WEEK: "รายได้ของคุณในสัปดาห์นี้",
    COMPLETED_TASK: "งานที่ทำเสร็จทั้งหมด",
    INCOME_TOTAL: "รายได้รวมทั้งหมด",
    INCOME_IN_MONTH: "รายได้ของคุณในเดือนนี้",
    TOPUP: "เติมเงิน",
    WITHDRAW: "ถอนเงิน",
    AMOUNT_WITHDRAW: "อยู่ในระหว่างดำเนินการถอนเงิน",
    AMOUNT_WITHDRAW_NOTE: "ระบบกำลังประมวลผลคำขอถอนเงินของคุณ",
    TRANSACTION_HISTORY: "ประวัติการทำรายการ",
    AMOUNT: "จำนวน",
    BALANCE: "ยอดเงินคงเหลือ",
    WITHDRAW_NOTE: "หมายเหตุ: คุณต้องมีเงินขั้นต่ำจำนวน {{amount}} {{currency}} เหลือในบัญชีของท่าน สำหรับรับงานครั้งถัดไป",
    NEXT: "ถัดไป",
    CONFIRMATION: "แน่ใจ",
    CONFIRMATION_WITHDRAW: "คุณแน่ใจหรือไม่ว่าต้องการถอนเงินออกจากบัญชีนี้?",
    BANK_ACCOUNT: "บัญชี",
    FMAIN_ACCOUNT_NOTE: "คือ บัญชีที่แสดงยอดปัจจุบันที่คุณสามารถใช้เพื่อรับงานหรือถอนเงินเมื่อถึงเกณฑ์ที่กำหนด",
    PROMOTION_ACCOUNT_NOTE: "คือบัญชีสำหรับสนับสนุนแม่บ้าน โดยจำนวนเงินที่ได้รับจะมาจาก โบนัสการชวนเพื่อน, โบนัสรายเดือน, งานที่ลูกค้าใช้โค้ดส่วนลดในการจองงาน เงินบัญชีนี้ใช้เพื่อการรับงานเท่านั้น และไม่สามารถถอนออกได้",
    ON_HOLD_ACCOUNT: "เงินสำรองการรับงาน",
    ON_HOLD_ACCOUNT_NOTE: "หรือเงินที่อยู่ระหว่างการรอหักจากบัญชี  เงินส่วนนี้จะถูกหักจริงก็ต่อเมื่อคุณทำงานเสร็จสมบูรณ์แล้ว โดยจะหักจากบัญชีโปรโมชันก่อน หากเงินในบัญชีโปรโมชันไม่เพียงพอ จะถูกหักจากบัญชีหลักแทน หากคุณกำลังรอรับงานที่รอลูกค้าเลือก เงินส่วนนี้จะถูกสำรองไว้ เพื่อป้องกันคุณรับงานเกินจำนวนเงินที่มีในบัญชีหากลูกค้าได้เลือกคุณ",
    PAYOUT_NAME: "คำร้องขอถอนเงิน",
    PAYOUT_WAIT: "อยู่ในขั้นตอนการถอนเงิน",
    PAYOUT_PAID: "การถอนเงินเสร็จสมบูรณ์",
    PAYOUT_CANCELED: "ยกเลิก",
    PAYOUT_REJECTED: "ถูกปฏิเสธ",
    PAYOUT_SUCCESS: "คำขอถอนเงินสำเร็จ",
    MONTH: "เดือน",
    WEEK: "สัปดาห์",
    STAR: "ดาว",
    BELOW: "ต่ำกว่าเกณฑ์มาตราฐาน",
    TASK: "งาน",
    INCREASE_TASK: "คุณรับงานมากกว่าสัปดาห์ที่แล้ว {{task}} งาน :)",
    DECREASE_TASK: "คุณรับงานลดลงจากสัปดาห์ที่แล้ว {{task}} งาน  :(",
    GOOD_REVIEW: "รีวิวที่ดีของคุณ",
    BAD_REVIEW: "คุณควรพัฒนาคุณภาพเพิ่มขึ้น",
    TASK_HISTORY: "ประวัติงาน",
    INFORMATION: "รายละเอียด",
    EMPTY_TASK_IN_MONTH: "ไม่มีงานในเดือนนี้",
    EMPTY_TRANSACTION_IN_MONTH: "ไม่มีรายการในเดือนนี้",
    LIST_OF_EMPLOYEE: "รายละเอียดพนักงาน",
    REVIEW: "รีวิว",
    ERROR_ON_HOLD_ACCOUNT_WHEN_WITHDRAW: "คุณมี 1 รายการที่กำลังรอถอนเงิน",
    TRANSACTION: "การทำธุรกรรม",
    PAYOUT: "คำร้องขอถอนเงิน",
    LABEL_TRANSACTION_TAB: "ล่าสุด",
    EMPTY_TRANSACTION: "คุณยังไม่มีคำร้องขอถอนเงิน",
    EMPTY_PAYOUT: "คุณยังไม่มีรายการธุรกรรม",
    TITLE_CHECK_NOTIFICATION: "ทดสอบการแจ้งเตือน",
    BUTTON_CHECK_NOTIFICATION: "ส่งการแจ้งเตือน",
    TITLE_TEST_NOTIFICATION: "แจ้งเตือนกำลังทำงานดี",
    INFO_TEST_NOTIFICATION: 'แอปพลิเคชันจะปิดโดยอัตโนมัติเพื่อทดสอบการแจ้งเตือน คุณต้องการดำเนินการต่อหรือไม่?',
    TITLE_CARD_SHARE: "แชร์",
    CONTENT_CARD_SHARE: "แชร์แอพลิเคชันเพื่อรับของขวัญ",
    BUTTON_VIEW_MORE: "ดูรายละเอียดเพิ่มเติม",
    TEXT_QR: "กรุณาเตรียมคิวอาร์โค้ดของท่านเพื่อยืนยันตัวตนของท่านกับลูกค้า",
    LABEL_DELETE_ACCOUNT: "ลบบัญชี",
    TEXT_DELETE_ACCOUNT: "คุณต้องการจะลบบัญชีใช่ไหม?",
    TITLE_RESTART_APP: "ทดสอบการทำงานของแอปพลิเคชัน",
    BUTTON_RESTART_APP: "เริ่มตอนนี้",
    TEXT_RESTAR_APP: "คุณต้องการรีสตาร์ทแอปพลิเคชัน?",
    NUMBER_ACCEPT_TASK: "ปัจจุบันมี {{numberTasks}} งาน",
    NUMBER_OF_POINT_LABEL: "Preferential point",
    NUMBER_OF_POINT: "{{t}} points"
  },
  CHAT: {
    TRANSLATING: "แปลภาษา ...",
    TITLE: "แชท",
    PREPARED_MESSAGE_THANK: "ขอบคุณค่ะ",
    PREPARED_MESSAGE_THANK_2: "ขอบคุณครับ",
    PREPARED_MESSAGE_WAIT_ASKER: "ฉันรอคุณ 20 นาทีแล้ว แต่ยังไม่สามารถติดต่อคุณได้ ฉันขออนุญาตยกเลิกงานนะคะ!",
    GPS_NOT_FOUND: "ค้นหาพิกัดไม่สำเร็จ!",
    TYPE_A_MESSAGE: "ใส่ข้อความ",
    SERVICE_REQUEST_GPS: "กรุณาเปิดใช้งาน GPS เพื่อใช้ฟังชันนี้!",
    PT1_MAP_POPUP_PERMISSION_REQUEST_GPS_CLOSE: "ปิด",
    OPEN_SETTINGS: "เปิดตั้งค่า",
    MODAL_CONFIRM_SHARE_LOCATION_TITLE: "คุณต้องการแชร์ตำแหน่งที่ตั้งปัจจุบันใช่ไหม?",
    PREPARED_MESSAGE_CONFIRMATION: "สวัสดีค่ะ ฉันได้รับงานของคุณแล้ว ฉันจะเดินทางไปทำงานให้ตรงเวลาค่ะ",
    PREPARED_MESSAGE_CONFIRMATION_2: "สวัสดีค่ะ ฉันได้รับงานของคุณแล้ว ฉันจะเดินทางไปทำงานให้ตรงเวลาค่ะ",
    PREPARED_MESSAGE_REQUIRE_ADDRESS_EXACTLY: "โปรดบอกที่อยู่ ที่ชัดเจนของสถานที่ทำงานด้วยค่ะ",
    PREPARED_MESSAGE_REQUIRE_ADDRESS_EXACTLY_2: "โปรดบอกที่อยู่ ที่ชัดเจนของสถานที่ทำงานด้วยค่ะ",
    PREPARED_MESSAGE_COMING: "ฉันกำลังอยู่ระหว่างทางไปบ้านคุณ กรุณารอรับการติดต่อกลับด้วยค่ะ",
    PREPARED_MESSAGE_COMING_2: "ฉันกำลังอยู่ระหว่างทางไปบ้านคุณ กรุณารอรับการติดต่อกลับด้วยค่ะ",
    PREPARED_MESSAGE_WAITED_20_MINUTES: "ฉันรอคุณ 20 นาทีแล้ว แต่ยังไม่สามารถติดต่อคุณได้ ฉันขออนุญาตยกเลิกงานนะคะ",
    PREPARED_MESSAGE_WAITED_20_MINUTES_2: "ฉันรอคุณ 20 นาทีแล้ว แต่ยังไม่สามารถติดต่อคุณได้ ฉันขออนุญาตยกเลิกงานนะคะ",
    PREPARED_MESSAGE_WAIT_20_MINUTES: "สวัสดีค่ะฉันมาถึงแล้ว แต่ไม่สามารถติดต่อคุณได้ ฉันสามารถรอคุณได้อีก 20 นาที หากยังไม่สามารถติดต่อคุณได้ ฉันต้องขออนุญาตยกเลิกงานนี้ ขอบคุณค่ะ",
    PREPARED_MESSAGE_WAIT_20_MINUTES_2: "สวัสดีค่ะฉันมาถึงแล้ว แต่ไม่สามารถติดต่อคุณได้ ฉันสามารถรอคุณได้อีก 20 นาที หากยังไม่สามารถติดต่อคุณได้ ฉันต้องขออนุญาตยกเลิกงานนี้ ขอบคุณค่ะ",
    PREPARED_MESSAGE_AT_RECEPTION: "ขณะนี้ฉันกำลังรอคุณอยู่ที่แผนกต้อนรับ โปรดลงมารับฉันด้วยค่ะ",
    PREPARED_MESSAGE_AT_RECEPTION_2: "ขณะนี้ฉันกำลังรอคุณอยู่ที่แผนกต้อนรับ โปรดลงมารับฉันด้วยค่ะ",
    LABEL_CHAT_WITH_BTASKEE: "แชทกับเจ้าหน้าที่ "
  },
  TRAINING_INPUT: {
    TITLE: "ทดสอบ",
    LOADING_TITLE: "กำลังรับข้อมูล",
    INSTRUCTION_PASS_TEST: "หมายเหตุ : การทำแบบทดสอบจะต้องผ่าน 80% ขึ้นไป โปรดตั้งใจอ่านและทำแบบทดสอบก่อนกดส่งคำตอบ",
    ERROR: "ไม่สามารถตรวจสอบข้อมูลได้ โปรดลองอีกครั้ง!",
    START: "เริ่ม",
    RELOAD: "กรุณาลองอีกครั้ง!",
    FINISH: "ส่งข้อสอบ",
    ACCEPT_TEST_CONFIRMATION: "คุณได้อ่านข้อมูลทั้งหมดครบถ้วน และต้องการทำแบบทดสอบนี้ใช่ไหม?",
    FINISH_TEST_CONFIRMATION: "คุณแน่ใจ?",
    FAILD: "คุณไม่ผ่านแบบทดสอบ กรุณาติดต่อศูนย์ให้ความช่วยเหลือ",
    RESULT_TEST_FAILD: "คุณยังไม่ผ่านการทดสอบนี้ คุณเหลืออีก {{t}} ครั้งในการทำใหม่อีกครั้ง โปรดตั้งใจทำแบบทดสอบอีกครั้ง",
    RESULT_TEST_FAILD_LIMITED: "คุณไม่ผ่านการทำดสอบ หากต้องการทราบข้อมูลเพิ่มเติม กรุณาติดต่อเจ้าหน้าที่",
    SEE_RESULT: "สรุปคะแนน",
    GRADING_TEST: "กำลังตรวจสอบคะแนน... กรุณารอสักครู่!",
    QUIT_TEST: "ออกจากแบบทดสอบ",
    TRAINING_TASKER_PASS_TITLE: "ยินดีต้องรับสู่ bTaskee",
    PREPARE_PROFILE: "กำรุณาเตรียมเอกสาร ดังนี้:",
    UNVERIFIED_TASKER_PROFILE_1: "เอกสารประวัติการทำงาน  1 ชุด",
    UNVERIFIED_TASKER_PROFILE_2: "บัตรประชาชน 2 ชุด",
    UNVERIFIED_TASKER_PROFILE_3: "สำเนาทะเบียนบ้าน 1 ชุด",
    UNVERIFIED_TASKER_PROFILE_4: "เอกสารตรวจประวัติอาชญากรรม 1 ชุด",
    NOTE_FOR_UNVERIFIED_TASKER_PROFILE: "เอกสารต้องได้รับการรับรองจากสำนักงานตำรวจแห่งชาติและมีอายุไม่เกิน 6 เดือนนับจากวันที่ออก",
    APPLY_YOUR_PROFILE_AT_COMPANY_NOTE: "หลังจากนั้นให้เข้ามาส่งเอกสารและกรอกใบสมัครที่บริษัทฯ ด้วยตัวเอง",
    TIME_TO_APPLY: "ระยะเวลาในการส่งเอกสาร",
    MORNING_TO_APPLY: "ช่วงเช้า:",
    AFTERNOON_TO_APPLY: "ตอนบ่าย:",
    TIME_MORNING: "09:00 น",
    TIME_AFTERNOON: "14:00 น",
    ARRIVE_APPLY_LATE_NOTE: "หากคุณมาสาย คุณจะต้องทำการนัดและมาใหม่ในวันถัดไป",
    UNVERIFIED_TASKER_SUBMITION_ADDRRESS: "ที่อยู่สำหรับจัดส่งเอกสาร:",
    PHONE: "เบอร์โทรศัพท์: {{t}}",
    CALL_SUPPORT_FOR_MORE_DETAIL: "โปรดติดต่อเจ้าหน้าที่ หากคุณต้องการรายละเอียดเพิ่มเติม",
    CALL_WITH_HR: "โปรดติดติดต่อเจ้าหน้าที่เพื่อทำการนัดหมายก่อนเข้ามาอบรม เพื่อให้เจ้าหน้าที่สามารถลงจองรอบอบรมของท่าน",
    DESCRIPTION_PLAY_VIDEO: "มาจำบทเรียนกันดีกว่าด้วยบทสรุปด้านล่าง",
    NEXT: "ดำเนินการต่อ",
    DONE: "สมบูรณ์",
    TRAINING_PROGRAM: "โปรแกรมการฝึกอบรม",
    READING_TIME: "เวลาการเรียน:",
    BY_MINUTUES: "นาที",
    TRAINING: "บทเรียน",
    TRAINING_DESCRIPTION: "โปรดเลือกสถานที่ที่เงียบสงบและมีเวลาว่างเพียงพอ เพื่อให้ได้ประโยชน์อย่างสูงสุดในการเรียนรู้ และสามารถโฟกัสกับบทเรียนได้อย่างเต็มที่",
    TEST: "ทำแบบทดสอบ ",
    TEST_DESCRIPTION: "โปรดพยายามอย่างเต็มที่ในการอ่านและทำความเข้าใจบทเรียนอย่างละเอียด เพื่อให้สามารถทำแบบทดสอบได้อย่างมีประสิทธิภาพ",
    PASS: "ผ่าน",
    FAILED: "ไม่ผ่าน",
    REMAINING_TIME: "จำนวนการทำแบบทดสอบที่เหลือ",
    LESSON: "บทเรียน {{t}}",
    TRAINING_DETAIL_TITLE: "รายละเอียดบทเรียน",
    SUMMARY: "สรุป",
    FINISH_TEST_SUCCESS: "ขอแสดงความยินดีด้วยคุณทำแบบทดสอบครบแล้ว",
    TEST_FAILD_LIMITED: "คุณไม่ผ่านการทำแบบทดสอบ",
    TEST_AGAIN: "ทำใหม่อีกครั้ง",
    COME_BACK_LATER: "กลับมาทำใหม่ภายหลัง",
    NUMBER_OF_CORRECT_ANSWER: "จำนวนคำตอบที่ถูกต้อง: ",
    TAKE_THE_TEST: "ทำแบบทดสอบตอนนี้!",
    INFO_TEST: "ผลลัพธ์: {{t1}}/{{t2}}",
    DES_SEE_TEST: "แบบทดสอบจะเปิดหลังจากดูวิดีโอ",
    CORRECT: "ถูกต้อง",
    WRONG: "ผิด",
  },
  TRAINING_PREMIUM: {
    TITLE: "การฝึกอบรมเพื่อนพัฒนาคุณภาพที่สูงขึ้น",
    SHARE: 'แชร์',
    TASKER_PREMIUM_TITLE: 'ใบประกาศ',
    TASKER_PREMIUM_SUB_TITLE: 'ผู้เชี่ยวชาญ',
    CONTENT: "ข้อบังคับเกี่ยวกับการได้รับใบกระกาศนีย์บัตร",
    PASS_TITLE: "ยินดีด้วยคุณผ่านแบบทดสอบแล้ว",
    REGULATIONS_TASKER_PREMIUM: 'การฝึกอบรมเพื่อนพัฒนาคุณภาพที่สูงขึ้น',
    WITHDRAW_TASKER_PREMIUM_TITLE: 'กฎระเบียบการดำเนินงานสำหรับผู้เชี่ยวชาญ',
    REGULATIONS_TASKER_PREMIUM_1: 'ปฏิบัติตามข้อกฏและข้อตกลงตามเอกสารการร่วมมือที่ได้เซนต์ยอมรับก่อนร่วมงานกับทาง bTaskee',
    REGULATIONS_TASKER_PREMIUM_2: 'Senior collaborators will be **DISCLOSED** for violating the regulations on:',
    REGULATIONS_TASKER_PREMIUM_2_1: "มีการต่อรองการทำงานกับลูกค้าของ bTaskee นอกระบบ",
    REGULATIONS_TASKER_PREMIUM_2_2: 'การละเมิดกฎเกณฑ์เรื่องเครื่องแบบและมารยาท',
    REGULATIONS_TASKER_PREMIUM_2_3: 'คุณภาพการทำงานไม่คงที่และไม่ได้รับมาตราฐานของบริษัท',
    REGULATIONS_TASKER_PREMIUM_2_4: 'มีพฤติกรรมที่ไม่เหมาะสม',
    REGULATIONS_TASKER_PREMIUM_3: "เมื่อถูกยกเลิกใบอนุญาตการรับงานพรีเมี่ยม คุณจะได้รับผลกระทบดังนี้: ",
    REGULATIONS_TASKER_PREMIUM_3_1: 'ไม่สามารถรับงานพรีเมี่ยมได้',
    REGULATIONS_TASKER_PREMIUM_3_2: 'คุณไม่ได้รับการอนุญาตให้เข้าร่วมโปรแกรมผู้เชี่ยวชาญ',
    REGULATIONS_TASKER_PREMIUM_4: 'Every day will check and:',
    REGULATIONS_TASKER_PREMIUM_4_1: 'ถอนสิทธิ์ของ Tasker ในกรณีที่ฝ่าฝืนกฎระเบียบหรือเงื่อนไขของบริษัท bTaskee ',
    REGULATIONS_TASKER_PREMIUM_4_2: 'ออกใบอนุญาตให้ใหม่อีกครั้งหาก Tasker มีการพัฒนาและปรับปรุงคุณสมบัติได้ตรงตามเงื่อนไขที่กำหนด',
    CONDITION_TASKER_PREMIUM_TITLE: 'เงื่อนไขการอัพเกรดเป็นแม่บ้านระดับพรีเมืยม',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_1: 'มีเระดับดาวเฉลี่ยสูงมากกว่าหรือเท่ากับ 4.80',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_2: 'มีลูกค้าที่ตั้งเป็นแม่บ้านคนโปรดไม่น้อยกว่า 10 คน',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_3: 'มีอุปกรณ์ที่ครบถ้วนตามมาตรฐานของ bTaskee',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_4: 'มีเครื่องดูดฝุ่น',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_5: 'มีกระเป๋าเป้ bTaskee',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_6: 'ได้ทำงานบนระบบ bTaskee อย่างน้อย 200 งาน',
    TITLE_TASKER_PREMIUM: "อบรมตอนนี้",
    LABEL_START_NOW: "อัพเกรดเป็นพรีเมียม",
  },
  INTRO_APP: {
    BUTTON_START: "เริ่ม",
    TITLE: "สิทธิประโยชน์ที่คุณได้รับจาก bTaskee",
    LEARN_MORE: "อ่านเพิ่มเติม",
    START_WORKING: "มาเปลี่ยนเวลาว่างของคุณ ให้เป็นโอกาสในการสร้างรายได้กันเถอะ",
    ALREADY_ACCOUNT: "คุณมีบัญชีแล้วหรือยัง?",
    FLEXIBLE_TIME: "มีเวลาที่ยืนหยุ่น",
    HIGH_INCOME: "รายได้สูง",
    COMMUNITY_REWARD: "ชุมชนแลกเปลี่ยนความรู้ และ รางวัลมากมาย",
    FLEXIBLE_TIME_1: "มีเวลาการทำงานที่ยืดหยุ่นขึ้นอยู่กับคุณ",
    FLEXIBLE_TIME_2: "เปลี่ยนเวลาว่างของคุณให้เป็นรายได้",
    HIGH_INCOME_1: "ได้เงินมากกว่า 25,000 บาท ถ้าคุณขยันรับงาน ยื่งทำมากยิ่งได้มาก",
    COMMUNITY_REWARD_1: "พื้นที่ที่คุณสามารถเชื่อมต่อ แบ่งปัน ช่วยเหลือ และสร้างความภาคภูมิใจในอาชีพด้วยงานบ้าน",
    COMMUNITY_REWARD_2: "Collaborators are entitled to a support policy of up to VND 100 million.",
    HIGH_INCOME_TITLE_TH:"รายได้ดี",
    HIGH_INCOME_CONTENT_TH:"ทำงานดี รับงานบ่อย สามารถได้ค่าตอบแทนมากกว่า 30,000฿/เดือน ยังไม่รวมเงินทิปและโบนัสอีกนะ!",
    FLEXIBLE_TIME_TITLE_TH:"เป็นเจ้านายตัวเอง",
    FLEXIBLE_TIME_CONTENT_TH:"ชีวิตที่เลือกได้! ไม่ต้องเป็นลูกน้องใคร อยากทำงานกี่วัน กี่โมงก็เลือกได้ตามใจเรา~",
    COMMUNITY_REWARD_TITLE_TH:"มีเวลาให้คนที่คุณรัก",
    COMMUNITY_REWARD_CONTENT_TH:"ครอบครัวคือดวงใจ การรับงานกับ bTaskee ทำให้มีเวลาอยู่กับครอบครัวและตัวเองมากยิ่งขึ้น!",
    FLEXIBLE_TIME_ID:"ชีวิตที่เลือกได้! ไม่ต้องเป็นลูกน้องใคร อยากทำงานกี่วัน กี่โมงก็เลือกได้ตามใจเรา~",
    HIGH_INCOME_ID:"ทำงานดี รับงานบ่อย สามารถได้ค่าตอบแทนมากกว่า 30,000฿/เดือน ยังไม่รวมเงินทิปและโบนัสอีกนะ!",
    COMMUNITY_REWARD_ID:"ครอบครัวคือดวงใจ การรับงานกับ bTaskee ทำให้มีเวลาอยู่กับครอบครัวและตัวเองมากยิ่งขึ้น!"
  },
  SETTINGS: {
    SETTINGS: "การตั้งค่า",
    LANGUAGE: "ภาษา",
    NOTIFICATION: "การแจ้งเตือน",
    NOTIFICATION_TASK: "การแจ้งเตือนงาน",
    NOTIFICATION_ON: "เปิด",
    NOTIFICATION_OFF: "ปิด",
    FEE_SCHEDULE: "เวลาที่คุณสามารถทำงานได้",
    YOUR_WORKTIME: "เวลาที่สะดวกรับงาน",
    BUSY_TIME: "เวลาที่ไม่สะดวกรับงาน",
    REMIND: "เตือนฉันก่อนเวลา",
    MINUTE: "นาที",
    HOURS: "ชั่วโมง",
    MORNING: "เช้า",
    AFTERNOON: "กลางวัน",
    EVENING: "เย็น",
    UPDATE: "เปลี่ยนแปลง",
    NOTE_TASKER_UPDATE_SCHEDULE: "คุณสามารถเปลี่ยนแปลงตารางได้ 1 ครั้ง (ถ้าคุณต้องการเปลี่ยนแปลงมากกว่า 1 ครั้ง กรุณาติดต่อฝ่ายสนันสนุน bTaskee)",
    TEXT_VIBRATION:"มันจะสั่นเมื่อได้รับการแจ้งเตือนงานใหม่"
  },
  TOPUP: {
    MIN_COST_TOPUP: "จำนวนเงินฝากขั้นต่ำคือ:",
    INSTRUCTTION_NOTE: "หมายเหตุ: บัญชีของคุณจะได้รับการอัปเดตภายใน 24 ชั่วโมงหลังจากการโอนเงิน",
    BANK_TRANFER: "Ngân hàng:",
    BANK_INFO_ACCOUNT_HOLDER: "เจ้าของบัญชี:",
    BANK_INFO_ACCOUNT_NUMBER: "หมายเลขบัญชี:",
    BANK_INFO_TRANFER_CONTENT: "เนื้อหาของการถ่ายโอน:",
    BANK_INFO_CONTENT_SYNTAX: "ป้อนชื่อเต็มและหมายเลขโทรศัพท์ของคุณ",
    LBL_EX_DEPOSITE: "VD: Nguyễn Thị A 0123456789",
    NOTE_DEPOSIT_MONEY: "หมายเหตุ : เงินในบัญชีของท่านสามารถใช้สำหรับรับงานเท่านั้น ไม่สามารถใช้สำหรับค่าใช้จ่ายอื่นๆ เช่น ซื้อกระเป๋า , ซื้อชุดยูนิฟอร์ม ฯลฯ",
    SAVE_IMAGE: "บันทึกรูปภาพ",
    SAVE_IMAGE_SUCCESS: "บันทึกรูปภาพสำเร็จ",
    BTASKEE_THAILAND: "บีทีเอเอสเคอีอี (ไทยแลนด์)",
    METHOD: "ขั้นตอนการเติมเงิน",
    OPEN_BANK_APP: "เปิดแอพลิเคชันธนาคาร",
    SCAN: "สแกน",
    SELECT_PHOTO: "เลือกรูป",
    BUTTON_DONE: "เสร็จแล้ว",
    MIN_MONEY: "จำนวนเงินขั้นต่ำที่ฝากได้",
    MAX_MONEY: "จำนวนเงินสูงสุดที่คุณสามารถเติมเงินได้",
    IMAGE_DOWNLOAD_PERMISSTION: "กรุณาเปิดการอนุญาตให้เข้าถึงรูปภาพของท่าน",
    IMAGE_DOWNLOAD_PERMISSTION_MESS: "กรุณาเปิดการอนุญาตให้เข้าถึงรูปภาพของท่าน",
    COMING_SOON: "มาเร็ว ๆ นี้",
    NOTE:"บันทึก:",
    QR_CODE: "สแกนคิวอาร์โค้ด",
    NOTE_LABEL: "หมายเหตุ : ",
    QR_NOTE: "วิธีการเติมเงินผ่านคิวอาร์โค้ด?",
    STEP_1: "กดบันทึกรูปภาพคิวอาร์โค้ดลงมือถือ",
    STEP_2: "เปิดแอปฯธนาคาร",
    STEP_3: `ไปยังเมนู "สแกน" หรือ "สแกนจ่าย" จากนั้นกดที่ปุ่ม "รูปภาพ" ในหน้าสแกนเพื่อเลือกรูปคิวอาร์โค้ด ในมือถือของคุณ`,
    STEP_4: "กรุณาใส่จำนวนเงินที่คุณต้องการเติมเข้าบัญชี โปรดทราบว่าจำนวนฝากขั้นต่ำคือ {{money}} บาท",
    TOPUP_TO_BANK: "เติมเงิน",
  },
  WITHDRAW: {
    NOTE: "หมายเหตุ: คุณต้องมีเงินขั้นต่ำจำนวน {{amount}} {{currency}} เหลือในบัญชีของท่าน สำหรับรับงานครั้งถัดไป",
    VALID_AMOUNT: "จำนวนเงินที่ถอนต่อรายการจาก {{minCost}}{{currency}} ถึง {{maxCost}}{{currency}}",
    ERROR_SCOPE_OF_MONEY: "จำนวนเงินที่คุณต้องการถอน ไม่สามารถถอนได้ โปรดลองอีกครั้ง",
    MONEY: " {{currency}}{{cost}}",
    RECEIPT_OF_MONEY_INFO: 'ท่านจะได้รับเงินเข้าบัญชีทุกวันอังคารหรือวันศุกร์ ตั้งแต่เวลา 18.00 น เป็นต้นไป ซึ่งจะต้องส่งคำขอถอนเงินก่อนล่วงหน้าอย่างน้อย 1 วัน หากส่งคำขอในวันอังคารหรือวันศุกร์จะนับเป็นการถอนรอบถัดไป แนะนำให้ท่านกดถอนเงินวันจันทร์หรือพฤหัสเพื่อสะสมจำนวนเงินในการถอนได้มากขึ้น',
    TECHCOMBANK: "VietNam Technological and Commercial Joint Stock Bank",
    TRANSFER_FEE: "ค่าธรรมเนียมการถอนเงิน",
    ERROR_TCBANK_NUMBER: "คุณยังไม่ได้ส่งเอกสารข้อมูลบัญชีธนาคาร กรุณาส่งเอกสารเพื่ออัพเดตเลขบัญชี หากท่านส่งแล้วโปรดติดต่อเจ้าหน้าที่เพื่อรับการสนับสนุน",
    UNABLE_TO_WITHDRAW_1: 'คุณจำเป็นต้องมีขั้นต่ำ ',
    UNABLE_TO_WITHDRAW_2: ' สำหรับการถอนเงินคุณจำเป็นต้องมีบัญชีที่สามารถใช้งานได้',
    LABEL_NOTE: "หมายเหตุ: ",
    MIN_MONEY_NOTE: "เพื่อที่จะรับงานได้อย่างต่อเนื่อง บัญชีของคุณต้องมีเงินขั้นต่ำจำนวน: ",
    MIN_MONEY: "จำนวนการถอนเงินขั้นต่ำ: ",
    SCOPE_OF_MONEY: "คุณสามารถถอนเงินได้ตั้งแต่จำนวน {{t1}} ถึง {{t2}} บาท (Currentcy)",
    KASIKORN_BANK: "Kasikornbank",
    RECEIPT_OF_MONEY_INFO_TH: 'ท่านจะได้รับเงินเข้าบัญชีทุกวันอังคารหรือวันศุกร์ ตั้งแต่เวลา 18.00 น เป็นต้นไป ซึ่งจะต้องส่งคำขอถอนเงินก่อนล่วงหน้าอย่างน้อย 1 วัน หากส่งคำขอในวันอังคารหรือวันศุกร์จะนับเป็นการถอนรอบถัดไป แนะนำให้ท่านกดถอนเงินวันจันทร์หรือพฤหัสเพื่อสะสมจำนวนเงินในการถอนได้มากขึ้น',
  },
  ABOUT_BTASKEE: {
    TITLE: "เกี่ยวกับ bTaskee",
    DESCRIPTION: "กิจกรรมของชุมชน bTaskee",
  },
  NEW_VERSION_APP: {
    CONTENT_UPDATE_APP: "แอพลิเคชันมีการอัพเดตเวอร์ชันใหม่ โปรดอัพเดตแอพลิเคชันของท่านเพื่อสัมผัสประสบการณ์ใหม่",
    TITLE_BUTTON_UPDATE_VERSION: "แจ้งเตือน",
    MAINTENANCE_APP_TITLE: "ระบบกำลังอัพเดต โปรดกลับมาภายหลัง",
    NEW_VERSION_BUTTON: "อัพเดตเรียบร้อย",
  },
  CAR_ADVERTISING: {
    YOUR_REFERRAL_CODE: "รหัสแนะนำของท่าน",
    BUTTON_SHARE_REFERRAL_CODE: "แชร์รหัสแนะนำของท่าน",
    NUMBER_PEOPLE_REGISTER_WITH_REFERRAL: "Number of customers who have created accounts",
    NUMBER_PEOPLE_DONE_TASK: "Number of customers who booked the first task",
    TITLE_HISTORY_TRANSACTION: "ประวัติการทำรายการ",
    COST_AND_CURRENCY: "{{cost}} {{currency}}",
    INVITE_ASKER_TEXT_HEAD: "ลงทะเบียนสมัครบัญชีด้วยรหัสอ้างอิง",
    INVITE_ADVERTISING_SHARE_TEXT: "ลงทะเบียนสมัครเป็นผู้ให้บริการด้วยรหัสแนะนำ {{referralCode}} เพื่อรับเงิน {{referralValue}} ในบัญชีโปรโมชัน หลังจากให้บริการงานแรกของคุณเสร็จสิ้น\nหรือรับรหัสส่วนลดมูลค่า {{voucherValue}} จำนวน 1 ครั้ง หลังจากทำการลงทะเบียนสมัครใช้บริการด้วยรหัสแนะนำ {{referralCode}}",
    INVITE_ASKER_TEXT_TAIL: "รับคูปองส่วนลดมูลค่า เมื่อใช้บริการครั้งแรกสำเร็จ",
  },
  MONTHLY_REWARD: {
    TITLE: "รายละเอียดรางวัล",
    CONGRATULATIONS: "ยินดีด้วย!",
    BUTTON_REWARD: "ให้รางวัลเลย",
  },
  LAUNDRY: {
    TITLE_WAITING_COLLECT: "ตรวจสอบและยืนยัน",
    TITLE_WAITING_RETURN: "รอการชำระ",
    RETURN_DATE: "เวลาส่งคืน : ",
    CHECK_AND_CONFIRM: "ตรวจสอบและยืนยัน",
    PICK_UP_CLOTHES: "เวลารับ :",
    COLLECTION_DATE: "วันรับ: ",
  },
  SUPPORT:{
    TITLE: "ศูนย์ให้ความช่วยเหลือ",
    DESCRIPTION: "การสนับสนุนและเวลาการทำการ",
    TITLE_DAILY_WORK: "ฝ่ายสนับสนุนการทำงานประจำวัน",
    TITLE_PERSONNEL_WORK:"ฝ่ายดูแลระบบและบัญชี",
    TITLE_PERSONNEL_WORK2:"(การเงิน, บัญชีถูกล็อค, ต้องการหยุดงาน, อื่นๆ)",
    TIME_DAILY_WORK: "วันจันทร์ - วันอาทิตย์",
    TIME_PERSONNEL_WORK:"วันจันทร์ - วันศุกร์  ",
    SUNDAY:"วันอาทิตย์",
    SATURDAY:"วันเสาร์",
    TIME_IN_WORK:"เวลาการทำการ",
    OUT_OF_TIME:"เวลานอกทำการ",
    SWITCH_BOARD:"ติดต่อเจ้าหน้าที่",
    TEXT_OUT_OF_TIME:"ไม่สนับสนุนนอกเวลาทำการ"
  },
  RATING: {
    BUTTON_RATING: "ให้คะแนน",
    TASKER_RATE_ASKER_TITLE: "ความคิดเห็นต่อลูกค้า",
    TASKER_RATE_ASKER_THANK: "ขอบคุณสำหรับการทำงานนี้ให้สำเร็จ คุณมีความคิดเห็นให้ลูกค้าของคุณอย่างไร",
    TASKER_RATE_ASKER_TASK_NOT_FOUND: "ไม่สามารถให้ความคิดเห็นงานนี้ในตอนนี้ โปรดข้ามไป",
    ASKER_ONE_STAR_LABEL: "แย่",
    ASKER_TWO_STAR_LABEL: "ไม่ดี",
    ASKER_THREE_STAR_LABEL: "ยังไม่ดี",
    ASKER_FOUR_STAR_LABEL: "ดี",
    ASKER_FIVE_STAR_LABEL: "ยอดเยี่ยม",
    ASKER_WHAT_WENT_WRONG: "คุณต้องการแสดงความคิดเห็นไหม",
    ASKER_WHAT_COULD_BE_BETTER: "คุณคาดหวังการบริการอะไรที่ดีกว่า",
    ASKER_WHAT_GOOD: "ข้อดีของลูกค้า",
    ASKER_RATING_REVIEW: "ความคิดเห็นของคุณ",
    ASKER_THANK_YOU_NOTE: "ขอบคุณถึงลูกค้า",
    ASKER_RATING_BAD_1: "การเจรจาต่อรองแบบส่วนตัว",
    ASKER_RATING_BAD_2: "สภาพแวดล้อม ที่ทำงานอันตราย",
    ASKER_RATING_BAD_3: "งานเกินพิกัด",
    ASKER_RATING_BAD_4: "ติดต่อไม่ได้",
    ASKER_RATING_BAD_5: "ไม่เป็นมิตร",
    ASKER_RATING_OTHER: "อื่น ๆ",
    ASKER_RATING_GOOD_1: "ไม่ควรมีการเจรจาตกลงทำงานกันแบบส่วนตัวกับแม่บ้าน",
    ASKER_RATING_GOOD_2: "สร้างความมั่นใจในความปลอดภัยในการทำงาน",
    ASKER_RATING_GOOD_3: "โปรดจองงานและเวลาการทำงานในแอปให้สมดุลกัน",
    ASKER_RATING_GOOD_4: "โปรดรับโทรศัพท์เมื่อใกล้เวลาเริ่มงาน",
    ASKER_RATING_GOOD_5: "เป็นมิตรมากขึ้น",
    FRIENDLY: "เป็นมิตร",
    POLITE: "สุภาพ",
    CHEERFUL: "ร่าเริง",
    SUPPORT: "พร้อมที่จะช่วยเหลือ",
    TASK_SUCCESS: "งานเสร็จสมบูรณ์",
    NOT_RATING: "คุณยังไม่ได้ประเมิณ",
    YOUR_REVIEW: "ความคิดเห็นของคุณ",
    LENGTH_OF_TEXT: "{{t}}/140 คำ",
  },
  FILTER_NEW_TASK: {
    TITLE: "กรองการค้นหาด้วย",
    BY_CREATED_AT: "งานที่พึ่งโพสต์",
    BY_DATE: "งานที่ใกล้จะถึง",
    BY_AREA: "แสดงงานเฉพาะในพื้นที่ที่ลงทะเบียน"
  },
  SHARE_SCREEN: {
    YOUR_REFERRAL_CODE: "รหัสแนะนำขอบคุณ",
    TEXT_SHARE_SUCCESS: "ขั้นตอนเพิ่มรายได้ของคุณ",
    SHARE_WITH_YOUR_FRIEND: "บอกต่อเพื่อน",
    FRIEND_DOW_APP: "พาเพื่อนเข้ามาเป็นส่วนหนึ่ง",
    BE_REWARDED: "ชวนเพื่อนให้กลายเป็นลูกค้า",
    FAQ: "คำถามที่พบบ่อย",
    GIFTS_FOR_YOU_FOR_ME: "แค่บอกต่อก็เพิ่มรายได้!",
    DESCRIPTION_BE_REWARDED: "สำหรับขั้นตอนนี้ เพียงแค่แนะนำให้ดาวน์โหลดแอปพลิเคชัน และอย่าลืมอ่าน คำถามที่พบบ่อยด้านล่างเพื่อคำแนะนำที่ดียิ่งขึ้น",
    DESCRIPTION_FRIEND_DOW_APP: "ให้เพื่อนของคุณกดดาวน์โหลดแอปฯ และสมัครบริการด้วยรหัสแนะนำ อย่าลืมย้ำให้เพื่อนของคุณกรอกรหัสแนะนำตอนลงทะเบียนด้วยนะ!เพื่อนของคุณ",
    DESCRIPTION_SHARE_WITH_YOUR_FRIEND: "กดปุ่ม 'แชร์' ด้านล่างเพื่อแชร์รหัสแนะนำของคุณ",
    HOW_GET_REWARD: "เพื่อนของฉันจะได้รางวัลยังไง?",
    DONE_GET_REWARD:"เมื่อเพื่อนของคุณลงทะเบียนเข้าใช้งาน กรุณากรอกโค้ดแนะนำให้ถูกต้องและครบถ้วน",
    REFERRAL_REWARD: "รางวัลสำหรับการแนะนำ",
    TOTAL_BONUS: "เงินโบนัสทั้งหมดที่คุณได้รับจากการแนะนำเพื่อน",
    SEE_MORE: "ดูทั้งหมด",
    JOIN_DAY: "วันที่เริ่ม",
    ADD_TO_PROMOTION: "เงินที่ได้รับจะเข้าไปยังบัญชีโปรโมชัน",
    SHARE_REFERRAL_CODE: "แชร์รหัสแนะนำ",
    TITLE_SHARE_REFERRAL_CODE: "แบ่งปัน",
    SUB_TITLE_SHARE_REFERRAL_CODE:"แชร์กับ",
    TEXT_Q1: "Q1",
    LABEL_COPY:"คัดลอกสำเร็จ",
    SHARE_WITH_ASKER: "สำหรับแนะนำลูกค้าใช้แอพลิเคชัน",
    SHARE_WITH_TASKER: "สำหรับแนะนำเพื่อนสมัครงาน",
    DEEPLINK_TITLE: 'bTaskee Partner - แอปพลิเคชันสำหรับ bTasker',
  },
  KIT_CHEMICALS:{
    TITLE: "อุปกรณ์และน้ำยาทำความสะอาด",
    GET_KITS: "อุปกรณ์",
    GET_CHEMICALS: "น้ำยาทำความสะอาด",
    GET_KITS_AND_CHEMICALS_DETAIL: "รายละเอียดอุปกรณ์และน้ำยาทำความสะอาด",
    PRESS_BUY_KITS_AND_CHEMICALS: "สถานที่จัดจำหน่าย",
    KITS_AND_CHEMICALS_AMOUNT: "ราคา",
    KITS_AND_CHEMICALS_PRICE: "ราคาอ้างอิง",
    KITS_AND_CHEMICALS_MONEY: "เป็นเงิน",
  },
  DELETE_ACCOUNT:{
    TITLE:"ลบบัญชี",
    TURN_BACK:"กลับมา",
    TEXT_AGREE_DELETE_ACCOUNT:"ฉันได้อ่านและยอมรับเงื่อนไขการลบบัญชี ",
    DELETE_ACCOUNT_TITLE_REASON:"เหตุผล",
    DELETE_ACCOUNT_SUB_REASON:"ทำไมคุณถึงต้องการลบบัญชี?",
    PLACEHOLDER_TEXT_INPUT:"กรุณาระบุเหตุผลที่ต้องการลบบัญชี",
    TEXT_TITLE_DELETE:"คุณไม่ต้องการเป็นบีทัสเก้อแล้ว",
    TEXT_INFO_ACCOUNT:"• รายละเอียดบัญชี",
    TEXT_CONFIRM:"โปรดรับทราบว่าการลบบัญชีจะทำให้คุณเสียโอกาสดังต่อไปนี้",
    TEXT_1:"• การลบบัญชีจะไม่สามารถกู้คืนอีกได้",
    TEXT_2:"• และคุณจะไม่สามารถใช้อิเมล์และเบอร์โทรศัพท์นี้ในการลงทะเบียนได้อีกครั้ง",
    TEXT_TRANS_INFO:"• และคุณจะไม่สามารถใช้อิเมล์และเบอร์โทรศัพท์นี้ในการลงทะเบียนได้อีกครั้ง",
    TEXT_TRANS_INFO_1:"ข้อมูลใดๆที่เกี่ยวข้องกับการทำธุรกรรมในแอพลิเคชัน, ที่อยู่ที่บันทึกไว้ , วิธีการชำระเงิน",
    TEXT_PRIVILEGES_BENEFIT:"• สิทธิประโยชน์",
    TEXT_PRIVILEGES_BENEFIT_1:"คุณจะสูญเสียเงินโบนัส, ของรางวัล และสิทธิพิเศษที่ได้รับจาก bTaskee",
    TEXT_INFO_ACCOUNT_1:"ข้อมูลส่วนตัวที่เกี่ยวข้องกับบัญชีและการเงินของท่าน",
    TEXT_INFO_ACCOUNT_2:"bTaskee จะไม่รับผิดชอบใด ๆ เกี่ยวกับการสูญหายของข้อมูลที่เกี่ยวข้อง, หรือเงินใด ๆ หลังจากที่บัญชีถูกลบออกแล้ว",
    DELETE_ACCOUNT_SUCCESS: "บัญชีของคุณถูกลบอย่างถาวรออกจากระบบของ bTaskee แล้ว ขออภัยในความไม่สะดวกที่เกิดขึ้น และเราหวังว่าคุณจะกลับมาร่วมงานกันอีกครั้ง",
    ARE_YOU_SURE: "คุณแน่ใจว่าต้องการลบบัญชีหรือไม่?",
  },
  BCARE: {
    TITLE: "กฏการสนับสนุนการเกิดอุบัติเหตุ",
    HEADER_TEXT: "แม่บ้านในระบบของ bTaskee ได้รับการคุ้มครองประกันอุบัติเหตุ",
    ROLE_LABEL: "สิ่งที่จำเป็น",
    ROLE_TEXT: "เป็นแม่บ้านในระบบของ bTaskee ",
    CONDITION_LABEL: "เงื่อนไข",
    CONDITION_TEXT: "คุ้มครองการเกิดอุบัติเหตุระหว่างไปทำงานที่บ้านลูกค้า และขณะทำงานในระบบของ bTaskee:",
    CONDITION_TEXT_1: "• เสียชีวิต",
    CONDITION_TEXT_2: "• ทุพพลภาพถาวรสิ้นเชิงหรือบางส่วนเนื่องจากอุบัติเหตุจากการทำงาน",
    FEE_LABEL: "ค่าคุ้มครอง",
    FEE_TEXT: "แม่บ้าน ",
    FEE_TEXT_1: "ไม่มีค่าใช้จ่าย",
    FEE_TEXT_2: " ไม่ต้องเสียค่าประกัน",
    BENEFIT_LABEL: "สิทธิประโยชน์",
    BENEFIT_TEXT: "1. ผู้ทำงานร่วมกันจะได้รับ:",
    BENEFIT_TEXT_1: "• ช่วยเหลือค่าใช้จ่ายหากเกิดอุบัติเหตุถึงขั้นเสียชีวิต",
    BENEFIT_TEXT_2: "• อุบัติเหตุส่งผลให้ทุพพลภาพถาวรสิ้นเชิงบางส่วนหรือทั้งหมด",
    BENEFIT_TEXT_3: "• เงินช่วยเหลือระหว่างการรักษาตัวในโรงพยาบาลเนื่องจากอุบัติเหตุ",
    BENEFIT_TEXT_4: "• ช่วยเหลือค่ารักษาพยาบาลจากอุบัติเหตุ",
    BENEFIT_TEXT_5: "bTaskee จะส่งเสริมการคุ้มครองสิทธิและผลประโยชน์ของท่าน",
    AMOUNT_LABEL: "ระดับของการป้องกัน",
    AMOUNT_TEXT: "จำนวนสนับสนุนสูงสุด ",
    AMOUNT_TEXT_1: "100,000,000 VND.",
    PROCEDURE_LABEL: "ขั้นตอนการสนับสนุน",
    PROCEDURE_TEXT_1: "กรณีเกิดอุบัติเหตุ โปรดแจ้ง bTaskee ผ่านหมายเลขโทรศัพท์ 0901.300.501 - กดปุ่ม 8",
    PROCEDURE_TEXT_2: "กรุณาเก็บใบรับรองแพทย์และเอกสารทั้งหมดที่เกี่ยวข้องกับการรักษาพยาบาล และนำส่งมาที่ bTaskee ออฟฟิศภายใน 30 วันนับจากวันที่ออกจากโรงพยาบาล เพื่อรับการสนับสนุนภายใน 30 วันนับจากได้รับเอกสาร",
    PROCEDURE_TEXT_3: "ต้องมีใบกำกับภาษีเมื่อซื้อยาจากนอกโรงพยาบาล เมื่อมีมูลค่ามากกว่า 200,000 VND",
    REQUIRE_LABEL: "สิ่งที่จำเป็นต้องมี",
    REQUIRE_TEXT_1: "ใบเสร็จ",
    REQUIRE_TEXT_2: "ค่ายา",
    REQUIRE_TEXT_3: "ใบรับรองแพทย์",
    NOTE: "หมายเหตุ:",
    NOTE_TEXT_1: "• เอกสารจำเป็นต้องมีลายเซนต์แพทย์และตราประทับจากโรงพยาบาล , ร้านขายยา และระบุรายละเอียดการป่วย",
    NOTE_TEXT_2: "• แม่บ้านจำเป็นต้องเตรียมเอกสารทั้งหมดส่งให้ทางบริษัทเพื่อพิจารณาการสนับสนุน",
  },
  REFERRAL: {
    TITLE:"กรอกรหัสแนะนำเพื่อรับของขวัญพิเศษ",
    YES:"ใส่รหัสแนะนำ",
    NO:"ไม่มีรหัสแนะนำ"
  },
  MODAL_ALERT: {
    TITLE_MODAL_TIP: "ยินดีด้วย!",
    LABEL_MODAL_TIP: "คุณได้รับทิปจากลูกค้า",
    TEXT_MODAL_TIP: "ทักษะ คุณภาพงาน และทัศนคติในการบริการของคุณสมควรได้รับรางวัลนี้จากลูกค้า พยายามต่อไปเพื่อชนะใจลูกค้ามากขึ้น!",
    TITLE_MODAL_LEVEL_UP: "Level Up",
  },
  PROCEDURE_ACTIVE_ACCOUNT: {
    BUTTON_TEST_NOW: "ทดสอบตอนนี้",
    TITLE_STEP_1: "ทดสอบความรู้สมัครงาน",
    TITLE_STEP_2: "ความรู้พื้นฐาน",
    TITLE_STEP_3: "เปิดบัญชี",
    CONTENT_STEP_1: "มาดูกันว่า คุณมีทักษะและทัศนคติที่เหมาะสำหรับการทำอาชีพแม่บ้านหรือไม่",
    CONTENT_STEP_2: "กรุณาเข้าร่วมการโปรแกรมการฝึกทักษะขั้นพื้นฐานก่อนที่จะร่วมงานกัน!",
    CONTENT_STEP_3: "ยินดีด้วยคุณมีคุณสมบัติในการร่วมงานกับบีทัสกี้ และเราแน่ใจว่าคุณจะประสบความสำเร็จในเส้นทางนี้ไปด้วยกันกับเรา",
    NUMBER_OF_TIME_TEST: "เวลาสำหรับการทำแบบทดสอบ",
    TEXT_SUCCESS: "สำเร็จ",
    TEST_FALSE: "คุณได้ทำเกินจำนวนครั้งตามที่กำหนดแล้ว โปรดติดต่อเจ้าหน้าที่หากต้องการความช่วยเหลือ",
    MAKE_APPOINTMENT: "นัดหมายอบรม",
    ACTIVE_SUCCESS_TITLE: "ยินดีด้วย!",
    ACTIVE_SUCCESS_CONTENT: "การแจ้งเตือนหลังจากทำการจองนัดหมายเสร็จสมบูรณ์: ขอแสดงความยินดีด้วย คุณได้ทำการส่งใบสมัครเรียบร้อยแล้ว โปรดทราบว่าเราจะมีนัดหมายเข้ามาอบรมและส่งเอกสารที่สำนักงาน กรุณานำสำเนาเอกสารและเอกสารต้นฉบับที่ได้รับการรับรองมาดังนี้",
    TITLE_MAKE_AN_APPOINTMENT: "นัดหมายอบรม",
    BUTTON_CHAT: "แชท",
    BUTTON_CALL: "แชทตอนนี้",
    MORNING_APPOINTMENT: "เช้า - 09.00 น",
    AFTERNOON_APPOINTMENT: "บ่าย - 13.00 น",
    TITLE_SELECT_TIME: "เลือกเวลา",
    LABEL_DATE: "วัน",
    LABEL_TIME: "เวลา",
    NOTE_SELECT_TIME: "หมายเหตุ: โปรดมาถึงตรงเวลาการนัดหมาย เพื่อไม่ให้กระทบกับผู้ร่วมอบรมท่านอื่นๆ หากท่านมาสายเกินเวลานัดหมายจะต้องทำการนัดหมายใหม่ในรอบถัดไป",
    TITLE_SELECT_PLACE: "เลือกสถานที่",
    APPROVED_TITLE: "อนุมัติเรียบร้อย",
    APPROVED_CONTENT: "ขอแสดงความยินดีด้วย การอัพเดตโปรไฟ์ของคุณเสร็จสมบูรณ์แล้ว กรุณานัดหมายการอบรมในพื้นที่ใกล้เคียงของท่าน เพื่อเปิดบัญชีการใช้งาน",
    PROCESSING_TITLE: "กำลังตรวจสอบเอกสาร",
    PROCESSING_CONTENT: "เรากำลังตรวจสอบเอกสารของคุณ ระบบจะแจ้งเตือนผลการตรวจสอบให้คุณทราบโดยเร็วที่สุด",
    BUTTON_UPDATE_PROFILE:"อัพเดตโปรไฟล์",
    REJECTED_TITLE: "ถูกปฏิเสธ",
  },
  SUPPLEMENT_INFO:{
    TITLE_ADD_SUPPLEMENT:"อัพโหลดโปรไฟล์",
    NOTE_SUPPLEMENT_1:"• เอกสารที่ได้รับการรับรองจากเจ้าหน้าที่รัฐจะต้องมีอายุไม่เกิน 6 เดือน",
    NOTE_SUPPLEMENT_2:"• กรุณาวางบัตรประชาชนเพื่อถ่ายด้านหน้าและด้านหลังของบัตร",
    NOTE_SUPPLEMENT_3:"• กรุณาถ่ายรูปอย่างชัดเจนโดยไม่ตัดขอบใดๆ และหลีกเลี่ยงการมีแสงสะท้อนบนข้อมูลสำคัญในเอกสาร",
    TEXT_IDENTITY:"บัตรประชาชน",
    TEXT_RESIDENCY:"ทะเบียนบ้าน",
    TEXT_CURRICULUM:"ประวัติการทำงาน",
    TEXT_CERTIFICATE:"ใบตรวจประวัติอาชญากรรม",
    TEXT_REQUIRE:"* จำเป็น",
    TEXT_OPTIONAL:"* ไม่บังคับ (คุณสามารถส่งทีหลังได้)",
    TEXT_SUPPLEMENT_NOTE:"กรุณาส่งเอกสารที่ต้องใช้สำหรับสมัครงาน",
    OPEN_PHOTO_GALLERY:"เปิดรูปภาพจากแกลเลอรี",
    OPEN_IMAGE_CAMERA:"ถ่ายภาพจากกล้อง",
    TEXT_NOTE_IDENTITY_1:"• โปรดตรวจสอบให้แน่ใจว่าสภาพแวดล้อมการถ่ายรูปมีความสว่างเพียงพอ",
    TEXT_NOTE_IDENTITY_2:"• วางบัตรของคุณไว้ตรงกลางและให้พอดีกับกรอบ",
    TAKE_A_PHOTO:"ถ่ายรูป",
    IMAGE_FRONT_SIDE:"ด้านหน้า",
    IMAGE_BACK_SIDE:"ด้านหลัง",
    UPLOAD:"อัพโหลด",
    REUPLOAD:"อัปโหลดใหม่",
    OPEN_CAMERA:"เปิดกล้อง",
    CHOOSE_PHOTO:"เลือกรูปภาพจาก",
    UPLOAD_IMAGE:"อัปโหลดรูปภาพ",
  },
  JOURNEY:{
    TITLE:"การเดินทางของฉัน",
    LEADER_BOARD_SCREEN:"ตารางจัดอันดับ",
    TITLE_MAIN_PRIZE: "รางวัล:",
    TITLE_BONUS: "โบนัส:",
    BUTTON_GET_REWARD: "แลกคะแนน",
    TRAINING: "เริ่มอบรม",
    TASK: "กลับสู่เมนูหลัก",
    TITLE_ALERT: "รายละเอียด",
    TITLE_NUMBER_OF_TASK: "{{t}} งาน",
    TITLE_CURRENT_LEVEL: "ระดับของฉัน",
    AVG_RATING_CONDITION: "คุณภาพงานควรอยู่ที่ {{t}} หรือสูงกว่า",
    MESSAGE_GET_REWARD_SUCCESS: "รับรางวัลสำเร็จ!",
    TITLE_RECEIVED_REWARD: "สิ่งที่ได้รับ:",
    BONUS_PRIZE: "โบนัส:",
    LABEL_TIME_PASSED: "เวลาผ่านไปแล้ว",
    TITLE_PRIZE_BONUS_DETAIL: "รายละเอียดโบนัส",
    TITLE_PRIZE_BONUS: "โบนัส",
    HOURS: "{{t}} ชั่วโมง",
    DAYS: "{{t}} วัน ",
    TRAINING_PASSED: "สำเร็จ",
    TRAINING_INCOMPLETE: "ยังไม่สำเร็จ",
    BONUS_NOT_RECEIVE: "รางวัลที่ยังไม่ได้:",
    RECEIVE_AT_OFFICE: " (รับที่สำนักงาน)",
    LABEL_PROCESSING: "กำลังประมวลผล",
    LABEL_PASSED: "ผ่าน",
    LABEL_LOCKED: "ล็อค",
    LABEL_MISSION: "ภารกิจของคุณ:",
    LEADER_BOARD_EMPTY: "ตารางจัดอันดับกำลังอัปเดต!",
    TEXT_MODAL_ALERT_LEVEL_UP: "ยินดีด้วยที่ไปถึงเป้าหมาย!",
    DESCRIPTION_MODAL_ALERT_LEVEL_UP: "รับรางวัลสำหรับความพยายามของคุณและสู้ต่อไปเพื่ออนาคต!",
    TITLE_BUTTON_SEE_REWARD: "ดูรางวัล",
    TITLE_BUTTON_NEXT_REWARD: "รางวัลถัดไป",
    LABEL_MODAL_ALERT_LEVEL_UP_REWARD: "ยินดีด้วยค่ะ!",
    TEXT_BONUS_PRIZE: "รางวัลโบนัส",
    TITLE_BUTTON_RANK_SCORE: "How to calculate the ranking score?",
    TITLE_CALCULATE_SCORE: "How to calculate points?",
    TITLE_HOW_TO_CALCULATE_SCORE: "How to calculate rating points",
    TEXT_CALCULATE_SCORE_1: "After completing 1 task, your score will be calculated based on the formula:",
    TEXT_CALCULATE_SCORE_2: "Extra Ranked Points = ",
    TEXT_CALCULATE_SCORE_3: " “Rate the quality of service” ",
    TEXT_CALCULATE_SCORE_4: " “Time to complete the task” ",
    TEXT_CALCULATE_SCORE_5: "For example, when completing **1 task** that requires execution from **12:00 to 16:00 (4 hours)** and is rated by a customer **5 stars**, you will have:",
    TEXT_CALCULATE_SCORE_6: "1 + 4 + 5 = 10 (point)",
    TITLE_RATING_SERVICE_QUALITY: "Service quality rating",
    TEXT_RATING_SERVICE_QUALITY_1: "From 1 to 5",
    TEXT_RATING_SERVICE_QUALITY_2: "When the Task is done, be sure to remind the customer to rate the service for additional rating points. Try to do well to get a 5 star rating, you will get 5 points.",
    TITLE_DURATION: "Time to complete the task",
    TEXT_DURATION_1: "Based on the required time of the task",
    TEXT_DURATION_2: "Note that the task completion time is fixed when the customer places the service, you cannot deliberately delay the completion of the work longer to earn more points.",
    TITLE_DETAIL_JOURNEY: "Journey detail",
    LEARN_MORE: "เรียนรู้เพิ่มเติม",
    DESCRIPTION_LEARN_MORE: "คุณสามารถดูข้อมูลทั้งหมดสำหรับการเดินทางของคุณได้ที่นี้ ",
    COMING_SOON: "มาเร็ว ๆ นี้",
    CURRENT_LEVEL: "ระดับในปัจจุบัน",
    TEXT_TRAINING_TO_RECEIVE_BONUS: "Complete training to get rewards",
  },
  MEMBER_INFO: {
    TITLE: "Member Infor",
    BPOINT_HISTORY: "bPoint History",
    VIEW: "View",
    SEE_NOW: "See now",
  },
  BREWARD: {
    RECOMMEND_FOR_YOU: "Recommend for you",
    FLASH_SALES: "Flash Sales",
    TOP_DEALS: "Top Deals",
    EXCLUSIVE_DEALS: "Exclusive Deals",
    VIEW_MORE: "View more",
    REDEM_NOW: "Redeem now",
    ALL: "ทั้งหมด",
    TITLE_BPOINT_HISTORY_RECEIVED: "Received",
    TITLE_BPOINT_HISTORY_USED: "Used",
    EMPTY_TRANSACTION: "List transaction is empty!",
    TITLE_BUTTON_VIEW_MORE: "View more",
    EXPIRED_DATE:"Expired date",
    MY_REWARD: "My reward",
    RECENT_SEARCHES:"Recent searches",
    VOUCHERS_SEARCHES:"Vouchers searches",
    SEARCH:"Search for vouchers by voucher name: Discount ...",
    BUTTON_AGREE:"Agree",
    BUTTON_LATER:"Later",
    TITLE_CONTACT:"Contact",
    STORE:"Store List",
    BRANCH_STORE:"Currently {{t}} active",
    BRANCH_STORE_EMPTY:"The list of stores is being updated",
    DOW_IOS:"IOS",
    DOW_ANDROID:"Android",
    DOW:"Download the application",
    OUT_OF_STOCK: "สินค้าหมด",
  },
  WEATHER:{
    TITLE: "Weather",
    BY_DATE: "By date",
    BY_HOUR: "By hour",
    PARTLY_CLOUDY: "Partly cloudy",
    MODERATE_RAIN: "Moderate rain",
    PATCHY_RAIN_POSSIBLE: "Patchy rain possible",
    SUNNY: "Sunny",
    CLEAR: "Clear",
    OVERCAST: "Overcast",
    CLOUDY: "Cloudy",
    LIGHT_RAIN: "Light rain",
    MODERATE_RAIN_AT_TIME: "Moderate rain at times",
    HEAVY_RAIN: "Heavy rain",
    HEAVY_RAIN_AT_TIME: "Heavy rain at times",
    MODERATE_OR_HEAVY_FREEZING_RAIN: "Moderate or heavy freezing rain",
    MODERATE_OR_HEAVY_RAIN_SHOWER: "Moderate or heavy rain shower",
    MODERATE_OR_HEAVY_RAIN_WITH_THUNDER: "Moderate or heavy rain with thunder",
    MIST: "Mist",
    FOG: "Fog",
    PATCHY_RAIN_NEARBY: "Patchy rain nearby",
    PATCHY_SNOW_NEARBY: "Patchy snow nearby",
    PATCHY_SLEET_NEARBY: "Patchy sleet nearby",
    PATCHY_FREEZING_DRIZZLE_NEARBY: "Patchy freezing drizzle nearby",
    THUNDERY_OUTBREAKS_IN_NEARBY: "Thundery outbreaks in nearby",
    FREEZING_FOG: "Freezing fog",
    PATCHY_LIGHT_DRIZZLE: "Patchy light drizzle",
    LIGHT_DRIZZLE: "Light drizzle",
    FREEZING_DRIZZLE: "Freezing drizzle",
  }
};
