export default {
  VALIDATE: {
    THIS_FIELD_IS_REQUIRED: "Thông tin bắt buộc",
    ERROR_PASSWORD_LENGTH: "Mật khẩu 6 - 12 ký tự, không khoảng trắng.",
    TYPE_INPUT_INVALID: "Thông tin không hợp lệ",
  },
  ERROR: {
    ERROR_TRY_AGAIN: "Có lỗi xảy ra. Vui lòng thử lại! [{{t}}]",
    PHONE_NUMBER_SYNTAX_IS_INCORRECT: "Số điện thoại không đúng",
    SEND_OTP_MESSAGE_ACCOUNT_NOT_EXIST: "Số điện thoại không tồn tại.",
    ACTIVATION_ERROR_CODE: "Mã kích hoạt không đúng. Vui lòng thử lại.",
    USER_NOT_FOUND: "Tài khoản không tồn tại",
    USER_LOCKED: "Tài khoản của bạn tạm thời bị khóa, vui lòng liên hệ chúng tôi để biết thêm chi tiết",
    INVALID_PASSWORD: "Mật khẩu không đúng. Vui lòng nhập lại.",
    USER_TYPE_INCORRECT: "Số điện thoại này đã được đăng ký trên ứng dụng bTaskee (Ứng dụng dành cho Khách hàng). Vui lòng liên hệ với tổng đài để được hỗ trợ thêm!",
    USER_PERMISSION_DENIED: "Không có quyền truy cập",
    NETWORK_REQUEST_FAILED: "Không có kết nối. Vui lòng kiểm tra mạng!",
    CANCEL_LIMITED: "Không thể hủy công việc này. Bạn đã vượt mức hủy công việc cho phép trong 7 ngày qua !",
    ACTIVATION_CODE_INVALID: "Mã kích hoạt không đúng. Vui lòng thử lại.",
    BUTTON_RELOAD: "Tải lại",
  },
  PERMISSION: {
    ACCESS_PHOTOS_TITLE: "Yêu cầu quyền truy cập ảnh",
    ACCESS_PHOTOS_CONTENT: "bTaskee cần quyền truy cập ảnh để thực hiện chức năng này",
    WRITE_EXTERNAL_STORAGE_TITLE: "Yêu cầu quyền lưu trữ",
    WRITE_EXTERNAL_STORAGE_CONTENT: "bTaskee cần quyền để lưu trữ vào điện thoại của bạn",
  },
  NOTIFICATION: {
    TAB_NOTIFICATION: "Thông báo",
    NOTIFICATION_MESSAGE: "Bạn có muốn xoá thông báo",
    NOTIFICATION_MESSAGE_NOTHING: "Hiện tại không có thông báo",
    NOTIFICATION_DETAIL: "Chi tiết thông báo",
    TASK_NOTIFICATION: "Thông báo công việc",
    SYSTEM_NOTIFICATION: "Thông báo hệ thống",
    HAPPY_BIRTHDAY_TITLE: "Chúc mừng sinh nhật",
    TITLE_HAVE_NEW_TASK: "Công việc mới",
    READ_ALL_NOTIFICATION: "Đánh dấu đã đọc",
    TITLE_NOTIFICATION_WARNING: 'Chức năng thông báo công việc đã TẮT',
    CONTENT_NOTIFICATION_WARNING: 'Bạn có thể bỏ lỡ những công việc hấp dẫn khi tắt thông báo. Mở tính năng thông báo ngay.',
    TURN_ON_NOTIFICATION: 'Bật thông báo ngay',
  },
  DIALOG: {
    BUTTON_CLOSE: "Đóng",
    BUTTON_ACCEPT: "Đồng ý",
    TITLE_INFORMATION: "Thông báo",
    TITLE_ERROR: "Rất tiếc",
    BUTTON_SEE: "Xem",
    BUTTON_DONE: "Đóng",
    BUTTON_SEE_AGAIN: "Xem lại",
    BUTTON_CALL_SUPPORT: "Gọi hỗ trợ",
    UPDATE_SUCCESS: "Cập nhật thành công",
    BUTTON_CONFIRM: "Xác nhận",
    BUTTON_UPDATE: "Cập nhật",
    BUTTON_NEXT: "Tiếp theo",
    CANCEL_TASK_SUCCESS: "Bạn hãy vào chọn một công việc mới phù hợp hơn nhé!",
    ARE_YOU_SURE_TO_GO_BACK: "Bạn có chắn chắn muốn thoát khỏi ứng dụng?",
    BUTTON_CANCEL: "Huỷ",
    BUTTON_SKIP: "Bỏ qua",
    BUTTON_SEE_MORE: "Xem ngay"
  },
  LOGIN: {
    TITLE_LOGIN: "Đăng nhập",
    USERNAME: "Số điện thoại",
    PASSWORD: "Mật khẩu",
    BUTTON_LOGIN: "Đăng nhập",
    FORGOT_PASSWORD: "Quên mật khẩu?",
    SIGN_UP: "Đăng ký",
    VERSION: "Phiên bản {{t}}",
    BUILD_NUMBER: "Mã {{t}}",
    TASKER_APP: "Dành cho Cộng Tác Viên",
    MESSAGE_ACCOUNT_ACTIVE: "Tài khoản của bạn chưa được kích hoạt, hãy kích hoạt ngay",
    MESSAGE_ACCOUNT_TASKER_LOCK: "bTaskee rất tiếc phải hạn chế tài khoản của bạn trong lúc này. Vui lòng liên hệ Tổng đài để tiếp tục nhận việc.",
    MESSAGE_TOKEN_EXPIRED: "Tài khoản của bạn đăng nhập ở thiết bị khác. Đổi mật khẩu nếu đó là đăng nhập trái phép. Vui lòng đăng nhập lại để sử dụng dịch vụ!"
  },
  CHOOSE_LANGUAGE: {
    TITLE: "Chọn ngôn ngữ",
    VI: "Tiếng Việt",
    EN: "English",
    TH: "ภาษาไทย",
    ID: "Bahasa Indonesia",
  },
  COUNTRY: {
    INDONESIA: "Indonesia",
    VIETNAM: "Việt Nam",
    THAILAND: "Thái Lan",
  },
  REGISTER: {
    TITLE_REGISTER: "Đăng ký",
    FULL_NAME: "Họ và tên",
    FULL_NAME_PLACEHOLDER: "Nguyễn Văn A",
    ID_NUMBER: "Số CMND/CCCD",
    ID_NUMBER_PLACEHOLDER: "123456789",
    PHONE_NUMBER: "Số điện thoại",
    PHONE_NUMBER_PLACEHOLDER: "0987654321",
    PASSWORD: "Mật khẩu (để đăng nhập lần sau)",
    PASSWORD_PLACEHOLDER: "Ít nhất 6 ký tự",
    REFERRAL_CODE: "Mã giới thiệu (nếu có)",
    REFERRAL_CODE_PLACEHOLDER: "Mã giới thiệu",
    BUTTON_REGISTER: "Đăng ký",
    BUTTON_CHOOSE_WORKING_PLACES: "Chọn các khu vực làm việc",
    BUTTON_CONFIRM_OTP: "Kích hoạt",
    BUTTON_RESEND_CODE: "Gửi lại mã",
    REFERRAL_REWARD: "Nhập mã giới thiệu từ Cộng Tác Viên để nhận được nhiều ưu đãi hấp dẫn từ bTaskee.",
    BUTTON_NEXT: "Tiếp tục",
    TEXT_OTP:"Mã OTP sẽ xuất hiện trong",
    BUTTON_RESEND_CODE_1: "Bạn không nhận được mã OTP?",
  },
  REGISTER_CHOOSE_WORKING_PLACE_CITY: {
    TITLE: "Chọn thành phố",
    CHOOSE_CITY: "Bạn muốn làm việc ở thành phố nào?",
    NOTE_CHOOSE_SERVICE: "Xin lưu ý, các dịch vụ có thể thay đổi tùy theo thành phố và bạn chỉ chọn một thành phố để làm việc",
  },
  REGISTER_CHOOSE_WORKING_PLACE_DISTRICT: {
    TITLE: "Chọn quận",
    LIMIT_DISTRICT: "Chọn tối đa 3 quận",
    CHOOSE_DISTRICT: "Bạn muốn làm việc ở quận nào?",
  },
  REGISTER_CHOOSE_SERVICES: {
    TITLE: "Chọn dịch vụ",
    BUTTON_REGISTER: "Đăng ký",
    CHOOSE_SERVICES: "Bạn muốn đăng ký dịch vụ nào?",
  },
  CONFIRM_CHOOSE_WORKING_PLACE_AND_SERVICES: {
    CONFIRM: "Xác nhận",
    CONFIRM_NOTE: "Vui lòng kiểm tra lại thông tin đăng ký để nhận được chương trình đào tạo thích hợp.",
    SERVICES: "Dịch vụ",
    DISTRICTS: "Quận",
    SAVE_SUCCESS: "Bạn đã đăng ký dịch vụ thành công! Hãy cùng bTaskee kiểm tra tay nghề nhé!",
  },
  FORGOT_PASSWORD: {
    TITLE: "Quên mật khẩu",
    DESCRIPTION: "Nhập số điện thoại đã đăng ký để nhận lại mật khẩu của bạn",
    RESEND_PASSWORD: "Gửi lại mật khẩu",
  },
  SET_PASSWORD: {
    TITLE: "Thiết lập mật khẩu mới",
    DESCRIPTION: "Mật khẩu này sẽ là mật khẩu cho bạn đăng nhập vào lần tới.",
    NEW_PASSWORD: "Mật khẩu mới",
    SAVE: "Lưu",
    SUCCESS_SET_PASSWORD: "Đổi mật khẩu thành công",
    WELCOME: "Chào mừng bạn đã quay lại với Btaskee",
  },
  CHANGE_PASSWORD: {
    TITLE: "Thay đổi mật khẩu",
    DESCRIPTION: "Mật khẩu này sẽ là mật khẩu cho bạn đăng nhập vào lần tới.",
    INPUT_OLD_PASSWORD: "Nhập mật khẩu cũ",
    OLD_PASSWORD: "Mật khẩu cũ",
    INPUT_NEW_PASSWORD: "Nhập mật khẩu mới",
    NEW_PASSWORD: "Mật khẩu mới",
    ACCESS: "Đồng ý",
    SUCCESS_CHANGE_PASSWORD: "Đổi mật khẩu thành công",
    CHANGE_PASSWORD: "Đổi mật khẩu",
    WELCOME: "Chào mừng đến bTaskee",
  },
  CHOOSE_COUNTRY: {
    TITLE_CHOOSE_COUNTRY: "Chọn quốc gia",
    BUTTON_NEXT: "Tiếp theo",
    TITLE: "Bạn sinh sống ở đâu?",
  },
  OTP: {
    TITLE: "Kích hoạt tài khoản",
    HELLO: "Xin chào",
    INSTRUCTION_OTP: "MÃ KÍCH HOẠT đã gửi đến số điện thoại {{t}} của bạn qua tin nhắn. Vui lòng nhập MÃ KÍCH HOẠT vào bên dưới!",
    ACTIVATION_CODE: "Mã kích hoạt",
    RESEND_CODE_ERROR: "Bạn đã ấn gửi quá nhiều lần. Vui lòng thử lại sau.",
  },
  TASK_DETAIL: {
    TITLE: "Chi tiết công việc",
    DESCRIPTION_FOR_PROMOTION: "Thêm vào TK khuyến mãi của bạn",
    PAYMENT_METHOD_LABEL: "Phương thức thanh toán:",
    TYPE_HOUSE_LABEL: "Loại nhà: ",
    NOTE_LABEL: "Ghi chú: ",
    BUTTON_SEE_FULL_NOTE: "Xem tất cả",
    BUTTON_SLIDE_TO_CONFIRM: "Kéo để nhận việc",
    BUTTON_FAQ: "Hỏi đáp",
    STATUS_WAITING_CONFIRM: "Chờ xác nhận",
    WITHDRAW_TASK: "Rút khỏi công việc",
    BEGIN_WORK: "Bắt đầu công việc",
    TASK_IS_WORKING: "Công việc đang thực hiện",
    DURATION_NOTE: "Làm trong {{duration}} giờ",
    COUNT_DOWN_TIME_START_JOB: "Công việc sẽ bắt đầu sau {{time}}",
    COUNT_DOWN_TIME_START_JOB_TASK_ITEM: "Bắt đầu sau:",
    COUNT_DOWN_TIME_FINISH_JOB: "Công việc sẽ kết thúc sau {{time}}",
    FINISH: "Hoàn tất",
    DURATION_HOUSE: "{{duration}} phòng : {{area}}",
    APARTMENT: "Căn hộ",
    HOME: "Nhà/ nhà phố",
    VILLA: "Biệt thự",
    HOTEL: "Khách sạn",
    DOG: "Chó",
    CAT: "Mèo",
    REQUIREMENTS_COOKING: "Nấu ăn",
    REQUIREMENTS_IRON: "Ủi đồ",
    REQUIREMENTS_2_SHOTS_VACCINE: "Đã tiêm 2 mũi vaccine",
    REQUIREMENTS_NEGATIVE_TEST_COVID: "Giấy xét nghiệm COVID-19 âm tính trong vòng 7 ngày",
    REQUIREMENTS_BRING_TO_TOOLS: "Mang theo dụng cụ",
    CALL_WITH_PHONE_NUMBER: "Gọi bằng số điện thoại",
    CALL_WITH_BTASKEE_APP: "Gọi bằng bTaskee",
    ACCEPTED_SUCCESS: "Nhận công việc thành công",
    ACCEPTED_TASK_WAITING_SUCCESS: "Nhận công việc thành công. Đang chờ Khách hàng xác nhận",
    PAYMENT_METHOD_CASH: "Thu tiền mặt",
    PAYMENT_METHOD_TRANSFER: "Chuyển khoản",
    MY_TASK_EMPTY: "Bạn chưa nhận công việc nào vào ngày này",
    NEW_TASK_EMPTY: "Chưa có công việc mới nào",
    BUTTON_TRANSLATE_NOTE: "Dịch",
    NOTES_TITLE: "Ghi chú",
    BUTTON_DONE: "Xong",
    NUMBER_OF_TASK: "{{number}} việc",
    BUTTON_GO_TO_DATE: "Hôm nay",
    NUMBER_ACCEPTED_TASK: "Số người đã nhận công việc: ",
    TITLE_CANCEL_TASK: "Huỷ việc",
    BUTTON_CANCEL: "Huỷ việc",
    BUTTON_NO: "Quay lại",
    CONFIRM_CANCEL_TEXT: "Bạn có chắc chắn muốn huỷ công việc này?",
    CANCEL_TASK_REASON_NEARBY_TASK_PLACE: "Đã tới chỗ làm, cố gắng liên hệ khách hàng không được.",
    CANCEL_TASK_REASON_SO_FAR_AWAY: "Lỡ nhận công việc quá xa.",
    CANCEL_TASK_REASON_WRONG_DATE: "Xem nhầm ngày không đi làm được.",
    CANCEL_TASK_OTHER_REASON: "Lý do khác",
    CANCEL_TASK_REASON_TEXT: "Vui lòng bấm chọn 1 trong các lý do bên dưới để hủy công việc này",
    CANCEL_REASON_IS: "Lý do huỷ việc là:",
    CANCEL_FREE: "Phí:",
    NOTE_CANCEL_TASK: "Tiền phạt sẽ trừ trực tiếp vào tài khoản chính nếu bạn hủy công việc.",
    PLACEHOLDER_TEXT_INPUT: "Vui lòng nhập lý do bạn muốn huỷ công việc này...(Thông tin bắt buộc)",
    TITLE_MODAL_CALL: "Liên hệ với khách hàng",
    PREMIUM_TASK: "Dịch vụ Premium",
    TASK_FROM_SUBSCRIPTION: "Công việc gói",
    POP_UP_DRAW_TASK_TXT: "Uy tín của bạn sẽ bị giảm. Bạn có chắc chắn muốn rút khỏi công việc này?",
    CANCELED: "Đã huỷ",
    DONE: "Đã hoàn thành",
    CANCELED_BY_TASKER: "Đã huỷ bởi bạn",
    CANCELED_BY_ASKER: "Đã huỷ bởi khách hàng",
    CANCELED_REASON: "Lý do",
    NUMBER_OF_DINER: "Số người ăn: ",
    NUMBER_OF_DISH: "Số món ăn",
    TASTE: "Khẩu vị: ",
    EATING_TIME: "Giờ ăn: ",
    BAC: "Miền Bắc",
    TRUNG: "Miền Trung",
    NAM: "Miền Nam",
    FRUIT_DESERT: "Trái cây tráng miệng",
    GO_MARKET: "Đi chợ",
    DISH_WAITING: "Đang chờ",
    CALL_CUSTOMER_TO_UPDATE_DISH: "Trước khi nhận công việc. Vui lòng liên hệ với khách hàng để cập nhật thêm!",
    BUDGET_TO_MARKET: "Tiền đi chợ: ",
    AIR_CONDITIONER_NUMBER: "{{t}} máy",
    ANY_CAPACITY: "Không phân biệt công suất",
    CAPACITY_LESS_THAN: "Công suất dưới {{t}}HP",
    CAPACITY_GREATER_THAN: "Công suất trên {{t}}HP",
    CAPACITY_FROM_TO: "Công suất {{t1}}HP đến {{t2}}HP",
    CAPACITY_LESS_THAN_BTU: "Công suất dưới {{t}} BTU",
    CAPACITY_GREATER_THAN_BTU: "Công suất trên {{t}} BTU",
    CAPACITY_FROM_TO_BTU: "{{t1}} - {{t2}} BTU",
    TYPE_AC: "Loại máy",
    QTY: "Số lượng",
    TASK_AIR_CONDITIONER: "Công việc",
    HOSTEL_NAME: "Tên địa điểm: ",
    TOTAL_AREA: "Tổng diện tích: {{t}}m²",
    IMAGE_TITLE: "Hình ảnh",
    NAME_ROOM: "Tên phòng: {{t}}",
    AREA_ROOM: "Diện tích: {{t}}m²",
    NOTE_ROOM: "Ghi chú: {{t}}",
    HOSTEL_DETAIL: "Thông tin phòng",
    NUMBER_TASKER_ACCEPTED: "CTV đã nhận: ",
    LIST_OF_TASK: "Danh sách công việc",
    BUTTON_SEE_LIST: "Chi tiết",
    TITLE_LIST_CLEANING_TOOL: "Danh sách dụng cụ",
    OVERVIEW: "Tổng quát",
    NUMBER_TOTAL_SOFA: "Tổng số lượng: ",
    SOFA_TYPE: "Loại",
    MATTRESS: "Nệm",
    DRY_CLEANING: "Giặt khô",
    WASHING: "Giặt nước",
    CURTAIN: "Rèm",
    CARPET: "Thảm",
    BED: "Nệm",
    AREA_DISINFECTION: "Diện tích: ",
    DISINFECTION_AREA_FROM_TO: "{{t1}}m² - {{t2}}m²",
    DISINFECTION_AREA_CUSTOM: "{{t}}m²",
    DISINFECTION_PROCEDURE: "Quy trình phun khử khuẩn",
    DISINFECTION_PROCEDURE_CONTENT_TITLE: "Quy trình phun khử khuẩn",
    DISINFECTION_PROCEDURE_CONTENT_1: "1. Chuẩn bị hoá chất để phun khử khuẩn.",
    DISINFECTION_PROCEDURE_CONTENT_2: "2. Tắt hệ thống thông gió, tắt máy lạnh và quạt.",
    DISINFECTION_PROCEDURE_CONTENT_3: "3. Phòng khách: trần nhà, sàn nhà, tường nhà, tủ, cửa, bàn...",
    DISINFECTION_PROCEDURE_CONTENT_4: "4. Phòng ngủ: trần nhà, sàn nhà, tường nhà, kệ tủ, dưới gầm giường...",
    DISINFECTION_PROCEDURE_CONTENT_5: "5. Phòng bếp: trần nhà, sàn nhà, tường nhà, bàn ăn, ghế, kệ tủ...",
    DISINFECTION_PROCEDURE_CONTENT_6: "6. Phòng tắm: trần nhà, Sàn nhà, tường nhà, bồn nước...",
    DISINFECTION_PROCEDURE_CONTENT_7: "7. Kiểm tra lại công việc sau khi hoàn thành.",
    SHOPPING_TIME_LABEL: "Thời gian đi chợ: ",
    DURATION: "{{t}} giờ",
    ESTIMATED_PURCHASE_AMOUNT: "Số tiền đi chợ khách hàng ước tính: ",
    SHOPPING_LIST: "Danh sách cần mua",
    AMOUNT_CHILD_LABEL: "Số lượng trẻ",
    AGE_OF_CHILD: "Độ tuổi",
    NUMBER_OF_CHILD: "Trẻ",
    BUTTON_CONFIRM: "Xác nhận",
    TET_BOOKING: "Công việc Tết",
    YOUR_WORK: "Công việc của bạn",
    YOU_ARE_LEADER: "Bạn là nhóm trưởng của công việc này",
    YOU_ARE_MEMBER: "Bạn là thành viên của nhóm",
    WORK_ACCORDING_TO_ASSIGNMENT: "- Làm việc theo sự phân công của nhóm trưởng.",
    PLEASE_CANCEL_TASK_BEFORE_A_TIME: "- Nếu muốn huỷ công việc, vui lòng gọi cho tổng đài trước lúc bắt đầu công việc {{t}} tiếng để được hỗ trợ.",
    RECEIVE_CASH_FROM_LEADER: "Sau khi hoàn thành công việc, bạn liên hệ nhóm trưởng để nhận tiền.",
    OTHER_PAYMENT: "- Sau khi công việc hoàn thành, tiền sẽ được chuyển vào tài khoản chính của từng thành viên.",
    RECEIVE_CASH: "- Sau khi công việc hoàn thành, nhận tiền mặt từ khách hàng và chia cho các thành viên như thông tin bên dưới.",
    DIVIDE_WORK: "- Phân chia công việc cho bạn và các thành viên.",
    NEED_TO_CONTACT_PARTNER: "- Nhóm trưởng cần liên hệ với những thành viên trong nhóm trước khi công việc bắt đầu. Nếu có thành viên nào không đi làm được, cần liên hệ với tổng đài để được hỗ trợ.",
    TITLE_TASK_WAITING: "Công việc đang chờ",
    BUTTON_CHAT: "Chat",
    BUTTON_CALL: "Gọi ngay",
    MONEY_GET_MORE: "Thu tiền mặt từ khách hàng",
    TASK_WAS_CONFIRMED: "Công việc này đã có người nhận",
    SEE_MORE: "Xem\nthêm",
    CANCEL_TASK_TASKER_SO_FAR_AWAY_TASK_PLACE: 'Bạn không thể hủy với lý do này. Hệ thống chỉ chấp nhận lý do hủy này nếu bạn đang đứng gần nơi làm việc.',
    CANCEL_TASK_LOCATION_NOT_FOUND_TEXT: 'Không xác định được vị trí hiện tại của bạn. Vui lòng bật định vị (GPS), sau đó khởi động lại ứng dụng để tiếp tục hủy công việc.',
    NEW_ASKER_NOTE: 'Đây là khách hàng mới sử dụng dịch vụ, bạn nên liên hệ khách hàng trước khi đi làm.',
    TITLE_LIST_OF_TOOL_FOR_TASKER: "Các dụng cụ vệ sinh cần mang theo khi đến nhà khách hàng",
    TITLE_ALERT_FAQ: "Chú ý",
    MESSAGE_ALERT_FAQ_WAITING: "Nếu bạn rút khỏi công việc này thì bạn sẽ không bị mất phí.",
    MESSAGE_ALERT_FAQ_CONFIRMED: "Nếu bạn hủy công việc này thì bạn sẽ bị mất phí hủy việc theo quy định.",
    ACCIDENT_INSURANCE: 'Công việc được bCare hỗ trợ',
    DESCRIPTION_CANCEL_TASK: "Bạn hãy vào chọn một công việc mới phù hợp hơn nhé!",
    TODAY: "Hôm nay",
    TOMORROW: "Ngày mai",
    QR_CODE:"Nhận dạng QR công việc của bạn",
    COST_INCURRED: "Phát sinh thêm",
    DESCRIPTION_FOR_PROMOTION_LEADER: "Sẽ được chia đều và thêm vào tài khoản khuyến mãi của các thành viên.",
    MONEY_GET_MORE_MEMBER: "Nhận thêm từ nhóm trưởng",
    PAYMENT_MOTHOD_BANKER: "Chuyển khoản",
    PAYMENT_MOTHOD_CASH: "Tiền mặt",
    PAYMENT_MOTHOD_PROMOTION: "Khuyến mãi",
    MONEY_GET_MORE_LEADER: "Nhận thêm từ bạn",
    SOFA_CLEANING_TYPE_MORE: "Nhiều hơn 6 ghế",
    CURTAIN_CHOOSE_SERVICE_ON_SITE: "Dịch vụ làm tại chỗ",
    CURTAIN_CHOOSE_SERVICE_OFF_SITE: "Dịch vụ mang đi",
    WORKED_FOR_ASKER: "Đã từng làm cho nhà này",
    ASKER_OFTEN_USE_SERVICE: "Khách hàng sử dụng dịch vụ thường xuyên",
    TIP: "Tip:",
    CANCEL_FEE: "Phí huỷ việc là ",
    MORNING: "Buổi sáng",
    AFTERNOON: "Buổi chiều",
    EVENING: "Buổi tối",
    VACUUMING_OFFICE_CARPETS: "Hút bụi thảm văn phòng",
    CLEANING_GLASSES: "Lau kính",
    WM_TYPE: "Loại máy giặt",
    WM_SERVICES: "Dịch vụ",
    NUMBER_OF_WM: "Số lượng máy giặt",
    CALL_WITH_MEMBER: "Liên hệ với nhóm viên",
    CALL_WITH_LEADER: "Liên hệ với nhóm trưởng",
  },
  HOME: {
    TAB_HOME: "Trang chủ",
    TAB_BENEFIT: "Phúc lợi",
    TAB_ACCOUNT: "Tài khoản",
    BTASKEE: "bTaskee",
    TAB_MY_TASK: "Đã nhận",
    TAB_NEW_TASK: "Việc mới",
    TAB_NOTIFICATION: "Hộp thư",
    NET_DISCONNECTED: "Không có kết nối. Vui lòng kiểm tra lại mạng!",
    NET_ONLINE: "Đã kết nối!",
  },
  NOTIFICATION_CHAT: {
    TAB_TITLE: "CHAT",
    NOTHING: "Hiện tại không có tin nhắn nào.",
  },
  NOTIFICATION_SYSTEM: {
    TAB_TITLE: "Thông báo",
    INBOX: "Hộp thư",
  },
  TAB_BENEFIT: {
    TRAINING_PROGRAM: "Chương trình đào tạo",
    MONTHLY_REWARD: "Thưởng tháng",
    BREWARD: "bReward",
    COMMUNITY: "Cộng đồng",
    BCARE: "bCare",
    INSURANCE: "Chính sách hỗ trợ tai nạn",
    LEVEL_MONTHLY_REWARD: "Cần làm thêm {{t}} giờ để đạt được mức thưởng tiếp theo trong tháng này",
    MAX_LEVEL: "Chúc mừng bạn đã đạt mức thưởng cao nhất trong tháng này.",
    HOURS_OF_AWARDS: "{{t}} giờ ",
    PROMOTION: "Ưu đãi",
    BREWARD_DETAIL: "Chi tiết ưu đãi",
    LABEL_REWARD_INFO: "Thông tin ưu đãi",
    LABEL_CONDITION: "Điều khoản sử dụng",
    BUTTON_REDEEM: "Đổi quà",
    NUMBER_POINT: "bPoint",
    TITLE_ALERT_CONFIRM_REDEEM: "Xác nhận đổi điểm",
    CONTEXT_ALERT_CONFIRM_REDEEM: "Bạn chắc chắn muốn đổi khuyến mãi này?",
    BUTTON_CONFIRM: "Xác nhận",
    BUTTON_LATER: "Dùng sau",
    FREE: "Miễn phí",
    REDEEM_SUCCESS: "Đổi quà thành công",
    NEW_GIFT: "Mới",
    USED_GIFT: "Đã sử dụng",
    LIST_INCENTIVE_EMPTY: "Chưa có ưu đãi nào.",
    MY_GIFT: "Ưu đãi của tôi",
    EXPIRED_ON: "Hạn sử dụng:",
    EXPIRED: "Hết hạn",
    USED: "Đã dùng",
    DETAIL_REWARD_EMPTY: "Khuyến mãi chưa khả dụng!",
    LABEL_SAVE_SUCCESS: "Thành công",
    MONTHLY_REWARD_DETAIL: "Chi tiết phần thưởng",
    MORE_HOURS:"Cần làm thêm",
    MORE_REWARD:"Phần thưởng tiếp theo",
    TIME_WORK_IN_MONTH:"Thời gian làm việc trong tháng này:",
    REWARD_WORD_IN_MONTH:"Mức thưởng đã đạt được trong tháng:",
    HOURS:"giờ",
    DAY_LEFT:"Số ngày còn lại:",
    DAY:"ngày",
    NEXT_STEP:"Mốc tiếp theo:",
    VIEW_DETAIL:"Xem Chi Tiết",
    DETAIL_REWARD:"Chi tiết phần thưởng",
    MONEY: "{{cost}}{{currency}}",
    NEXT_REWARD: "Mức tiếp theo",
    TRAINING: "Đào tạo",
    COMMUNITY_CONTENT: "Giao lưu và chia sẻ cùng các Chị Ong khác trên toàn quốc để tích luỹ kinh nghiệm.",
    BREWARD_CONTENT: "Nhận “vô vàn quà tặng” khi tích bPoints đổi quà cùng bRewards.",
    TRAINING_CONTENT: "Cùng thăng hạng chất lượng với các khóa đào tạo của bTaskee nào!",
    BCARE_CONTENT: "Cộng Tác Viên không thể thỏa thuận với rủi ro, vì vậy hãy để bCare hỗ trợ Cộng Tác Viên.",
    PREMIUM_CONTENT: "Hãy cùng phấn đấu để trở thành cộng tác viên cao cấp",
    EMPTY_DATA: "Vui lòng quay lại sau khi kích hoạt tài khoản của bạn để nhận các lợi ích đặc biệt dành riêng cho cộng tác viên bTaskee.",
    SEARCH: "Tìm kiếm",
    SEARCH_VOUCHER: "Tìm kiếm ưu đãi",
    ACCOUNT_LOCK: "Đã khóa"
  },
  TAB_ACCOUNT: {
    PROFILE: "Thông tin",
    FINANCE: "Tài chính",
    WEEKLY_REPORT: "Báo cáo tuần",
    HISTORY_INCOME: "Lịch sử thu nhập",
    INCOME:"Thu nhập",
    SERVICES: "Dịch vụ",
    DISTRICTS: "Quận",
    LEVEL: "Hạng",
    PREMIUM: "Premium",
    TITLE_QA_CODE: "Nhận dạng QR của bạn",
    YOUR_REFERRAL_CODE: "Mã giới thiệu của bạn",
    COPY: "Sao chép",
    LABEL_COPY: "Đã sao chép",
    SEE_INFORMATION: "Xem thêm",
    LOGOUT: "Đăng xuất",
    LOGOUT_CONFIRM: "Bạn có chắc chắn muốn đăng xuất không?",
    LEVEL_1: "Nghiệp dư",
    LEVEL_2: "Chuyên nghiệp",
    HOLDING_ACCOUNT: "Tiền công việc tạm tính: ",
    MAIN_ACCOUNT: "Tài khoản chính",
    PROMOTION_ACCOUNT: "Tài khoản khuyến mãi: ",
    INCOME_THIS_WEEK: "Thu nhập trong tuần này",
    COMPLETED_TASK: "Công việc đã hoàn thành",
    INCOME_TOTAL: "Tổng thu nhập",
    INCOME_IN_MONTH: "Thu nhập tháng này",
    TOPUP: "Nạp tiền",
    WITHDRAW: "Rút tiền",
    AMOUNT_WITHDRAW: "Tiền chờ rút",
    AMOUNT_WITHDRAW_NOTE: "Đang được hệ thống xử lý",
    TRANSACTION_HISTORY: "Lịch sử giao dịch",
    AMOUNT: "Số tiền",
    BALANCE: "Số tiền khả dụng",
    WITHDRAW_NOTE: "Lưu ý: Phải còn ít nhất {{amount}} {{currency}} trong tài khoản để có thể tiếp tục nhận việc",
    NEXT: "Tiếp tục",
    CONFIRMATION: "Xác nhận",
    CONFIRMATION_WITHDRAW: "Bạn có chắc chắn muốn rút tiền khỏi tài khoản?",
    BANK_ACCOUNT: "Tài khoản",
    FMAIN_ACCOUNT_NOTE: "là tài khoản chứa số dư hiện tại mà cộng tác viên có thể sử dụng để nhận việc hoặc rút tiền khi đủ điều kiện.",
    PROMOTION_ACCOUNT_NOTE: "là tài khoản chứa số tiền mà cộng tác viên được thưởng, hỗ trợ, các công việc mà khách hàng sử dụng mã KM sẽ được cộng vào đây và chỉ được sử dụng để nhận việc.",
    ON_HOLD_ACCOUNT: "Tiền công việc tạm tính",
    ON_HOLD_ACCOUNT_NOTE: "là số tiền bị giữ lại khi cộng tác viên đang nhận công việc. Nếu cộng tác viên hoàn thành công việc số tiền này sẽ trừ vào tài khoản khuyến mãi, khi hết tài khoản khuyến mãi sẽ chuyển sang trừ vào tài khoản chính",
    PAYOUT_NAME: "Yêu cầu rút tiền",
    PAYOUT_WAIT: "Đang xử lý",
    PAYOUT_PAID: "Đã xử lý",
    PAYOUT_CANCELED: "Đã huỷ",
    PAYOUT_REJECTED: "Đã từ chối",
    PAYOUT_SUCCESS: "Tạo yêu cầu thành công",
    MONTH: "Tháng",
    WEEK: "Tuần",
    STAR: "Sao",
    BELOW: "Dưới trung bình",
    TASK: "Công việc",
    INCREASE_TASK: "Tăng {{task}} công việc so với tuần trước",
    DECREASE_TASK: "Giảm {{task}} công việc so với tuần trước",
    GOOD_REVIEW: "Đánh giá tốt",
    BAD_REVIEW: "Cần cải thiện",
    TASK_HISTORY: "Lịch sử công việc",
    INFORMATION: "Thông tin",
    EMPTY_TASK_IN_MONTH: "Không có công việc nào trong tháng này",
    EMPTY_TRANSACTION_IN_MONTH: "Không có giao dịch nào trong tháng này",
    LIST_OF_EMPLOYEE: "Danh sách nhân viên",
    REVIEW: "Đánh giá",
    ERROR_ON_HOLD_ACCOUNT_WHEN_WITHDRAW: "Bạn đã có 1 yêu cầu rút tiền đang chờ xử lý",
    TRANSACTION: "Giao dịch",
    PAYOUT: "Yêu cầu",
    LABEL_TRANSACTION_TAB: "Gần đây",
    EMPTY_TRANSACTION: "Bạn chưa có giao dịch nào",
    EMPTY_PAYOUT: "Bạn không có yêu cầu nào",
    TITLE_CHECK_NOTIFICATION: "Kiểm tra thông báo",
    BUTTON_CHECK_NOTIFICATION: "Gửi thông báo",
    TITLE_TEST_NOTIFICATION: 'Thông báo đang hoạt động tốt',
    INFO_TEST_NOTIFICATION: 'Để kiểm tra thông báo máy sẽ tự động tắt ứng dụng, bạn có muốn tiếp tục thực hiện?',
    TITLE_CARD_SHARE: "Chia sẻ",
    CONTENT_CARD_SHARE: "Chia sẻ để nhận các ưu đãi hấp dẫn",
    BUTTON_VIEW_MORE: "Xem thêm",
    TEXT_QR: "Vui lòng đưa ra mã QR của bạn để khách hàng có thể nhận dạng.",
    LABEL_DELETE_ACCOUNT: "Xoá tài khoản",
    TEXT_DELETE_ACCOUNT: "Bạn có chắc chắn muốn xoá tài khoản hiện tại không?",
    TITLE_RESTART_APP: "Khởi động lại ứng dụng",
    BUTTON_RESTART_APP: "Khởi động ngay",
    TEXT_RESTAR_APP: "Bạn có chắc chắn muốn khởi động lại ứng dụng không?",
    NUMBER_ACCEPT_TASK: "Hiện đang có {{numberTasks}} công việc",
    NUMBER_OF_POINT_LABEL: "Điểm ưu đãi",
    NUMBER_OF_POINT: "{{t}} points"
  },
  CHAT: {
    TITLE: "Tin nhắn",
    TRANSLATING: "Dịch ...",
    PREPARED_MESSAGE_THANK: "Cảm ơn bạn rất nhiều.",
    PREPARED_MESSAGE_WAIT_ASKER: "Tôi đang trên đường về nhà. Bạn vui lòng đợi tôi một chút nhé. Cảm ơn!",
    GPS_NOT_FOUND: "Không tìm được vị trí!",
    SERVICE_REQUEST_GPS: "Vui lòng mở GPS để sử dụng dịch vụ này!",
    PT1_MAP_POPUP_PERMISSION_REQUEST_GPS_CLOSE: "Đóng",
    OPEN_SETTINGS: "Mở cài đặt",
    TYPE_A_MESSAGE: "Nhập tin nhắn",
    MODAL_CONFIRM_SHARE_LOCATION_TITLE: "Bạn có muốn chia sẻ vị trí hiện tại?",
    PREPARED_MESSAGE_CONFIRMATION: "Xin chào, tôi đã nhận làm công việc của bạn. Tôi sẽ đến đúng giờ.",
    PREPARED_MESSAGE_REQUIRE_ADDRESS_EXACTLY: "Vui lòng cho tôi biết địa chỉ chính xác của nơi làm việc. Cảm ơn!",
    PREPARED_MESSAGE_COMING: "Tôi đang trên đường đến, vui lòng giữ liên lạc!",
    PREPARED_MESSAGE_WAIT_20_MINUTES: "Xin chào tôi đã đến nơi nhưng không liên hệ được với bạn. Tôi sẽ chờ bạn 20p, nếu vẫn không liên hệ được tôi xin phép hủy công việc.",
    PREPARED_MESSAGE_WAITED_20_MINUTES: "Tôi đã đợi bạn 20p nhưng vẫn không liên hệ được, tôi xin phép hủy công việc.",
    PREPARED_MESSAGE_AT_RECEPTION: "Tôi đang đứng tại quầy lễ tân, vui lòng xuống đón tôi.",
    LABEL_CHAT_WITH_BTASKEE: "Chat với bTaskee"
  },
  TRAINING_INPUT: {
    TITLE: "Bài kiểm tra",
    LOADING_TITLE: "Đang lấy thông tin",
    INSTRUCTION_PASS_TEST: "Lưu ý: Bài kiểm tra cần đạt 80% kết quả mới đạt yêu cầu, do đó bạn hãy đọc thật kỹ trước khi trả lời nhé!",
    ERROR: "Lấy thông tin bài kiểm tra thất bại. Vui lòng thử lại!",
    START: "Bắt đầu làm bài",
    RELOAD: "Thử lại",
    FINISH: "Nộp bài",
    ACCEPT_TEST_CONFIRMATION: "Bạn đã đọc kỹ lưu ý và muốn làm bài kiểm tra?",
    FINISH_TEST_CONFIRMATION: "Bạn chắc chắn muốn nộp bài!",
    FAILD: "Bạn chưa đạt bài kiểm tra, vui lòng gọi tổng đài để được hỗ trợ.",
    RESULT_TEST_FAILD: "Bạn chưa vượt qua bài kiểm tra. Bạn còn {{t}} lần làm lại. Hãy cẩn thận nhé!",
    RESULT_TEST_FAILD_LIMITED: "Bạn đã không vượt qua được bài kiểm tra. Vui lòng liên hệ với tổng đài để biết thêm chi tiết!",
    SEE_RESULT: "Xem kết quả",
    GRADING_TEST: "Đang kiểm tra kết quả... Vui lòng chờ!",
    QUIT_TEST: "Thoát bài kiểm tra",
    TRAINING_TASKER_PASS_TITLE: "Chào mừng bạn đến với bTaskee",
    PREPARE_PROFILE: "Vui lòng chuẩn bị hồ sơ bao gồm:",
    UNVERIFIED_TASKER_PROFILE_1: "Sơ yếu lý lịch:",
    UNVERIFIED_TASKER_PROFILE_2: "02 CMND (Photo):",
    UNVERIFIED_TASKER_PROFILE_3: "01 Hộ khẩu (Photo):",
    UNVERIFIED_TASKER_PROFILE_4: "01 Giấy chứng thực hạnh kiểm:",
    NOTE_FOR_UNVERIFIED_TASKER_PROFILE: "Các giấy tờ trên đều phải được công chứng không quá 6 tháng.",
    APPLY_YOUR_PROFILE_AT_COMPANY_NOTE: "Sau đó đến nộp hồ sơ trực tiếp tại một trong các văn phòng của bTaskee tại khu vực Thành Phố bạn đăng ký.",
    TIME_TO_APPLY: "Thời gian đến nộp hồ sơ:",
    MORNING_TO_APPLY: "Buổi sáng:",
    AFTERNOON_TO_APPLY: "Buổi chiều:",
    TIME_MORNING: "09h00.",
    TIME_AFTERNOON: "14h00.",
    ARRIVE_APPLY_LATE_NOTE: "Lưu ý: Nếu bạn đến  muộn sẽ phải hẹn qua ngày khác.",
    UNVERIFIED_TASKER_SUBMITION_ADDRRESS: "Địa chỉ nộp hồ sơ:",
    CALL_SUPPORT_FOR_MORE_DETAIL: "Gọi hỗ trợ nếu bạn cần thêm thông tin chi tiết",
    PHONE: "Số điện thoại: {{t}}",
    CALL_WITH_HR: "Xin vui lòng liên hệ với nhân sự trước khi đến để được sắp xếp thời gian và nơi gửi xe cho thuận tiện.",
    DESCRIPTION_PLAY_VIDEO: "Hãy ghi nhớ bài học rõ hơn với phần tóm tắt bên dưới",
    NEXT: "Tiếp tục",
    DONE: "Hoàn thành",
    TRAINING_PROGRAM: "Chương trình đào tạo",
    READING_TIME: "Thời gian học:",
    BY_MINUTUES: "phút",
    TRAINING: "Bài học",
    TRAINING_DESCRIPTION: "Hãy dành một không gian trống & thời gian rảnh để sự tập trung của bạn vào bài học là cao nhất.",
    TEST: "Bài kiểm tra",
    TEST_DESCRIPTION: "Hãy đọc kỹ bài học tóm tắt để làm bài kiểm tra hiệu quả hơn",
    PASS: "Đã đạt",
    FAILED: "Chưa đạt",
    REMAINING_TIME: "Số lần làm còn lại:",
    LESSON: "Bài {{t}}",
    TRAINING_DETAIL_TITLE: "Bài học chi tiết",
    SUMMARY: "Tóm tắt",
    FINISH_TEST_SUCCESS: "Chúc mừng đã hoàn thành bài kiểm tra",
    TEST_FAILD_LIMITED: "Bạn đã không vượt qua được bài kiểm tra",
    TEST_AGAIN: "Làm lại ngay",
    COME_BACK_LATER: "Quay lại sau",
    NUMBER_OF_CORRECT_ANSWER: "Số câu trả lời đúng: ",
    TAKE_THE_TEST: "Làm bài kiểm tra ngay!",
    INFO_TEST: "Kết quả: {{t1}}/{{t2}}",
    DES_SEE_TEST: "Bài kiểm tra sẽ được mở sau khi xem hết Video",
    CORRECT: "Đúng",
    WRONG: "Sai",
  },
  TRAINING_PREMIUM: {
    TITLE: "Đào tạo Premium",
    SHARE: 'Chia sẻ',
    TASKER_PREMIUM_TITLE: 'Bằng chứng nhận',
    TASKER_PREMIUM_SUB_TITLE: 'Cộng tác viên cao cấp',
    CONTENT: "Các quy định về việc cấp bằng cộng tác viên cao cấp",
    PASS_TITLE: "Chúc mừng bạn đã vượt qua bài kiểm tra",
    REGULATIONS_TASKER_PREMIUM: 'Quy định hoạt động đối với CTV cao cấp',
    WITHDRAW_TASKER_PREMIUM_TITLE: 'Quy định hoạt động đối với CTV cao cấp',
    REGULATIONS_TASKER_PREMIUM_1: 'Áp dụng các quy định và thỏa thuận theo Biên Bản Thỏa Thuận Hợp Tác đã ký khi đăng ký tham gia trở thành cộng tác viên của bTaskee.',
    REGULATIONS_TASKER_PREMIUM_2: 'Cộng tác viên cao cấp sẽ bị **TƯỚC BẰNG** khi vi phạm quy định về:',
    REGULATIONS_TASKER_PREMIUM_2_1: 'Thương lượng làm riêng với Khách hàng của bTaskee ngoài hệ thống',
    REGULATIONS_TASKER_PREMIUM_2_2: 'Vi phạm các vấn đề về đồng phục, tác phong.',
    REGULATIONS_TASKER_PREMIUM_2_3: 'Không đảm bảo chất lượng dịch vụ',
    REGULATIONS_TASKER_PREMIUM_2_4: 'Vi phạm các vấn đề về thái độ ứng xử.',
    REGULATIONS_TASKER_PREMIUM_3: 'Khi bị tước bằng cộng tác viên sẽ:',
    REGULATIONS_TASKER_PREMIUM_3_1: 'Không được nhận công việc Premium',
    REGULATIONS_TASKER_PREMIUM_3_2: 'Không được tham gia chương trình vinh danh hằng tháng.',
    REGULATIONS_TASKER_PREMIUM_4: 'Hằng ngày sẽ kiểm tra và:',
    REGULATIONS_TASKER_PREMIUM_4_1: 'Thu hồi bằng nếu Tasker vi phạm.',
    REGULATIONS_TASKER_PREMIUM_4_2: 'Cấp lại bằng nếu Tasker đạt điều kiện.',
    CONDITION_TASKER_PREMIUM_TITLE: 'Điều kiện để nâng cấp trở thành CTV cao cấp của bTaskee',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_1: 'Có điểm trung bình sao từ 4.80 trở lên.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_2: 'Có trên 10 Khách hàng ưa thích.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_3: 'Có đầy đủ bộ công cụ dụng cụ theo tiêu chuẩn bTaskee.',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_4: 'Đã có Máy hút bụi',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_5: 'Đã có balo bTaskee',
    CONDITION_TASKER_PREMIUM_DESCRIPTION_6: 'Đã hoàn thành ít nhất 200 công việc trên hệ thống bTaskee.',
    TITLE_TASKER_PREMIUM: "Bắt đầu ngay",
    LABEL_START_NOW: "Để trở thành cộng tác viên cao cấp",
  },
  INTRO_APP: {
    BUTTON_START: "Bắt đầu",
    TITLE: "Lợi ích cùng bTaskee",
    LEARN_MORE: "Tìm hiểu thêm",
    START_WORKING: "Hãy biến thời gian rảnh thành thu nhập!",
    ALREADY_ACCOUNT: "Bạn đã có tài khoản?",
    FLEXIBLE_TIME: "Thời gian linh động",
    HIGH_INCOME: "Thu nhập hấp dẫn",
    COMMUNITY_REWARD: "Cộng đồng & Chính sách đãi ngộ tốt",
    FLEXIBLE_TIME_1: "Thời gian làm việc linh động và tùy thuộc vào lựa chọn của bạn",
    FLEXIBLE_TIME_2: "Chuyển hóa thời gian rảnh của bạn thành thu nhập",
    HIGH_INCOME_1: "Thu nhập lên đến 20 triệu/tháng nếu bạn tích cực và siêng năng theo dõi nhận việc.",
    COMMUNITY_REWARD_1: "Cộng đồng lớn kết nối, chia sẻ và tôn vinh giá trị cao đẹp của con người và nghề Giúp việc nhà",
    COMMUNITY_REWARD_2: "Cộng tác viên được hưởng chính sách hỗ trợ lên đến 100 triệu đồng.",
    FLEXIBLE_TIME_ID:"Chủ động lựa chọn những công việc phù hợp với bạn. Hãy biến thời gian rảnh của bạn thành thu nhập.",
    HIGH_INCOME_ID:"Bạn có thể nhận được mức thu nhập hấp dẫn chỉ với thời gian rảnh rỗi của mình.",
    COMMUNITY_REWARD_ID:"Cùng tham gia vào một cộng đồng hiện đại, năng động và thiết thực.",
    FLEXIBLE_TIME_TITLE_TH:"Thời gian linh động",
    FLEXIBLE_TIME_CONTENT_TH:"Thời gian làm việc linh động và tùy thuộc vào lựa chọn của bạn, chuyển hóa thời gian rảnh của bạn thành thu nhập",
    HIGH_INCOME_TITLE_TH:"Thu nhập hấp dẫn",
    HIGH_INCOME_CONTENT_TH:"Thu nhập lên đến 20 triệu/tháng nếu bạn tích cực và siêng năng theo dõi nhận việc.",
    COMMUNITY_REWARD_TITLE_TH:"Cộng đồng & Chính sách đãi ngộ tốt",
    COMMUNITY_REWARD_CONTENT_TH:"Cộng đồng lớn kết nối, chia sẻ và tôn vinh giá trị cao đẹp của con người và nghề Giúp việc nhà, cộng tác viên được hưởng chính sách hỗ trợ lên đến 100 triệu đồng.",
  },
  SETTINGS: {
    SETTINGS: "Cài đặt",
    LANGUAGE: "Ngôn ngữ",
    NOTIFICATION: "Thông báo",
    NOTIFICATION_TASK: "Nhận thông báo công việc",
    NOTIFICATION_ON: "Mở",
    NOTIFICATION_OFF: "Tắt",
    FEE_SCHEDULE: "Lịch rảnh",
    YOUR_WORKTIME: "Thời gian rảnh",
    BUSY_TIME: "Thời gian bận",
    REMIND: "Nhắc nhở trước",
    MINUTE: "Phút",
    HOURS: "Giờ",
    MORNING: "Sáng",
    AFTERNOON: "Chiều",
    EVENING: "Tối",
    UPDATE: "Cập nhật",
    NOTE_TASKER_UPDATE_SCHEDULE: "Bạn chỉ được cập nhập 1 lần (nếu muốn thay đổi hãy liên hệ với bTaskee).",
    TEXT_VIBRATION:"Rung khi có công việc mới"
  },
  TOPUP: {
    MIN_COST_TOPUP: "Số tiền nạp tối thiểu:",
    INSTRUCTTION_NOTE: "Tài khoản của bạn sẽ được cập nhật trong vòng 24 giờ kể từ lúc chuyển tiền.",
    BANK_TRANFER: "Ngân hàng:",
    BANK_INFO_ACCOUNT_HOLDER: "Chủ tài khoản:",
    BANK_INFO_ACCOUNT_NUMBER: "Số tài khoản:",
    BANK_INFO_TRANFER_CONTENT: "Nội dung: ",
    BANK_INFO_CONTENT_SYNTAX: "Họ và tên số điện thoại của bạn",
    LBL_EX_DEPOSITE: "Ví dụ: Nguyễn Thị A 0123456789",
    NOTE_DEPOSIT_MONEY: "Tiền nạp vào tài khoản chỉ được sử dụng để nhận việc, không sử dụng để chi trả các khoản khác như mua balo, đồng phục v.v...",
    SAVE_IMAGE: "Lưu hình ảnh",
    SAVE_IMAGE_SUCCESS: "Lưu hình ảnh thành công",
    BTASKEE_THAILAND: "bTaskee (Thái Lan)",
    METHOD: "Cách nạp tiền",
    OPEN_BANK_APP: "Mở app ngân hàng",
    SCAN: "Quét mã",
    SELECT_PHOTO: "Chọn hình ảnh",
    BUTTON_DONE: "Xong",
    MIN_MONEY: "Số tiền tối thiểu có thể nạp",
    MAX_MONEY: "Số tiền tối đa có thể nạp",
    IMAGE_DOWNLOAD_PERMISSTION: "Quyền tải xuống hình ảnh",
    IMAGE_DOWNLOAD_PERMISSTION_MESS: "Cần có sự cho phép của bạn để lưu hình ảnh vào thiết bị",
    COMING_SOON: "Sắp ra mắt",
    NOTE:"Lưu ý:",
    QR_CODE: "Quét mã QR",
    NOTE_LABEL: "Ghi chú: ",
    QR_NOTE: "Làm thế nào để nạp tiền online qua mã QR?",
    STEP_1: "Nhấn Lưu để tải ảnh mã QR về máy.",
    STEP_2: "Mở ứng dụng ngân hàng của bạn",
    STEP_3: "Vào phần Quét hoặc Quét QR, sau đó chọn ảnh mã QR mà bạn vừa lấy từ thư viện ảnh của mình.",
    STEP_4: "Bạn hãy nhập số tiền muốn nạp vào tài khoản, lưu ý số tiền nạp tối thiểu là {{money}}.",
    TOPUP_TO_BANK: "Nạp vào số tài khoản",
  },
  WITHDRAW: {
    NOTE: "Lưu ý: Phải còn ít nhất {{amount}}{{currency}} trong tài khoản để có thể tiếp tục nhận việc",
    SCOPE_OF_MONEY: "Số tiền bạn có thể rút từ {{t1}} đến {{t2}}",
    VALID_AMOUNT: "Số tiền mỗi lần rút từ {{minCost}}{{currency}} đến {{maxCost}}{{currency}}",
    ERROR_SCOPE_OF_MONEY: "Số tiền bạn nhập không nằm trong khoảng cho phép rút. Vui lòng thử lại!",
    MONEY: "{{cost}}{{currency}}",
    RECEIPT_OF_MONEY_INFO: 'Yêu cầu rút tiền của bạn sẽ được duyệt vào thứ 3 và thứ 6 hàng tuần. Ngân hàng sẽ chuyển tiền đến bạn trong vòng 1-3 ngày làm việc.',
    TECHCOMBANK: "Ngân hàng TMCP Kỹ thương Việt Nam",
    TRANSFER_FEE: "Phí rút tiền",
    ERROR_TCBANK_NUMBER: "Bạn chưa cung cấp số tài khoản ngân hàng Techcombank của bạn. Vui lòng cập nhật thông tin ngân hàng của bạn trước khi rút tiền.",
    UNABLE_TO_WITHDRAW_1: 'Bạn cần ít nhất ',
    UNABLE_TO_WITHDRAW_2: ' trong tài khoản chính để có thể rút tiền!',
    LABEL_NOTE: "Lưu ý: ",
    MIN_MONEY_NOTE: "Để tiếp tục nhận việc, tài khoản chính của bạn cần có ít nhất: ",
    MIN_MONEY: "Số tiền tối thiểu mỗi lần rút: ",
    KASIKORN_BANK: "Kasikornbank",
    RECEIPT_OF_MONEY_INFO_TH: 'Bạn sẽ nhận được tiền vào tài khoản vào thứ 3 hoặc thứ 6 hàng tuần từ 18h trở đi, yêu cầu này phải được yêu cầu trước ít nhất 1 ngày, nếu yêu cầu vào thứ 3 hoặc thứ 6 sẽ được tính là chu kỳ rút tiền tiếp theo. Bạn nên tạo yêu cầu rút tiền vào Thứ Hai hoặc Thứ Năm để nhận được số tiền sớm nhất.',
  },
  ABOUT_BTASKEE: {
    TITLE: "Về bTaskee",
    DESCRIPTION: "Hoạt động",
  },
  NEW_VERSION_APP: {
    CONTENT_UPDATE_APP: "Có phiên bản mới. Vui lòng cập nhật để trải nghiệm những tính năng mới nhất.",
    TITLE_BUTTON_UPDATE_VERSION: "Thông báo",
    MAINTENANCE_APP_TITLE: "Đang cập nhập hệ thống. Vui lòng quay lại sau.",
    NEW_VERSION_BUTTON: "Cập nhập ngay",
  },
  CAR_ADVERTISING: {
    YOUR_REFERRAL_CODE: "Mã giới thiệu của bạn",
    BUTTON_SHARE_REFERRAL_CODE: "Chia sẻ mã giới thiệu",
    NUMBER_PEOPLE_REGISTER_WITH_REFERRAL: "Số khách hàng đã tạo tài khoản",
    NUMBER_PEOPLE_DONE_TASK: "Số khách hàng đã đặt ca đầu tiên",
    TITLE_HISTORY_TRANSACTION: "Lịch sử giao dịch",
    COST_AND_CURRENCY: "{{cost}} {{currency}}",
    INVITE_ASKER_TEXT_HEAD: "Đăng ký tài khoản với mã giới thiệu",
    INVITE_ADVERTISING_SHARE_TEXT: "Đăng ký trở thành cộng tác viên với mã giới thiệu {{referralCode}} để nhận ngay {{referralValue}} vào tài khoản khuyến mãi sau khi bạn hoàn thành công việc đầu tiên.\nHoặc nhận ngay voucher {{voucherValue}} khi bạn đăng ký tài khoản khách hàng thành công với mã giới thiệu {{referralCode}}",
    INVITE_ASKER_TEXT_TAIL: "để nhận được voucher giảm giá sau khi công việc đầu tiên hoàn tất.",
},
  MONTHLY_REWARD: {
    TITLE: "Nhận thưởng chi tiết",
    CONGRATULATIONS: "Chúc mừng bạn!",
    BUTTON_REWARD: "Nhận thưởng ngay",
  },
  LAUNDRY: {
    TITLE_WAITING_COLLECT: "Chờ nhận",
    TITLE_WAITING_RETURN: "Chờ trả",
    RETURN_DATE: "Thời gian trả đồ: ",
    CHECK_AND_CONFIRM: "Kiểm tra và xác nhận",
    PICK_UP_CLOTHES: "Nhận đồ",
    COLLECTION_DATE: "Thời gian nhận đồ: ",
  },
  SUPPORT:{
    TITLE: "Hỗ trợ",
    DESCRIPTION: "Hỗ trợ nhân sự và thời gian làm việc.",
    TITLE_DAILY_WORK: "Hỗ trợ công việc hằng ngày",
    TITLE_PERSONNEL_WORK:"Hỗ trợ vấn đề về nhân sự",
    TITLE_PERSONNEL_WORK2:"(mở, khóa tài khoản, xin tạm nghỉ...)",
    TIME_DAILY_WORK: "Thứ 2 - Thứ 7:",
    TIME_PERSONNEL_WORK:"Thứ 2 - Thứ 6:",
    SATURDAY:"Thứ 7",
    SUNDAY:"Chủ nhật",
    TIME_IN_WORK:"Giờ hành chính",
    OUT_OF_TIME:"Ngoài giờ",
    SWITCH_BOARD:"Gọi tổng đài",
    TEXT_OUT_OF_TIME:"Tổng đài không hỗ trợ ngoài giờ làm việc."
  },
  RATING: {
    BUTTON_RATING: "Đánh giá",
    TASKER_RATE_ASKER_TITLE: "Đánh giá khách hàng",
    TASKER_RATE_ASKER_THANK: "Cảm ơn bạn đã hoàn thành công việc này. Bạn đánh giá thế nào về khách hàng của bạn?",
    TASKER_RATE_ASKER_TASK_NOT_FOUND: "Không thể đánh giá công việc này bây giờ. Vui lòng bỏ qua.",
    ASKER_ONE_STAR_LABEL: "Tệ",
    ASKER_TWO_STAR_LABEL: "Không tốt",
    ASKER_THREE_STAR_LABEL: "Chưa tốt",
    ASKER_FOUR_STAR_LABEL: "Tốt",
    ASKER_FIVE_STAR_LABEL: "Tuyệt vời",
    ASKER_WHAT_WENT_WRONG: "Điều gì bạn muốn phản ánh?",
    ASKER_WHAT_COULD_BE_BETTER: "Điều gì bạn mong muốn tốt hơn?",
    ASKER_WHAT_GOOD: "Điều gì tuyệt vời ở khách hàng?",
    ASKER_RATING_REVIEW: "Nhận xét của bạn",
    ASKER_THANK_YOU_NOTE: "Cảm ơn đến khách hàng",
    ASKER_RATING_BAD_1: "Lôi kéo làm riêng",
    ASKER_RATING_BAD_2: "Môi trường làm việc nguy hiểm",
    ASKER_RATING_BAD_3: "Quá tải công việc",
    ASKER_RATING_BAD_4: "Không liên lạc được",
    ASKER_RATING_BAD_5: "Không thân thiện",
    ASKER_RATING_OTHER: "Khác",
    ASKER_RATING_GOOD_1: "Không nên lôi kéo làm riêng",
    ASKER_RATING_GOOD_2: "Đảm bảo an toàn lao động",
    ASKER_RATING_GOOD_3: "Cân đối công việc và thời gian khi đặt trên ứng dụng",
    ASKER_RATING_GOOD_4: "Nên giữ liên lạc khi sắp đến giờ làm",
    ASKER_RATING_GOOD_5: "Thân thiện hơn",
    FRIENDLY: "Thân thiện",
    POLITE: "Lịch sự",
    CHEERFUL: "Vui vẻ",
    SUPPORT: "Sẵn sàng giúp đỡ",
    TASK_SUCCESS: "Công việc đã hoàn thành",
    NOT_RATING: "Chưa đánh giá",
    YOUR_REVIEW: "Nhận xét của bạn",
    LENGTH_OF_TEXT: "{{t}}/140 từ",
  },
  FILTER_NEW_TASK: {
    TITLE: "Lọc theo thời gian",
    BY_CREATED_AT: "Mới đăng",
    BY_DATE: "Công việc sắp làm",
    BY_AREA: "Chỉ hiện công việc trong khu vực đã đăng ký",
  },
  SHARE_SCREEN: {
    YOUR_REFERRAL_CODE: "Mã giới thiệu của bạn",
    TEXT_SHARE_SUCCESS: "Làm thế nào để chia sẻ thành công",
    SHARE_WITH_YOUR_FRIEND: "Chia sẻ với bạn bè",
    FRIEND_DOW_APP: "Bạn bè của bạn trở thành CTV mới:",
    BE_REWARDED: "Bạn bè của bạn trở thành khách hàng",
    FAQ: "FAQ",
    GIFTS_FOR_YOU_FOR_ME: "Quà tặng cho bạn và cho tôi",
    DESCRIPTION_BE_REWARDED: "Lúc này chỉ cần hướng dẫn tận tình và đọc kỹ phần FAQ bên dưới để việc hướng dẫn được chính xác nhé!",
    DESCRIPTION_FRIEND_DOW_APP: "Bạn bè/khách hàng cứ theo nhấp vào link giới thiệu, tải app và nhập mã giới thiệu của bạn.",
    DESCRIPTION_SHARE_WITH_YOUR_FRIEND: "Hãy nhấn vào biểu tượng CHIA SẺ dưới cùng để chia sẻ mã giới thiệu của riêng bạn.",
    HOW_GET_REWARD: "Làm thế nào để bạn bè tôi nhận được phần thưởng ?",
    DONE_GET_REWARD: "Khi đăng ký tài khoản hãy nhớ nhập CHÍNH XÁC mã giới thiệu của bạn nhé.",
    REFERRAL_REWARD: "Phần thưởng giới thiệu",
    TOTAL_BONUS: "Tổng tiền thưởng đã nhận",
    SEE_MORE: "Xem tất cả",
    JOIN_DAY: "Tham gia ngày",
    ADD_TO_PROMOTION: "(Tiền sẽ được cộng vào tài khoản khuyến mãi của bạn.)",
    SHARE_REFERRAL_CODE: "Chia sẻ",
    TITLE_SHARE_REFERRAL_CODE: "Chia sẻ",
    SUB_TITLE_SHARE_REFERRAL_CODE:"Chia sẻ cho",
    TEXT_Q1: "Q1",
    LABEL_COPY: "Đã sao chép",
    SHARE_WITH_ASKER: "Chia sẻ cho Khách hàng",
    SHARE_WITH_TASKER: "Chia sẻ cho CTV",
    DEEPLINK_TITLE: 'bTaskee Partner - Ứng dụng dành cho cộng tác viên bTaskee',
  },
  KIT_CHEMICALS:{
    TITLE: "Bộ dụng cụ và hóa chất",
    GET_KITS: "Bộ dụng cụ",
    GET_CHEMICALS: "Bộ hoá chất",
    GET_KITS_AND_CHEMICALS_DETAIL: "Chi tiết bộ dụng cụ và hoá chất",
    PRESS_BUY_KITS_AND_CHEMICALS: "Xem nơi bán",
    KITS_AND_CHEMICALS_AMOUNT: "Số lượng",
    KITS_AND_CHEMICALS_PRICE: "Giá tham khảo trên 1 sản phẩm",
    KITS_AND_CHEMICALS_MONEY: "Thành tiền",
  },
  DELETE_ACCOUNT:{
    TITLE:"Xoá tài khoản",
    TURN_BACK:"Quay lại",
    TEXT_AGREE_DELETE_ACCOUNT:"Tôi đồng ý với điều khoản và xác nhận xoá tài khoản",
    DELETE_ACCOUNT_TITLE_REASON:"Lý do",
    DELETE_ACCOUNT_SUB_REASON:"Lý do bạn xoá tài khoản",
    PLACEHOLDER_TEXT_INPUT:"Vui lòng nhập lý do bạn muốn xoá tài khoản.(Vui lòng nhập ít nhất {{t}} ký tự)",
    TEXT_TITLE_DELETE:"Bạn không muốn là bTasker nữa ư?",
    TEXT_INFO_ACCOUNT:"• Thông tin tài khoản",
    TEXT_CONFIRM:"Bạn vui lòng xác nhận rằng việc xoá tài khoản sẽ làm mất những thông tin sau:",
    TEXT_1:"• Tài khoản bị xoá bạn sẽ không thể khôi phục lại được.",
    TEXT_2:"• Đồng thời bạn sẽ không thể dùng email và số điện thoại của tài khoản này để tạo tài khoản mới.",
    TEXT_TRANS_INFO:"• Thông tin giao dịch",
    TEXT_TRANS_INFO_1:"Mọi thông tin liên quan đến giao dịch, địa chỉ đã lưu, phương thức thanh toán",
    TEXT_PRIVILEGES_BENEFIT:"• Ưu đãi và quyền lợi",
    TEXT_PRIVILEGES_BENEFIT_1:"Bạn sẽ mất tất cả ưu đãi, voucher và quyền lợi của cộng tác viên",
    TEXT_INFO_ACCOUNT_1:"Các thông tin cá nhân liên quan đến tài khoản Tasker của bạn",
    TEXT_INFO_ACCOUNT_2:"bTaskee sẽ không chịu trách nhiệm cho bất kì mất mát nào về thông tin, dữ liệu hoặc tiền sau khi đã xoá tài khoản.",
    DELETE_ACCOUNT_SUCCESS: "Tài khoản của bạn đã bị xoá vĩnh viễn trên hệ thống của bTaskee. Chúng tôi rất tiếc vì sự bỏ lỡ của bạn. Mong bạn sẽ quay lại sớm nhất có thể.",
    ARE_YOU_SURE: "Bạn có chắc chắn muốn xoá tài khoản không?",
  },
  BCARE: {
    TITLE: "Chính sách hỗ trợ tai nạn",
    HEADER_TEXT: "Bất cứ công việc nào trên hệ thống bTaskee đều hỗ trợ tai nạn",
    ROLE_LABEL: "Vai trò",
    ROLE_TEXT: "Là Cộng tác viên trên hệ thống bTaskee",
    CONDITION_LABEL: "Điều kiện",
    CONDITION_TEXT: "Bảo vệ khi gặp tai nạn trong quá trình di chuyển đến nhà Khách hàng và thực hiện công việc trên hệ thống bTaskee dẫn đến:",
    CONDITION_TEXT_1: "• Tử vong",
    CONDITION_TEXT_2: "• Thương tật toàn bộ hoặc bộ phận vĩnh viễn do tai nạn.",
    FEE_LABEL: "Phí bảo vệ",
    FEE_TEXT: "Cộng tác viên ",
    FEE_TEXT_1: "không cần",
    FEE_TEXT_2: " đóng bất kỳ khoản phí bảo hiểm nào.",
    BENEFIT_LABEL: "Quyền lợi",
    BENEFIT_TEXT: "1. Cộng tác viên sẽ được:",
    BENEFIT_TEXT_1: "• Hỗ trợ chi phí nếu tai nạn dẫn đến tử vong.",
    BENEFIT_TEXT_2: "• Hỗ trợ chi phí nếu tai nạn dẫn đến: thương tật toàn bộ hoặc một bộ phận vĩnh viễn.",
    BENEFIT_TEXT_3: "• Hỗ trợ tài chính trong thời gian nằm viện điều trị do tai nạn.",
    BENEFIT_TEXT_4: "• Hỗ trợ chi phí điều trị y tế do tai nạn.",
    BENEFIT_TEXT_5: "2. bTaskee sẽ chủ động hỗ trợ giải quyết các quyền lợi được bảo vệ",
    AMOUNT_LABEL: "Mức bảo vệ",
    AMOUNT_TEXT: "Mức tiền hỗ trợ linh động đến tối đa ",
    AMOUNT_TEXT_1: "100,000,000đ.",
    PROCEDURE_LABEL: "Quy trình hỗ trợ",
    PROCEDURE_TEXT_1: "Khi xảy ra tai nạn thông báo đến bTaskee qua hotline 0901.300.501 - nhấn phím 8.",
    PROCEDURE_TEXT_2: "Giữ lại tất cả các chứng từ, hoá đơn liên quan đến việc khám chữa bệnh và gửi đến công ty không quá 30 ngày kể từ khi xuất viện để được hỗ trợ bảo hiểm trong vòng 30 ngày kể từ ngày đến trình báo.",
    PROCEDURE_TEXT_3: "Lấy hoá đơn đỏ khi mua thuốc ngoài bệnh viện trị giá trên 200.000đ.",
    REQUIRE_LABEL: "Yêu cầu",
    REQUIRE_TEXT_1: "Hoá đơn",
    REQUIRE_TEXT_2: "Tiền thuốc",
    REQUIRE_TEXT_3: "Giấy khám chữa bệnh",
    NOTE: "Lưu ý:",
    NOTE_TEXT_1: "• Phải rõ ràng, hợp lý có chữ ký và đóng dấu của bệnh viện, nhà thuốc và thông tin của bệnh nhân.",
    NOTE_TEXT_2: "• Cộng Tác Viên cần điền đầy đủ giấy tờ theo yêu cầu để cung cấp cho công ty xem xét mức hỗ trợ.",
  },
  REFERRAL: {
    TITLE:"Nhập mã giới thiệu để nhận quà.",
    YES:"Có",
    NO:"Không"
  },
  MODAL_ALERT: {
    TITLE_MODAL_TIP: "Xin chúc mừng",
    LABEL_MODAL_TIP: "Bạn vừa nhận được tiền tip từ khách hàng",
    TEXT_MODAL_TIP: "Kỹ năng, chất lượng công việc và thái độ cung ứng dịch vụ của bạn xứng đáng nhận được phần thưởng này từ khách hàng. Hãy tiếp tục phấn đấu và chiếm trọn trái tim của nhiều khách hàng hơn nhé!",
    TITLE_MODAL_LEVEL_UP: "Thăng cấp"
  },
  PROCEDURE_ACTIVE_ACCOUNT: {
    BUTTON_TEST_NOW: "Bắt đầu ngay",
    TITLE_STEP_1: "Bài kiểm tra đầu vào",
    TITLE_STEP_2: "Bài kiểm tra cơ bản",
    TITLE_STEP_3: "Cập nhật hồ sơ",
    CONTENT_STEP_1: "Hãy xem bạn đã có bao nhiêu kỹ năng và tư duy phù hợp với Nghề giúp việc nhé!",
    CONTENT_STEP_2: "Hãy tham gia chương trình đào tạo những kỹ năng cơ bản trước khi bạn tham gia hệ thống nhé!",
    CONTENT_STEP_3: "Chúc mừng bạn là một ứng viên tiềm năng của bTaskee và chắc rằng trong hành trình tới chúng ta sẽ cùng nhau gặt hái được nhiều thành công.",
    NUMBER_OF_TIME_TEST: "Số lần đã làm bài kiểm tra",
    TEXT_SUCCESS: "Hoàn thành",
    TEST_FALSE: "Bạn đã vượt quá số lần làm bài quy định. Vui lòng gọi tổng đài để được hổ trợ.",
    MAKE_APPOINTMENT: "Đặt lịch hẹn",
    ACTIVE_SUCCESS_TITLE: "Chúc mừng",
    ACTIVE_SUCCESS_CONTENT: "Chúc mừng bạn đã hoàn tất quá trình nộp hồ sơ. Hãy lưu ý Chúng ta có lịch hẹn trực tiếp tại văn phòng nhé! Khi đi vui lòng mang theo hồ sơ photo công chứng và hồ sơ gốc bao gồm: CCCD/CMND - Sổ hộ khẩu/Xác nhận thông tin cư trú - Sơ yếu lý lịch - Xác nhận hạnh kiểm.",
    TITLE_MAKE_AN_APPOINTMENT: "Đặt lịch hẹn",
    BUTTON_CHAT: "Chat",
    BUTTON_CALL: "Gọi ngay",
    MORNING_APPOINTMENT: "Buổi sáng - 09:00",
    AFTERNOON_APPOINTMENT: "Buổi chiều - 14:00",
    TITLE_SELECT_TIME: "Chọn thời gian",
    LABEL_DATE: "Ngày",
    LABEL_TIME: "Giờ",
    NOTE_SELECT_TIME: "Lưu ý: Vui lòng đến đúng giờ hẹn vì việc chậm trễ có thể gây ảnh hưởng đến sự hỗ trợ của Nhân sự.",
    TITLE_SELECT_PLACE: "Chọn địa điểm",
    APPROVED_TITLE: "Đã duyệt",
    APPROVED_CONTENT: "Chúc mừng bạn đã hoàn thành việc cập nhật hồ sơ bước đầu. Vui lòng chọn lịch hẹn đến văn phòng gần nhất để được hỗ trợ kích hoạt tài khoản.",
    PROCESSING_TITLE: "Đang xử lý",
    PROCESSING_CONTENT: "Hồ sơ của bạn đang được kiểm duyệt. Hệ thống sẽ thông báo cho bạn biết kết quả trong thời gian sớm nhất.",
    BUTTON_UPDATE_PROFILE:"Cập nhật hồ sơ",
    REJECTED_TITLE: "Đã từ chối",
  },
  SUPPLEMENT_INFO:{
    TITLE_ADD_SUPPLEMENT:"Bổ sung hồ sơ",
    NOTE_SUPPLEMENT_1:"• Tất cả các tài liệu phải được công chứng trong vòng 6 tháng qua.",
    NOTE_SUPPLEMENT_2:"• Vui lòng sử dụng cùng một loại tài liệu để chụp ảnh mặt trước và mặt sau.",
    NOTE_SUPPLEMENT_3:"• Vui lòng chụp ảnh rõ nét, không cắt góc và tránh lóa các thông tin quan trọng trên tài liệu.",
    TEXT_IDENTITY:"Căn cước công dân",
    TEXT_RESIDENCY:"Giấy xác nhận cư trú",
    TEXT_CURRICULUM:"Sơ yếu lý lịch",
    TEXT_CERTIFICATE:"Giấy xác nhận hạnh kiểm",
    TEXT_REQUIRE:"* bắt buộc",
    TEXT_OPTIONAL:"* bạn có thể bổ sung sau",
    TEXT_SUPPLEMENT_NOTE:"Vui lòng chụp ảnh các tài liệu bổ sung cho hồ sơ của bạn",
    OPEN_PHOTO_GALLERY:"Mở ảnh từ thư viện",
    OPEN_IMAGE_CAMERA:"Chụp ảnh từ máy ảnh ",
    TEXT_NOTE_IDENTITY_1:"• Đảm bảo môi trường chụp ảnh có đủ độ sáng.",
    TEXT_NOTE_IDENTITY_2:"• Đối tượng chính được định vị ở trung tâm và nằm gọn trong khu vực tạo khung.",
    TAKE_A_PHOTO:"Chụp ảnh",
    IMAGE_FRONT_SIDE:"Mặt trước",
    IMAGE_BACK_SIDE:"Mặt sau",
    UPLOAD:"Tải lên",
    REUPLOAD:"Tải lên lại",
    OPEN_CAMERA:"Mở máy ảnh",
    CHOOSE_PHOTO:"Chọn ảnh từ ",
    UPLOAD_IMAGE:"Tải ảnh lên"
  },
  JOURNEY:{
    TITLE:"Hành trình",
    LEADER_BOARD_SCREEN:"Bảng xếp hạng",
    TITLE_MAIN_PRIZE: "Quyền lợi:",
    TITLE_BONUS: "Phần thưởng:",
    BUTTON_GET_REWARD: "Nhận thưởng ngay",
    TRAINING: "Đào tạo ngay",
    TASK: "Về trang chủ",
    TITLE_ALERT: "Chi tiết",
    TITLE_NUMBER_OF_TASK: "{{t}} Công việc",
    TITLE_CURRENT_LEVEL: "Cấp độ hiện tại",
    AVG_RATING_CONDITION: "Số sao trung bình từ {{t}} trở lên",
    MESSAGE_GET_REWARD_SUCCESS: "Chúc mừng bạn nhận quà thành công",
    TITLE_RECEIVED_REWARD: "Đã nhận:",
    BONUS_PRIZE: "Phần thưởng thêm",
    LABEL_TIME_PASSED: "Thời gian đã qua",
    TITLE_PRIZE_BONUS_DETAIL: "Chi tiết phần thưởng thêm",
    TITLE_PRIZE_BONUS: "Phần thưởng thêm",
    HOURS: "{{t}} giờ",
    DAYS: "{{t}} ngày ",
    TRAINING_PASSED: "Hoàn thành",
    TRAINING_INCOMPLETE: "Chưa đạt",
    BONUS_NOT_RECEIVE: "Quà chưa nhận:",
    RECEIVE_AT_OFFICE: " (nhận tại văn phòng)",
    LABEL_PROCESSING: "Đang tiến hành",
    LABEL_PASSED: "Đã hoàn thành",
    LABEL_LOCKED: "Khóa",
    LABEL_MISSION: "Nhiệm vụ:",
    LEADER_BOARD_EMPTY: "Danh sách đang được cập nhật!",
    TEXT_MODAL_ALERT_LEVEL_UP: "Chúc mừng bạn đã đạt đến",
    DESCRIPTION_MODAL_ALERT_LEVEL_UP: "Nhận phần thưởng cho những nỗ lực của bạn và cố gắng hơn nữa trong tương lai nhé các chị Ong!",
    TITLE_BUTTON_SEE_REWARD: "Xem phần thưởng",
    TITLE_BUTTON_NEXT_REWARD: "Phần thưởng tiếp theo",
    LABEL_MODAL_ALERT_LEVEL_UP_REWARD: "Xin chúc mừng",
    TEXT_BONUS_PRIZE: "Nhận thêm",
    TITLE_BUTTON_RANK_SCORE: "Tính điểm xếp hạng như thế nào?",
    TITLE_CALCULATE_SCORE: "Cách tính điểm",
    TITLE_HOW_TO_CALCULATE_SCORE: "Cách tính điểm xếp hạng",
    TEXT_CALCULATE_SCORE_1: "Sau khi hoàn thành 1 công việc, điểm của bạn sẽ được tính dựa trên công thức:",
    TEXT_CALCULATE_SCORE_2: "Điểm xếp hạng cộng thêm = ",
    TEXT_CALCULATE_SCORE_3: " “Đánh giá chất lượng phục vụ” ",
    TEXT_CALCULATE_SCORE_4: " “Thời gian hoàn thành công việc” ",
    TEXT_CALCULATE_SCORE_5: "Ví dụ khi hoàn thành **1 công việc** có yêu cầu thực hiện từ **12:00 đến 16:00 (4 tiếng)** và được khách hàng đánh giá **5 sao**, thì bạn sẽ có:",
    TEXT_CALCULATE_SCORE_6: "1 + 4 + 5 = 10 (điểm)",
    TITLE_RATING_SERVICE_QUALITY: "Đánh giá chất lượng dịch vụ",
    TEXT_RATING_SERVICE_QUALITY_1: "Từ 1 cho đến 5",
    TEXT_RATING_SERVICE_QUALITY_2: "Khi hoàn thành xong công việc, hãy nhớ nhắc nhở khách hàng đánh giá chất lượng dịch vụ để được thêm điểm xếp hạng. Cố gắng làm thật tốt để được đánh giá 5 sao thì bạn sẽ có 5 điểm.",
    TITLE_DURATION: "Thời gian hoàn thành công việc",
    TEXT_DURATION_1: "Dựa trên thời gian yêu cầu của công việc",
    TEXT_DURATION_2: "Lưu ý rằng thời gian thực hiện công việc đã được cố định khi khách hàng đặt dịch vụ, bạn không thể cố tình trì hoãn hoàn thành công việc lâu hơn để kiếm thêm điểm.",
    TITLE_DETAIL_JOURNEY: "Chi tiết Hành trình",
    LEARN_MORE: "Tìm hiểu thêm",
    DESCRIPTION_LEARN_MORE: "Chị Ong có thể xem thêm toàn bộ các thông tin về Hành trình Ong tại đây",
    COMING_SOON: "Sắp ra mắt",
    CURRENT_LEVEL: "Cấp độ hiện tại",
    TEXT_TRAINING_TO_RECEIVE_BONUS: "Hoàn thành đào tạo để nhận thưởng",
  },
  MEMBER_INFO: {
    TITLE: "Thông tin thành viên",
    BPOINT_HISTORY: "Lịch sử bPoints",
    VIEW: "Xem",
    SEE_NOW: "Xem ngay",
    LABEL_AVAILABLE_POINT: "Số bPoint khả dụng",
    BROWSE_BREWARD: "Xem các ưu đãi",
    RECOMMEND_FOR_YOU: "Gợi ý cho bạn"
  },
  BREWARD: {
    RECOMMEND_FOR_YOU: "Gợi ý cho bạn",
    FLASH_SALES: "Siêu ưu đãi",
    TOP_DEALS: "Ưu đãi phổ biến",
    EXCLUSIVE_DEALS: "Ưu đãi độc quyền",
    VIEW_MORE: "Xem thêm",
    REDEM_NOW: "Đổi quà ngay",
    ALL: "Tất cả",
    TITLE_BPOINT_HISTORY_RECEIVED: "Đã nhận",
    TITLE_BPOINT_HISTORY_USED: "Đã sử dụng",
    EMPTY_TRANSACTION: "Bạn chưa có giao dịch nào!",
    TITLE_BUTTON_VIEW_MORE: "Hiển thị thêm",
    EXPIRED_DATE:"Ngày hết hạn",
    MY_REWARD: "Ưu đãi của tôi",
    RECENT_SEARCHES:"Tìm kiếm gần đây",
    VOUCHERS_SEARCHES:"Tìm kiếm, gõ vào đây",
    SEARCH:"Tìm kiếm phiếu giảm giá theo tên của phiếu giảm giá: Giảm giá ...",
    BUTTON_AGREE:"Đồng ý",
    BUTTON_LATER:"Để sau",
    TITLE_CONTACT:"Liên hệ",
    STORE:"Danh sách cửa hàng",
    BRANCH_STORE:"Hiện tại có {{t}} chi nhánh hoạt động",
    BRANCH_STORE_EMPTY:"Danh sách các cửa hàng đang được cập nhật",
    DOW_IOS:"Tải trên App Store",
    DOW_ANDROID:"Tải trên Google Play",
    DOW:"Tải ứng dụng",
    OUT_OF_STOCK: "Hết lượt đổi",
  },
  WEATHER:{
    TITLE: "Thời tiết",
    BY_DATE: "Theo ngày",
    BY_HOUR: "Theo giờ",
    PARTLY_CLOUDY: "Có mây",
    MODERATE_RAIN: "Mưa vừa",
    PATCHY_RAIN_POSSIBLE: "Mưa rải rác",
    SUNNY: "Nhiều nắng",
    CLEAR: "Trời quang",
    OVERCAST: "U ám",
    CLOUDY: "Nhiều mây",
    LIGHT_RAIN: "Mưa nhẹ",
    MODERATE_RAIN_AT_TIME: "Thỉnh thoảng mưa vừa",
    HEAVY_RAIN: "Mưa rơi nặng hạt",
    HEAVY_RAIN_AT_TIME: "Thỉnh thoảng mưa nặng hạt",
    MODERATE_OR_HEAVY_FREEZING_RAIN: "Mưa giá rét vừa hoặc nặng hạt",
    MODERATE_OR_HEAVY_RAIN_SHOWER: "Mưa rào vừa hoặc nặng hạt",
    MODERATE_OR_HEAVY_RAIN_WITH_THUNDER: "Mưa vừa hoặc mưa to có sấm sét",
    MIST: "Sương mù",
    FOG: "Sương mù",
    PATCHY_RAIN_NEARBY: "Mưa lả tả gần đó",
    PATCHY_SNOW_NEARBY: "Tuyết rơi lả tả gần đó",
    PATCHY_SLEET_NEARBY: "Mưa tuyết lả tả gần đó",
    PATCHY_FREEZING_DRIZZLE_NEARBY: "Mưa phùn băng giá lả tả gần đó",
    THUNDERY_OUTBREAKS_IN_NEARBY: "Các cơn giông tố nổi lên gần đó",
    FREEZING_FOG: "Sương mù băng giá",
    PATCHY_LIGHT_DRIZZLE: "Mưa phùn nhẹ lả tả",
    LIGHT_DRIZZLE: "Mưa phùn nhẹ",
    FREEZING_DRIZZLE: "Mưa phùn băng giá",
  }
};
